#!/usr/bin/env python3
"""Generate sparse pure-shell projection kernels for two-electron blocks."""

from __future__ import annotations

from math import comb, sqrt
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "source" / "integrals" / "int2_pure_generated.F90"

CART_MONOMIALS = {
    0: [(0, 0, 0)],
    1: [(1, 0, 0), (0, 1, 0), (0, 0, 1)],
    2: [(2, 0, 0), (0, 2, 0), (0, 0, 2), (1, 1, 0), (1, 0, 1), (0, 1, 1)],
    3: [
        (3, 0, 0), (0, 3, 0), (0, 0, 3), (2, 1, 0), (2, 0, 1),
        (1, 2, 0), (0, 2, 1), (1, 0, 2), (0, 1, 2), (1, 1, 1),
    ],
    4: [
        (4, 0, 0), (0, 4, 0), (0, 0, 4), (3, 1, 0), (3, 0, 1),
        (1, 3, 0), (0, 3, 1), (1, 0, 3), (0, 1, 3), (2, 2, 0),
        (2, 0, 2), (0, 2, 2), (2, 1, 1), (1, 2, 1), (1, 1, 2),
    ],
    5: [
        (5, 0, 0), (0, 5, 0), (0, 0, 5), (4, 1, 0), (4, 0, 1),
        (1, 4, 0), (0, 4, 1), (1, 0, 4), (0, 1, 4), (3, 2, 0),
        (3, 0, 2), (2, 3, 0), (0, 3, 2), (2, 0, 3), (0, 2, 3),
        (3, 1, 1), (1, 3, 1), (1, 1, 3), (2, 2, 1), (2, 1, 2),
        (1, 2, 2),
    ],
    6: [
        (6, 0, 0), (0, 6, 0), (0, 0, 6), (5, 1, 0), (5, 0, 1),
        (1, 5, 0), (0, 5, 1), (1, 0, 5), (0, 1, 5), (4, 2, 0),
        (4, 0, 2), (2, 4, 0), (0, 4, 2), (2, 0, 4), (0, 2, 4),
        (4, 1, 1), (1, 4, 1), (1, 1, 4), (3, 3, 0), (3, 0, 3),
        (0, 3, 3), (3, 2, 1), (3, 1, 2), (2, 3, 1), (1, 3, 2),
        (2, 1, 3), (1, 2, 3), (2, 2, 2),
    ],
}


def double_factorial(n: int) -> int:
    result = 1
    while n > 1:
        result *= n
        n -= 2
    return result


def mat_vec(metric: list[list[float]], row: list[float]) -> list[float]:
    return [sum(metric[i][j] * row[j] for j in range(len(row))) for i in range(len(row))]


def solid_harmonic_coefficients(l: int) -> list[list[float]]:
    """Return B(cart, sph), matching cart2sph.F90 and symmetry.py."""
    monomials = CART_MONOMIALS[l]
    index = {mono: i for i, mono in enumerate(monomials)}
    norms = [
        1.0 / sqrt(
            double_factorial(2 * ax - 1)
            * double_factorial(2 * ay - 1)
            * double_factorial(2 * az - 1)
        )
        for ax, ay, az in monomials
    ]

    size = len(monomials)
    metric = [[0.0 for _ in range(size)] for _ in range(size)]
    for i, (ax, ay, az) in enumerate(monomials):
        for j, (bx, by, bz) in enumerate(monomials):
            if (ax + bx) % 2 or (ay + by) % 2 or (az + bz) % 2:
                continue
            metric[i][j] = (
                double_factorial(ax + bx - 1)
                * double_factorial(ay + by - 1)
                * double_factorial(az + bz - 1)
                * norms[i]
                * norms[j]
            )

    cols = []
    for m in range(-l, l + 1):
        am = abs(m)
        coeff_mono = [0.0 for _ in range(size)]
        for t in range((l - am) // 2 + 1):
            for u in range(t + 1):
                k_start = 0 if m >= 0 else 1
                for k in range(k_start, am + 1, 2):
                    sign_pow = t + (k - k_start) // 2
                    coeff = (
                        (-1) ** sign_pow
                        * (0.25 ** t)
                        * comb(l, t)
                        * comb(l - t, am + t)
                        * comb(t, u)
                        * comb(am, k)
                    )
                    ax = 2 * t + am - 2 * u - k
                    ay = 2 * u + k
                    az = l - 2 * t - am
                    if ax < 0 or ay < 0 or az < 0:
                        continue
                    coeff_mono[index[(ax, ay, az)]] += coeff
        row = [coeff_mono[i] / norms[i] for i in range(size)]
        metric_row = mat_vec(metric, row)
        norm2 = sum(row[i] * metric_row[i] for i in range(size))
        cols.append([x / sqrt(norm2) for x in row])

    return [[cols[s][c] for s in range(2 * l + 1)] for c in range(size)]


def f90(value: float) -> str:
    return f"{value:.15e}_dp".replace("e", "e")


def emit_load(l: int, b: list[list[float]], threshold: float = 1.0e-14) -> list[str]:
    lines = [
        f"  subroutine load_l{l}(proj)",
        "    type(int2_shell_projection_t), intent(inout) :: proj",
    ]
    for cart_idx, row in enumerate(b, start=1):
        for out_idx, coeff in enumerate(row, start=1):
            if abs(coeff) <= threshold:
                continue
            lines.append(f"    call add_term(proj, {cart_idx:2d}, {out_idx:2d}, {f90(coeff)})")
    lines += [f"  end subroutine load_l{l}", ""]
    return lines


def main() -> None:
    blocks = {l: solid_harmonic_coefficients(l) for l in range(2, 7)}
    max_terms = max(
        sum(1 for coeff in row if abs(coeff) > 1.0e-14)
        for block in blocks.values()
        for row in block
    )
    lines = [
        "! Generated by tools/generate_int2_pure_kernels.py; do not edit by hand.",
        "module int2_pure_generated",
        "  use precision, only: dp",
        "  use constants, only: BAS_MXCART, BAS_MXANG, NUM_CART_BF, NUM_SPH_BF",
        "  implicit none",
        "  private",
        f"  integer, parameter, public :: INT2_PURE_MAX_TERMS = {max_terms}",
        "",
        "  type, public :: int2_shell_projection_t",
        "    integer :: ncart = 0",
        "    integer :: nout = 0",
        "    integer :: nterm(BAS_MXCART) = 0",
        "    integer :: out_idx(INT2_PURE_MAX_TERMS, BAS_MXCART) = 0",
        "    real(dp) :: coeff(INT2_PURE_MAX_TERMS, BAS_MXCART) = 0.0_dp",
        "  end type int2_shell_projection_t",
        "",
        "  public :: int2_init_shell_projection",
        "  public :: int2_project_pure_block",
        "",
        "contains",
        "",
        "  subroutine int2_init_shell_projection(l, pure, proj)",
        "    integer, intent(in) :: l, pure",
        "    type(int2_shell_projection_t), intent(out) :: proj",
        "    integer :: c",
        "",
        "    if (l < 0 .or. l > BAS_MXANG) error stop 'int2_pure_generated: angular momentum out of range'",
        "    proj = int2_shell_projection_t()",
        "    proj%ncart = NUM_CART_BF(l)",
        "    proj%nout = proj%ncart",
        "",
        "    if (pure == 1 .and. l >= 2) then",
        "      proj%nout = NUM_SPH_BF(l)",
        "      select case (l)",
        "      case (2)",
        "        call load_l2(proj)",
        "      case (3)",
        "        call load_l3(proj)",
        "      case (4)",
        "        call load_l4(proj)",
        "      case (5)",
        "        call load_l5(proj)",
        "      case (6)",
        "        call load_l6(proj)",
        "      case default",
        "        error stop 'int2_pure_generated: unsupported pure angular momentum'",
        "      end select",
        "    else",
        "      do c = 1, proj%ncart",
        "        call add_term(proj, c, c, 1.0_dp)",
        "      end do",
        "    end if",
        "  end subroutine int2_init_shell_projection",
        "",
        "  subroutine int2_project_pure_block(ints, am, pure, nbf, nbf_out)",
        "    real(dp), intent(inout), target :: ints(:)",
        "    integer, intent(in) :: am(4), pure(4), nbf(4)",
        "    integer, intent(out) :: nbf_out(4)",
        "    type(int2_shell_projection_t) :: proj(4)",
        "    real(dp), allocatable, target :: cart(:)",
        "    real(dp), pointer :: src(:,:,:,:), dst(:,:,:,:)",
        "    integer :: c1, c2, c3, c4, t1, t2, t3, t4",
        "    integer :: o1, o2, o3, o4, s",
        "    real(dp) :: val, v1, v2, v3",
        "",
        "    do s = 1, 4",
        "      call int2_init_shell_projection(am(s), pure(s), proj(s))",
        "      nbf_out(s) = proj(s)%nout",
        "    end do",
        "    if (all(nbf_out == nbf)) return",
        "",
        "    allocate(cart(product(nbf)))",
        "    cart = ints(1:product(nbf))",
        "    ints(1:product(nbf_out)) = 0.0_dp",
        "    src(1:nbf(1), 1:nbf(2), 1:nbf(3), 1:nbf(4)) => cart",
        "    dst(1:nbf_out(1), 1:nbf_out(2), 1:nbf_out(3), 1:nbf_out(4)) => ints",
        "",
        "    do c4 = 1, proj(4)%ncart",
        "      do c3 = 1, proj(3)%ncart",
        "        do c2 = 1, proj(2)%ncart",
        "          do c1 = 1, proj(1)%ncart",
        "            val = src(c1,c2,c3,c4)",
        "            if (val == 0.0_dp) cycle",
        "            do t4 = 1, proj(4)%nterm(c4)",
        "              o4 = proj(4)%out_idx(t4,c4)",
        "              v3 = val * proj(4)%coeff(t4,c4)",
        "              do t3 = 1, proj(3)%nterm(c3)",
        "                o3 = proj(3)%out_idx(t3,c3)",
        "                v2 = v3 * proj(3)%coeff(t3,c3)",
        "                do t2 = 1, proj(2)%nterm(c2)",
        "                  o2 = proj(2)%out_idx(t2,c2)",
        "                  v1 = v2 * proj(2)%coeff(t2,c2)",
        "                  do t1 = 1, proj(1)%nterm(c1)",
        "                    o1 = proj(1)%out_idx(t1,c1)",
        "                    dst(o1,o2,o3,o4) = dst(o1,o2,o3,o4) + v1 * proj(1)%coeff(t1,c1)",
        "                  end do",
        "                end do",
        "              end do",
        "            end do",
        "          end do",
        "        end do",
        "      end do",
        "    end do",
        "    deallocate(cart)",
        "  end subroutine int2_project_pure_block",
        "",
        "  subroutine add_term(proj, cart_idx, out_idx, coeff)",
        "    type(int2_shell_projection_t), intent(inout) :: proj",
        "    integer, intent(in) :: cart_idx, out_idx",
        "    real(dp), intent(in) :: coeff",
        "    integer :: slot",
        "    slot = proj%nterm(cart_idx) + 1",
        "    if (slot > INT2_PURE_MAX_TERMS) error stop 'int2_pure_generated: sparse row overflow'",
        "    proj%nterm(cart_idx) = slot",
        "    proj%out_idx(slot, cart_idx) = out_idx",
        "    proj%coeff(slot, cart_idx) = coeff",
        "  end subroutine add_term",
        "",
    ]
    for l, block in blocks.items():
        lines.extend(emit_load(l, block))
    lines.append("end module int2_pure_generated")
    OUT.write_text("\n".join(lines) + "\n", encoding="ascii")


if __name__ == "__main__":
    main()
