apply_basis_C – OPENQP
apply_basis_C Subroutine
8 statements
Source File
public subroutine apply_basis_C(c_handle) bind(C, name="apply_basis")
Uses
c_interop
types
Arguments
Type Intent Optional Attributes Name
type(oqp_handle_t) :: c_handle
Calls
Source Code
  subroutine apply_basis_C(c_handle) bind(C, name="apply_basis")
    use c_interop, only: oqp_handle_t, oqp_handle_get_info
    use types, only: information
    type(oqp_handle_t) :: c_handle
    type(information), pointer :: inf
    inf => oqp_handle_get_info(c_handle)
    call oqp_apply_basis(inf)
  end subroutine apply_basis_C
Call graph
apply_basis_c calls oqp_handle_get_info, oqp_apply_basis
oqp_apply_basis calls data_has_tags, tagarray_get_data, map_shell2basis_set, bcast, init, print_basis