atomic_structure_center – OPENQP
atomic_structure_center Function
21 statements
Source File
public function atomic_structure_center(self, weight) result(r)
Uses
strings
Type Bound
atomic_structure
Arguments
Type Intent Optional Attributes Name
class(atomic_structure) :: self
character(len=*), optional :: weight
Return Value real(kind=c_double), (3)
Calls
Called by
Source Code
  function atomic_structure_center(self, weight) result(r)
    use strings, only: to_upper
    implicit none
    class(atomic_structure) :: self
    character(len=*), optional :: weight
    real(c_double) :: r(3)
    character(len=8) :: wtype
    character(len=8), parameter :: WTYPE_NONE = 'NONE'
    character(len=8), parameter :: WTYPE_MASS = 'MASS'
    wtype = WTYPE_NONE
    if (present(weight)) wtype = to_upper(weight)
    r = 0
    select case (wtype)
    case(WTYPE_NONE)
      r = sum(self%xyz,2)/ubound(self%xyz,2)
    case(WTYPE_MASS)
      r = matmul(self%xyz,self%mass)/sum(self%mass)
    case default
      error stop "Unknown weight type in atomic_structure_center: "//wtype
    end select
  end function atomic_structure_center
Call graph
atomic_structure_center calls to_upper
get_td_transition_dipole calls atomic_structure_center
get_transition_dipole calls atomic_structure_center
tdhf_energy calls get_td_transition_dipole
tdhf_mrsf_energy calls get_transition_dipole
tdhf_sf_energy calls get_transition_dipole
tdhf_energy_c calls tdhf_energy
tdhf_mrsf_energy_c calls tdhf_mrsf_energy
tdhf_sf_energy_c calls tdhf_sf_energy