basis_overlap – OPENQP
basis_overlap Subroutine
24 statements
Source File
public subroutine basis_overlap(s, basis1, basis2, tol)
@brief Compute overlap matrix between two basis sets @details Overlap integrals are computed using Gauss-Hermite quadrature formula @author Igor S. Gerasimov @date Oct, 2022 Initial release
@param[in,out] s unpacked matrix of overlap integrals @param[in] basis1 basis w/ SP-shells separated @param[in] basis2 basis w/ SP-shells separated @param[in] tol 1-e exponential prefactor tolerance (should be ~tol_int*log(10.0_dp))
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(inout), CONTIGUOUS :: s(:,:)
type(basis_set), intent(in) :: basis1
type(basis_set), intent(in) :: basis2
real(kind=REAL64), intent(in) :: tol
Calls
Called by
Call graph
basis_overlap calls alloc2, fetch_by_id, shell_pair2, comp_kin_ovl_int1_prim, update_rectangular_matrix
comp_kin_ovl_int1_prim calls doquadgausshermite
doquadgausshermite calls abrt
get_structures_ao_overlap calls basis_overlap
huckel_guess calls basis_overlap
get_structures_ao_overlap_c calls get_structures_ao_overlap
guess_huckel calls huckel_guess
guess_huckel_c calls guess_huckel