c_f_char – OPENQP
c_f_char Function
15 statements
Source File
public function c_f_char(cchar) result(fstr)
Uses
iso_c_binding
@brief Convert raw null-terminated C-string to Fortran string
Note
No boundary checks for c-string are performed, use at your own risk!
Arguments
Type Intent Optional Attributes Name
character(kind=c_char, len=1), intent(in) :: cchar(*)
Return Value character(len=:), allocatable
Called by
Source Code
  function c_f_char(cchar) result(fstr)
    use, intrinsic :: iso_c_binding, only: c_char, c_null_char
    character(kind=c_char), intent(in) :: cchar(*)
    character(:), allocatable :: fstr
    integer :: i, strlen
    strlen = 0
    do
        if (cchar(strlen+1) == c_null_char) exit
        strlen = strlen + 1
    end do
    allocate(character(strlen) :: fstr)
    do i = 1, strlen
        fstr(i:i) = cchar(i)
    end do
  end function c_f_char
Call graph
dft_initialize calls c_f_char
hf_energy calls dft_initialize
hf_gradient calls dft_initialize
oqp_tdhf_z_vector calls dft_initialize
tdhf_energy calls dft_initialize
tdhf_gradient calls dft_initialize
tdhf_energy_c calls tdhf_energy
tdhf_gradient_c calls tdhf_gradient
tdhf_z_vector_c calls oqp_tdhf_z_vector