check_status – OPENQP
check_status Subroutine
10 statements
Source File
public subroutine check_status(status, modulename, subroutinename, tag, abort)
Uses
messages
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int32_t), intent(in) :: status
character(len=*), intent(in) :: modulename
character(len=*), intent(in) :: subroutinename
character(len=*), intent(in) :: tag
logical, intent(in), optional :: abort
Calls
Called by
Source Code
  subroutine check_status(status, modulename, subroutinename, tag, abort)
    use messages, only: show_message, WITHOUT_ABORT
    integer(c_int32_t), intent(in) :: status
    character(len=*), intent(in) :: modulename, subroutinename, tag
    logical, optional, intent(in) :: abort
    logical :: abort_
    abort_ = WITHOUT_ABORT
    if (present(abort)) abort_ = abort
    if (status /= TA_OK) call show_message( &
        modulename // "::" // subroutinename // ": " // get_status_message(status, trim(tag)), &
        abort_)
  end subroutine check_status
Call graph
check_status calls get_status_message, show_message
dftder calls check_status
electric_moments calls check_status
hf_energy calls check_status
hf_gradient calls check_status, dftder