comp_kin_ovl_int1_prim – OPENQP
comp_kin_ovl_int1_prim Subroutine
39 statements
Source File
public subroutine comp_kin_ovl_int1_prim(cp, id, dokinetic, sblk, tblk)
@brief Compute primitive block of overlap and kinetic energy 1e integrals @param[in] cp shell pair data @param[in] id current pair of primitives @param[in] dokinetic if .FALSE. compute only overlap integrals @param[inout] sblk block of 1e overlap integrals @param[inout] tblk block of 1e kinetic energy integrals @author Vladimir Mironov @date Sep, 2018 Initial release
Arguments
Type Intent Optional Attributes Name
type(shpair_t), intent(in) :: cp
integer, intent(in) :: id
logical, intent(in) :: dokinetic
real(kind=REAL64), intent(inout), CONTIGUOUS :: sblk(:)
real(kind=REAL64), intent(inout), CONTIGUOUS :: tblk(:)
Calls
Called by
Call graph
comp_kin_ovl_int1_prim calls doquadgausshermite
doquadgausshermite calls abrt
basis_overlap calls comp_kin_ovl_int1_prim
omp_hst calls comp_kin_ovl_int1_prim
overlap calls comp_kin_ovl_int1_prim
get_structures_ao_overlap calls basis_overlap
huckel_guess calls basis_overlap, overlap
int1e calls omp_hst
get_structures_ao_overlap_c calls get_structures_ao_overlap
guess_huckel calls huckel_guess
guess_huckel_c calls guess_huckel