comp_overlap_der1 – OPENQP
comp_overlap_der1 Subroutine
31 statements
Source File
public subroutine comp_overlap_der1(cp, dij, de)
@brief Compute 1e overlap contribution to the gradient @param[in] cp shell pair data @param[in] dij density matrix block @param[inout] de dimension(3), contribution to gradient @author Vladimir Mironov @date Sep, 2018 Initial release
Arguments
Type Intent Optional Attributes Name
type(shpair_t), intent(in) :: cp
real(kind=REAL64), intent(in) :: dij(:,:)
real(kind=REAL64), intent(inout), CONTIGUOUS :: de(:)
Calls
Called by
Call graph
comp_overlap_der1 calls doquadgausshermite
doquadgausshermite calls abrt
grad_ee_overlap calls comp_overlap_der1
hf_gradient calls grad_ee_overlap
tdhf_1e_grad calls grad_ee_overlap
tdhf_gradient calls tdhf_1e_grad
tdhf_gradient_c calls tdhf_gradient