comp_coulomb_der1 – OPENQP
comp_coulomb_der1 Subroutine
39 statements
Source File
public subroutine comp_coulomb_der1(cp, c, znuc, dij, dernuc)
@brief Compute 1e Coulomb contribution to the gradient (v.r.t. shifts of shell's centers) @param[in] nroots roots for GaussRys @param[in] cp shell pair data @param[in] c coordinates of the charged particle @param[in] znuc particle charge @param[in] dij density matrix block @param[inout] dernuc dimension(3), contribution to gradient @author Vladimir Mironov @date Sep, 2018 Initial release
Arguments
Type Intent Optional Attributes Name
type(shpair_t), intent(in) :: cp
real(kind=REAL64), intent(in) :: c(3)
real(kind=REAL64), intent(in) :: znuc
real(kind=REAL64), intent(in) :: dij(:,:)
real(kind=REAL64), intent(out) :: dernuc(3)
Calls
Called by
Call graph
comp_coulomb_der1 calls evaluate
grad_en_pulay calls comp_coulomb_der1
hf_gradient calls grad_en_pulay
tdhf_1e_grad calls grad_en_pulay
tdhf_gradient calls tdhf_1e_grad
tdhf_gradient_c calls tdhf_gradient