comp_lz_int1_prim – OPENQP
comp_lz_int1_prim Subroutine
32 statements
Source File
public subroutine comp_lz_int1_prim(cp, id, zblk)
@brief Compute primitive block of 1e Coulomb ESP integrals in FMO method @param[in] cp shell pair data @param[in] id current pair of primitives @param[inout] zblk block of 1e Lz-integrals @author Vladimir Mironov @date Sep, 2018 Initial release
Arguments
Type Intent Optional Attributes Name
type(shpair_t), intent(in) :: cp
integer, intent(in) :: id
real(kind=REAL64), intent(inout), CONTIGUOUS :: zblk(:)
Calls
Called by
Call graph
comp_lz_int1_prim calls doquadgausshermite
doquadgausshermite calls abrt
omp_hst calls comp_lz_int1_prim
int1e calls omp_hst