compute – OPENQP
compute Subroutine
17 statements
Source File
public subroutine compute(self, functional, wts)
Uses
functionals
Type Bound
xc_libxc_t
Arguments
Type Intent Optional Attributes Name
class(xc_libxc_t) :: self
class(functional_t) :: functional
real(kind=fp), intent(in) :: wts(:)
Calls
Called by
Call graph
compute calls calc_evfxc, calc_evxc, calc_xc, scalexc
run_xc calls compxc
derexc_blk calls run_xc
dmatd_blk calls run_xc
tddft_fxc calls run_xc
tddft_gxc calls run_xc
tddft_xc_gradient calls run_xc
utddft_fxc calls run_xc
utddft_xc_gradient calls run_xc
dftder calls derexc_blk
dftexcor calls dmatd_blk
oqp_tdhf_z_vector calls tddft_fxc, tddft_gxc
tdhf_energy calls tddft_fxc
tdhf_gradient calls tddft_xc_gradient
hf_gradient calls dftder
scf_driver calls dftexcor
tdhf_energy_c calls tdhf_energy
tdhf_gradient_c calls tdhf_gradient
tdhf_z_vector_c calls oqp_tdhf_z_vector
hf_energy calls scf_driver