density_ordered – OPENQP
density_ordered Subroutine
23 statements
Source File
public subroutine density_ordered(shi, shj, dij, denab)
@brief Copy density block from the triangular density matrix @details This subroutine assumes shi%shid>=shj%shid @param[in] shi first shell data @param[in] shj second shell data @param[in] dij density matrix in packed triangular form @param[out] denab density matrix block for shells shi and shj
Note
Used in HELFEY-based subroutines @author Vladimir Mironov @date Sep, 2018 Initial release
Arguments
Type Intent Optional Attributes Name
type(shell_t), intent(in) :: shi
type(shell_t), intent(in) :: shj
real(kind=REAL64), intent(out), CONTIGUOUS :: dij(:)
real(kind=REAL64), intent(in), CONTIGUOUS :: denab(:)
Called by
Call graph
electrostatic_potential calls density_ordered
oqp_resp_charges calls electrostatic_potential
resp_charges_c calls oqp_resp_charges