dft_initialize – OPENQP
dft_initialize Subroutine
17 statements
Source File
public subroutine dft_initialize(infos, basis, molGrid, orbitals_cutoff, verbose)
Uses
types
basis_tools
Arguments
Type Intent Optional Attributes Name
type(information), intent(inout) :: infos
type(basis_set), intent(inout) :: basis
type(dft_grid_t), intent(inout) :: molGrid
real(kind=dp), optional :: orbitals_cutoff
logical, optional :: verbose
Calls
Called by
Call graph
dft_initialize calls show_message, add_atomic_grid, add_grid, compress, find_neighbours, reset, set_screening, c_f_char, dft_fc_blk, get_radial_grid, libxc_input, set_bragg_slater
dft_fc_blk calls getbyid, set
get_radial_grid calls set, transform
libxc_input calls show_message, add_functional, can_calculate, xc_f03_reference, xc_f03_reference_doi, xc_f03_version_string
lebedev_get_grid calls show_message
hf_energy calls dft_initialize
hf_gradient calls dft_initialize
oqp_tdhf_z_vector calls dft_initialize
tdhf_energy calls dft_initialize
tdhf_gradient calls dft_initialize
tdhf_energy_c calls tdhf_energy
tdhf_gradient_c calls tdhf_gradient
tdhf_z_vector_c calls oqp_tdhf_z_vector