dft_fc_blk – OPENQP
dft_fc_blk Subroutine
39 statements
Source File
public subroutine dft_fc_blk(molGrid, dft_partfun, atmxyz, at_mx_dist2, rij, nat, wtab, aij)
Uses
basis_tools
@brief Assemble numerical atomic DFT grids to a molecular grid @param[in] atmxvec array of atomic X coordinates @param[in] atmyvec array of atomic Y coordinates @param[in] atmzvec array of atomic Z coordinates @param[in] rij interatomic distances @param[in] nat number of atoms @param[in] curAt index of current atom @param[in] rad effective (e.g. Bragg-Slater) radius of current atom @param[inout] wtab normalized cell function values for LRD @param[in] aij surface shifting factors for Becke's method @author Vladimir Mironov
Arguments
Type Intent Optional Attributes Name
type(dft_grid_t), intent(inout) :: molGrid
integer, intent(in) :: dft_partfun
real(kind=fp), intent(in) :: atmxyz(:,:)
real(kind=fp), intent(in) :: at_mx_dist2(:)
real(kind=fp), intent(in) :: rij(nat,nat)
integer, intent(in) :: nat
real(kind=fp), intent(inout), allocatable :: wtab(:,:,:)
real(kind=fp), intent(in), optional, contiguous :: aij(:,:)
Calls
Called by
Call graph
dft_fc_blk calls getbyid, set
dft_initialize calls dft_fc_blk
hf_energy calls dft_initialize
hf_gradient calls dft_initialize
oqp_tdhf_z_vector calls dft_initialize
tdhf_energy calls dft_initialize
tdhf_gradient calls dft_initialize
tdhf_energy_c calls tdhf_energy
tdhf_gradient_c calls tdhf_gradient
tdhf_z_vector_c calls oqp_tdhf_z_vector