dftclean – OPENQP
dftclean Subroutine
6 statements
Source File
public subroutine dftclean(infos)
Uses
types
libxc
Arguments
Type Intent Optional Attributes Name
type(information), intent(inout) :: infos
Calls
Called by
Call graph
dftclean calls libxc_destroy
libxc_destroy calls destroy
hf_energy calls dftclean
hf_gradient calls dftclean
oqp_tdhf_z_vector calls dftclean
tdhf_energy calls dftclean
tdhf_gradient calls dftclean
tdhf_energy_c calls tdhf_energy
tdhf_gradient_c calls tdhf_gradient
tdhf_z_vector_c calls oqp_tdhf_z_vector