dftder – OPENQP
dftder Subroutine
47 statements
Source File
public subroutine dftder(basis, infos, molGrid)
Uses
types
mathlib
mod_dft_gridint_grad
oqp_tagarray_driver
@brief Analytical DFT gradient
Arguments
Type Intent Optional Attributes Name
type(basis_set) :: basis
type(information), intent(inout) :: infos
type(dft_grid_t), intent(inout) :: molGrid
Calls
Called by
Call graph
dftder calls show_message, tagarray_get_data, unpack_matrix, check_status, derexc_blk
unpack_matrix calls unpack_f90
check_status calls show_message, get_status_message
derexc_blk calls clean, init, run_xc
run_xc calls allreduce, compaos, compxc, getslicenonzero, getstats, init, pruneaos, resetpointers, parallel_start, parallel_stop, postUpdate, update
unpack_f90 calls show_message, oqp_dtpttr_i64
oqp_dtpttr_i64 calls show_message, dtpttr
compute calls calc_evfxc, calc_evxc, calc_xc, scalexc
init calls clean, resetenergy
mo_tran_gemm_ calls oqp_dgemm_i64
mo_tran_symm_ calls oqp_dsymm_i64
oqp_dgemm_i64 calls show_message, dgemm
oqp_dsymm_i64 calls show_message, dsymm
hf_gradient calls dftder