dftexcor – OPENQP
dftexcor Subroutine
23 statements
Source File
public subroutine dftexcor(basis, molGrid, iscftyp, fa, fb, coeffa, coeffb, nbf, nbf_tri, eexc, totele, totkin, infos)
Uses
types
basis_tools
mod_dft_gridint_energy
Arguments
Type Intent Optional Attributes Name
type(basis_set) :: basis
type(dft_grid_t), intent(in) :: molGrid
integer, intent(in) :: iscftyp
real(kind=dp), intent(inout) :: fa(*)
real(kind=dp), intent(inout) :: fb(*)
real(kind=dp), intent(inout) :: coeffa(*)
real(kind=dp), intent(inout) :: coeffb(*)
integer, intent(in) :: nbf
integer, intent(in) :: nbf_tri
real(kind=dp), intent(out) :: eexc
real(kind=dp), intent(out) :: totele
real(kind=dp), intent(out) :: totkin
type(information), intent(in) :: infos
Calls
Called by
Call graph
dftexcor calls dmatd_blk
dmatd_blk calls clean, init, run_xc
run_xc calls allreduce, compaos, compxc, getslicenonzero, getstats, init, pruneaos, resetpointers, parallel_start, parallel_stop, postUpdate, update
compute calls calc_evfxc, calc_evxc, calc_xc, scalexc
init calls clean, resetenergy
mo_tran_gemm_ calls oqp_dgemm_i64
mo_tran_symm_ calls oqp_dsymm_i64
oqp_dgemm_i64 calls show_message, dgemm
oqp_dsymm_i64 calls show_message, dsymm
scf_driver calls dftexcor
hf_energy calls scf_driver