dmatd_blk – OPENQP
dmatd_blk Subroutine
71 statements
Source File
public subroutine dmatd_blk(basis, molGrid, coeffa, coeffb, fa, fb, exc, totele, totkin, mxAngMom, nbf, dft_threshold, urohf, infos)
Uses
types
basis_tools
mod_dft_molgrid
mod_dft_gridint
@brief Compute grid XC contribution to the Kohn-Sham matrix @param[in] coeffa MO coefficients, alpha-spin @param[in] coeffb MO coefficients, beta-spin @param[inout] fa KS matrix, alpha-spin @param[inout] fb KS matrix, beta-spin @param[out] exc XC energy @param[out] totele electronic denisty integral @param[out] totkin kinetic energy integral @param[in] mxAngMom max. needed ang. mom. value (incl. derivatives) @param[in] nbf basis set size @param[in] urohf .TRUE. if open-shell calculation @author Vladimir Mironov
Arguments
Type Intent Optional Attributes Name
type(basis_set) :: basis
type(dft_grid_t), intent(in), target :: molGrid
real(kind=fp), intent(inout), target :: coeffa(nbf,*)
real(kind=fp), intent(inout), target :: coeffb(nbf,*)
real(kind=fp), intent(inout) :: fa(*)
real(kind=fp), intent(inout) :: fb(*)
real(kind=fp), intent(inout) :: exc
real(kind=fp), intent(inout) :: totele
real(kind=fp), intent(inout) :: totkin
integer, intent(in) :: mxAngMom
integer, intent(in) :: nbf
real(kind=fp), intent(in) :: dft_threshold
logical, intent(in) :: urohf
type(information), intent(in), target :: infos
Calls
Called by
Call graph
dmatd_blk calls clean, init, run_xc
run_xc calls allreduce, compaos, compxc, getslicenonzero, getstats, init, pruneaos, resetpointers, parallel_start, parallel_stop, postUpdate, update
compute calls calc_evfxc, calc_evxc, calc_xc, scalexc
init calls clean, resetenergy
mo_tran_gemm_ calls oqp_dgemm_i64
mo_tran_symm_ calls oqp_dsymm_i64
oqp_dgemm_i64 calls show_message, dgemm
oqp_dsymm_i64 calls show_message, dsymm
dftexcor calls dmatd_blk
scf_driver calls dftexcor
hf_energy calls scf_driver