doQuadGaussHermite – OPENQP
doQuadGaussHermite Subroutine
27 statements
Source File
public subroutine doQuadGaussHermite(tint, t, rij, ri, rj, ni, nj)
@brief Gauss-Hermite quadrature using minimum point formula @details Compute: xint = sum(w(1:npts,npts) * (h(1:npts,npts)t+dxi)(ni-1) * (h(1:npts,npts)t+dxj)(nj-1)) yint = sum(w(1:npts,npts) * (h(1:npts,npts)*t+dyi)(ni-1) * (h(1:npts,npts)t+dyj)(nj-1)) zint = sum(w(1:npts,npts) * (h(1:npts,npts)t+dzi)(ni-1) * (h(1:npts,npts)*t+dzj)(nj-1))
Note
Use of I functions will let NI run up to 7 (S=1, P=2, ..., I=7) Use of I functions will let NJ run up to 9 (for K.E. ints) Use of I functions requires NPTS=8 to do kinetic energy integrals. @param[out] xint x-component of the integral @param[out] yint y-component of the integral @param[out] zint z-component of the integral @param[out] t inverse square root of total exponent @param[out] x0 x-coord. of the center of primitive pair @param[out] y0 y-coord. of the center of primitive pair @param[out] z0 z-coord. of the center of primitive pair @param[out] xi x-coord. of the center of 1st primitive @param[out] yi y-coord. of the center of 1st primitive @param[out] zi z-coord. of the center of 1st primitive @param[out] xj x-coord. of the center of 2nd primitive @param[out] yj y-coord. of the center of 2nd primitive @param[out] zj z-coord. of the center of 2nd primitive @param[out] ni current angular momentum on center i @param[out] nj current angular momentum on center j
Note
based on STVINT from int1.src @author Vladimir Mironov @date Sep, 2018 Initial release
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(out) :: tint(3)
real(kind=dp), intent(in) :: t
real(kind=dp), intent(in) :: rij(3)
real(kind=dp), intent(in) :: ri(3)
real(kind=dp), intent(in) :: rj(3)
integer, intent(in) :: ni
integer, intent(in) :: nj
Calls
Called by
Call graph
doquadgausshermite calls abrt
comp_kin_ovl_int1_prim calls doquadgausshermite
comp_kinetic_der1 calls doquadgausshermite
comp_lz_int1_prim calls doquadgausshermite
comp_overlap_der1 calls doquadgausshermite
basis_overlap calls comp_kin_ovl_int1_prim
grad_ee_kinetic calls comp_kinetic_der1
grad_ee_overlap calls comp_overlap_der1
omp_hst calls comp_kin_ovl_int1_prim, comp_lz_int1_prim
overlap calls comp_kin_ovl_int1_prim
get_structures_ao_overlap calls basis_overlap
hf_gradient calls grad_ee_kinetic, grad_ee_overlap
huckel_guess calls basis_overlap, overlap
int1e calls omp_hst
tdhf_1e_grad calls grad_ee_kinetic, grad_ee_overlap
get_structures_ao_overlap_c calls get_structures_ao_overlap
guess_huckel calls huckel_guess
tdhf_gradient calls tdhf_1e_grad
guess_huckel_c calls guess_huckel
tdhf_gradient_c calls tdhf_gradient