electrostatic_potential – OPENQP
electrostatic_potential Subroutine
16 statements
Source File
public subroutine electrostatic_potential(basis, x, y, z, wt, d, pot, logtol)
Uses
precision
@brief Compute electronic contribution to electrostatic potential on a grid @author Vladimir Mironov @date Sep, 2023 Initial release
@param[in] basis basis w/ SP-shells separated @param[in] x array of X grid pts @param[in] y array of Y grid pts @param[in] z array of Z grid pts @param[in] wt array of grid weights @param[in] d density matrix @param[in] tol 1-e exponential prefactor tolerance @param[out] pot electrostatic potential on a grid
Arguments
Type Intent Optional Attributes Name
type(basis_set), intent(inout) :: basis
real(kind=real64), intent(in), contiguous :: x(:)
real(kind=real64), intent(in), contiguous :: y(:)
real(kind=real64), intent(in), contiguous :: z(:)
real(kind=real64), intent(in), contiguous :: wt(:)
real(kind=real64), intent(inout), contiguous :: d(:)
real(kind=real64), intent(out), contiguous :: pot(:)
real(kind=real64), intent(in), optional :: logtol
Calls
Called by
Call graph
electrostatic_potential calls bas_denorm_matrix, bas_norm_matrix, alloc, fetch_by_id, shell_pair, comp_coulpot_prim, density_ordered
comp_coulpot_prim calls evaluate
oqp_resp_charges calls electrostatic_potential
resp_charges_c calls oqp_resp_charges