fock_jk – OPENQP
fock_jk Subroutine
37 statements
Source File
public subroutine fock_jk(basis, d, f, scalefactor, infos)
Uses
int2_compute
precision
util
types
io_constants
basis_tools
Arguments
Type Intent Optional Attributes Name
type(basis_set), intent(in) :: basis
real(kind=dp), intent(in), target :: d(:,:)
real(kind=dp), intent(inout) :: f(:,:)
real(kind=dp), intent(in), optional :: scalefactor
type(information), intent(inout) :: infos
Calls
Source Code
  subroutine fock_jk(basis, d, f, scalefactor, infos)
   use precision, only: dp
   use io_constants, only: iw
   use util, only: measure_time
   use basis_tools, only: basis_set
   use types, only: information
   use int2_compute, only: int2_compute_t, int2_fock_data_t, int2_rhf_data_t, int2_urohf_data_t
   implicit none
   type(basis_set), intent(in) :: basis
   type(information), intent(inout) :: infos
   real(kind=dp), optional, intent(in) :: scalefactor
   integer :: i, ii, nf, nschwz
   real(kind=dp) :: scalef
   real(kind=dp), target, intent(in) :: d(:,:)
   real(kind=dp), intent(inout) :: f(:,:)
     type(int2_compute_t) :: int2_driver
     class(int2_fock_data_t), allocatable :: int2_data
!  Initial Settings
   scalef = 1.0d0
   if (present(scalefactor)) scalef = scalefactor
   call measure_time(print_total=1, log_unit=iw)
   write(iw,"(/3x,'Form Two-Electron J and K Fock')")
!  Initialize ERI calculations
   call int2_driver%init(basis, infos)
   call int2_driver%set_screening()
   int2_data = int2_rhf_data_t(nfocks=1, d=d, scale_exchange=scalefactor)
   call flush(iw)
!  Constructing two electron Fock matrix
   call int2_driver%run(int2_data)
   nschwz = int2_driver%skipped
!  Scaling (everything except diagonal is halved)
   f =  0.5 * int2_data%f(:,:,1)
   do nf = 1, ubound(f,2)
     ii = 0
     do i = 1, basis%nbf
        ii = ii + i
        f(ii,nf) = 2*f(ii,nf)
     end do
   end do
   call int2_driver%clean()
 end subroutine fock_jk
Call graph
fock_jk calls clean, init, run, set_screening, measure_time
ints_exchange calls show_message, alloc, compute, set, libint2_cleanup_eri, libint2_init_eri, clean, init, set_ids, genr22, int2_rys_compute, libint_compute_eri
libint_static_init calls libint2_static_init
genr22 calls fgrid, rfinc, rmr, xgrid
int2_rys_compute calls evaluate
libint_compute_eri calls ab_x, ab_y, ab_z, alpha1over_zetapluseta, alpha1rho_over_zeta2, alpha2over_zetapluseta, alpha2rho_over_zeta2, alpha3over_zetapluseta, alpha3rho_over_eta2, alpha4over_zetapluseta, alpha4rho_over_eta2, cd_x, cd_y, cd_z, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_0, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_1, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_10, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_11, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_12, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_13, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_14, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_15, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_16, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_17, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_18, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_19, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_2, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_20, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_3, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_4, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_5, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_6, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_7, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_8, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_9, fgrid, igrid, irgrd, oo2e, oo2z, oo2ze, pa_x, pa_y, pa_z, qc_x, qc_y, qc_z, rfinc, rho12_over_alpha1, rho12_over_alpha2, rho34_over_alpha3, rho34_over_alpha4, rmr, roe, roz, two_alpha0_bra, two_alpha0_ket, two_alpha1bra, two_alpha1ket, wp_x, wp_y, wp_z, wq_x, wq_y, wq_z