get_trans_den – OPENQP
get_trans_den Subroutine
44 statements
Source File
public subroutine get_trans_den(trden, xv12i, xv12j, noca, nocb, nvirb)
Uses
precision
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(out), dimension(:,:) :: trden
real(kind=dp), intent(in), dimension(:,:) :: xv12i
real(kind=dp), intent(in), dimension(:,:) :: xv12j
integer, intent(in) :: noca
integer, intent(in) :: nocb
integer, intent(in) :: nvirb
Called by
Call graph
get_mrsf_transition_density calls get_trans_den
tdhf_mrsf_energy calls get_mrsf_transition_density
tdhf_mrsf_energy_c calls tdhf_mrsf_energy