get_transition_dipole – OPENQP
get_transition_dipole Subroutine
37 statements
Source File
public subroutine get_transition_dipole(basis, dip, mo_a, trden, nstates)
Uses
messages
int1
precision
mathlib
basis_tools
Arguments
Type Intent Optional Attributes Name
type(basis_set), intent(in) :: basis
real(kind=dp), intent(out) :: dip(:,:,:)
real(kind=dp), intent(in) :: mo_a(:,:)
real(kind=dp), intent(in) :: trden(:,:,:,:)
integer, intent(in) :: nstates
Calls
Called by
Call graph
get_transition_dipole calls pack_matrix, show_message, atomic_structure_center, multipole_integrals, orthogonal_transform, symmetrize_matrix, traceprod_sym_packed
pack_matrix calls pack_f90
atomic_structure_center calls to_upper
multipole_integrals calls show_message, bas_norm_matrix, alloc, fetch_by_id, shell_pair, comp_allmult_int1_prim, print_sym_labeled, update_triang_matrix
orthogonal_transform calls show_message, oqp_dgemm_i64
comp_allmult_int1_prim calls mulquadgausshermite
oqp_dgemm_i64 calls show_message, dgemm
pack_f90 calls show_message, oqp_dtrttp_i64
print_sym_labeled calls bf_label
mulquadgausshermite calls abrt
oqp_dtrttp_i64 calls show_message, dtrttp
tdhf_mrsf_energy calls get_transition_dipole
tdhf_sf_energy calls get_transition_dipole
tdhf_mrsf_energy_c calls tdhf_mrsf_energy
tdhf_sf_energy_c calls tdhf_sf_energy