get_structures_ao_overlap_C – OPENQP
get_structures_ao_overlap_C Subroutine
8 statements
Source File
public subroutine get_structures_ao_overlap_C(c_handle) bind(C, name="get_structures_ao_overlap")
Uses
c_interop
types
@brief C-interoperable wrapper for get_states_overlap
@param[in] c_handle C handle for the information structure
Arguments
Type Intent Optional Attributes Name
type(oqp_handle_t) :: c_handle
Calls
Source Code
  subroutine get_structures_ao_overlap_C(c_handle) bind(C, name="get_structures_ao_overlap")
    use c_interop, only: oqp_handle_t, oqp_handle_get_info
    use types, only: information
    type(oqp_handle_t) :: c_handle
    type(information), pointer :: inf
    inf => oqp_handle_get_info(c_handle)
    call get_structures_ao_overlap(inf)
  end subroutine get_structures_ao_overlap_c
Call graph
get_structures_ao_overlap_c calls oqp_handle_get_info, get_structures_ao_overlap
get_structures_ao_overlap calls data_has_tags, tagarray_get_data, basis_overlap, measure_time, mo_overlap, print_geo, print_results, remove_records, reserve_data
basis_overlap calls alloc2, fetch_by_id, shell_pair2, comp_kin_ovl_int1_prim, update_rectangular_matrix
mo_overlap calls dgemm
comp_kin_ovl_int1_prim calls doquadgausshermite
doquadgausshermite calls abrt