get_td_transition_dipole – OPENQP
get_td_transition_dipole Subroutine
43 statements
Source File
public subroutine get_td_transition_dipole(basis, dip, v, vr, vl, nstates, nocc)
Uses
tdhf_lib
messages
int1
types
mathlib
basis_tools
Arguments
Type Intent Optional Attributes Name
type(basis_set), intent(in) :: basis
real(kind=8) :: dip(:,:)
real(kind=8) :: v(:,:)
real(kind=8) :: vr(:,:)
real(kind=8) :: vl(:,:)
integer :: nstates
integer :: nocc
Calls
Called by
Call graph
get_td_transition_dipole calls pack_matrix, show_message, atomic_structure_center, iatogen, multipole_integrals, orthogonal_transform, symmetrize_matrix, traceprod_sym_packed
pack_matrix calls pack_f90
atomic_structure_center calls to_upper
multipole_integrals calls show_message, bas_norm_matrix, alloc, fetch_by_id, shell_pair, comp_allmult_int1_prim, print_sym_labeled, update_triang_matrix
orthogonal_transform calls show_message, oqp_dgemm_i64
comp_allmult_int1_prim calls mulquadgausshermite
oqp_dgemm_i64 calls show_message, dgemm
pack_f90 calls show_message, oqp_dtrttp_i64
print_sym_labeled calls bf_label
mulquadgausshermite calls abrt
oqp_dtrttp_i64 calls show_message, dtrttp
tdhf_energy calls get_td_transition_dipole
tdhf_energy_c calls tdhf_energy