get_transitions – OPENQP
get_transitions Subroutine
14 statements
Source File
public subroutine get_transitions(trans, noca, nocb, nbf)
Arguments
Type Intent Optional Attributes Name
integer, intent(out), dimension(:,:) :: trans
integer, intent(in) :: noca
integer, intent(in) :: nocb
integer, intent(in) :: nbf
Called by
Source Code
  subroutine get_transitions(trans, noca, nocb, nbf)
    implicit none
    integer, intent(out), dimension(:,:) :: trans
    integer, intent(in) :: noca, nocb, nbf
    integer :: ij, i, j
    ij = 0
    do j = nocb+1, nbf
       do i = 1, noca
        ij = ij+1
        trans(ij,1) = i
        trans(ij,2) = j
      end do
    end do
  end subroutine get_transitions
Call graph
tdhf_mrsf_energy calls get_transitions
tdhf_sf_energy calls get_transitions
tdhf_mrsf_energy_c calls tdhf_mrsf_energy
tdhf_sf_energy_c calls tdhf_sf_energy