get_element_id – OPENQP
get_element_id Function
14 statements
Source File
public function get_element_id(element_name) result(id)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: element_name
Return Value integer
Calls
Called by
Call graph
get_element_id calls to_upper
guess_huckel calls from_file
guess_huckel_c calls guess_huckel