grad_en_hellman_feynman – OPENQP
grad_en_hellman_feynman Subroutine
54 statements
Source File
public subroutine grad_en_hellman_feynman(basis, coord, zq, denab, de, logtol)
@brief Hellmann-Feynman force @details Compute derivative contributions due to the Hamiltonian operator change w.r.t. shifts of nuclei. The contribution of the form is evaluated by Gauss-Rys quadrature. This version handles spdfg and L shells.
Note
No relativistic methods available @author Vladimir Mironov @date Sep, 2018 Initial release
@param[in,out] denab density matrix in packed format, remains unchanged on return
Arguments
Type Intent Optional Attributes Name
type(basis_set), intent(inout) :: basis
real(kind=dp), intent(in), contiguous :: coord(:,:)
real(kind=dp), intent(in), contiguous :: zq(:)
real(kind=dp), intent(inout) :: denab(:)
real(kind=dp) :: de(:,:)
real(kind=dp), optional :: logtol
Calls
Called by
Call graph
grad_en_hellman_feynman calls bas_norm_matrix, unpack_matrix, alloc, fetch_by_id, shell_pair, comp_coulomb_helfeyder1
unpack_matrix calls unpack_f90
comp_coulomb_helfeyder1 calls evaluate
unpack_f90 calls show_message, oqp_dtpttr_i64
oqp_dtpttr_i64 calls show_message, dtpttr
hf_gradient calls grad_en_hellman_feynman
tdhf_1e_grad calls grad_en_hellman_feynman
tdhf_gradient calls tdhf_1e_grad
tdhf_gradient_c calls tdhf_gradient