grad_ee_overlap – OPENQP
grad_ee_overlap Subroutine
41 statements
Source File
public subroutine grad_ee_overlap(basis, denab, de, logtol)
@brief Compute overlap energy derivative contribution to gradient @author Vladimir Mironov @date Sep, 2018 Initial release
@param[in,out] denab density matrix in packed format, remains unchanged on return
Arguments
Type Intent Optional Attributes Name
type(basis_set), intent(inout) :: basis
real(kind=dp), intent(inout) :: denab(:)
real(kind=dp) :: de(:,:)
real(kind=dp), optional :: logtol
Calls
Called by
Call graph
grad_ee_overlap calls bas_norm_matrix, unpack_matrix, alloc, fetch_by_id, shell_pair, comp_overlap_der1
unpack_matrix calls unpack_f90
comp_overlap_der1 calls doquadgausshermite
doquadgausshermite calls abrt
unpack_f90 calls show_message, oqp_dtpttr_i64
oqp_dtpttr_i64 calls show_message, dtpttr
hf_gradient calls grad_ee_overlap
tdhf_1e_grad calls grad_ee_overlap
tdhf_gradient calls tdhf_1e_grad
tdhf_gradient_c calls tdhf_gradient