grad_ee_kinetic – OPENQP
grad_ee_kinetic Subroutine
43 statements
Source File
public subroutine grad_ee_kinetic(basis, denab, de, logtol)
@brief Basis function derivative contributions to gradient @details Compute derivative integrals of type =
Note
No relativistic methods available @author Vladimir Mironov @date Sep, 2018 Initial release
@param[in,out] denab density matrix in packed format, remains unchanged on return
Arguments
Type Intent Optional Attributes Name
type(basis_set), intent(inout) :: basis
real(kind=dp), intent(inout) :: denab(:)
real(kind=dp) :: de(:,:)
real(kind=dp), optional :: logtol
Calls
Called by
Call graph
grad_ee_kinetic calls bas_norm_matrix, unpack_matrix, alloc, fetch_by_id, shell_pair, comp_kinetic_der1
unpack_matrix calls unpack_f90
comp_kinetic_der1 calls doquadgausshermite
doquadgausshermite calls abrt
unpack_f90 calls show_message, oqp_dtpttr_i64
oqp_dtpttr_i64 calls show_message, dtpttr
hf_gradient calls grad_ee_kinetic
tdhf_1e_grad calls grad_ee_kinetic
tdhf_gradient calls tdhf_1e_grad
tdhf_gradient_c calls tdhf_gradient