grad_en_pulay – OPENQP
grad_en_pulay Subroutine
57 statements
Source File
public subroutine grad_en_pulay(basis, coord, zq, denab, de, logtol)
@brief Basis function derivative contributions to gradient @details Compute derivative integrals of type =
Note
No relativistic methods available @author Vladimir Mironov @date Sep, 2018 Initial release
@param[in,out] denab density matrix in packed format, remains unchanged on return
Arguments
Type Intent Optional Attributes Name
type(basis_set), intent(inout) :: basis
real(kind=dp), intent(in), contiguous :: coord(:,:)
real(kind=dp), intent(in), contiguous :: zq(:)
real(kind=dp), intent(inout) :: denab(:)
real(kind=dp) :: de(:,:)
real(kind=dp), optional :: logtol
Calls
Called by
Call graph
grad_en_pulay calls bas_norm_matrix, unpack_matrix, alloc, fetch_by_id, shell_pair, comp_coulomb_der1
unpack_matrix calls unpack_f90
comp_coulomb_der1 calls evaluate
unpack_f90 calls show_message, oqp_dtpttr_i64
oqp_dtpttr_i64 calls show_message, dtpttr
hf_gradient calls grad_en_pulay
tdhf_1e_grad calls grad_en_pulay
tdhf_gradient calls tdhf_1e_grad
tdhf_gradient_c calls tdhf_gradient