grad_1e_ecp – OPENQP
grad_1e_ecp Subroutine
16 statements
Source File
public subroutine grad_1e_ecp(infos, basis, coord, denab, de, logtol)
Uses
types
parallel
@brief Effective core potential gradient
Arguments
Type Intent Optional Attributes Name
type(information), intent(inout), target :: infos
type(basis_set), intent(inout) :: basis
real(kind=dp), intent(in), contiguous :: coord(:,:)
real(kind=dp), intent(inout) :: denab(:)
real(kind=dp) :: de(:,:)
real(kind=dp), optional :: logtol
Calls
Called by
Source Code
  subroutine grad_1e_ecp(infos,basis, coord, denab, de, logtol)
    use types, only: information
    use parallel, only: par_env_t
    type(information), target, intent(inout) :: infos
    type(par_env_t) :: pe
    REAL(kind=dp), INTENT(INOUT) :: denab(:)
    type(basis_set), intent(inout) :: basis
    real(kind=dp), contiguous, intent(in) :: coord(:,:)
    REAL(kind=dp) :: de(:,:)
    REAL(kind=dp), optional :: logtol
    call pe%init(infos%mpiinfo%comm, infos%mpiinfo%usempi)
    if (pe%rank == 0) then
        call add_ecpder(basis, coord, denab, de)
    end if
    call pe%bcast(de, size(de))
  end subroutine grad_1e_ecp
Call graph
grad_1e_ecp calls bcast, init, add_ecpder
add_ecpder calls compute_first_derivs, free_integrator, free_result, init_integrator, init_integrator_instance, set_ecp_basis, bf_to_shell
hf_gradient calls grad_1e_ecp
tdhf_1e_grad calls grad_1e_ecp
tdhf_gradient calls tdhf_1e_grad
tdhf_gradient_c calls tdhf_gradient