grd2_driver – OPENQP
grd2_driver Subroutine
42 statements
Source File
public subroutine grd2_driver(infos, basis, de, gcomp, cam, alpha, beta, mu)
Uses
types
basis_tools
@brief The driver for the two electron gradient
Arguments
Type Intent Optional Attributes Name
type(information), intent(inout), target :: infos
type(basis_set), intent(in) :: basis
real(kind=dp), intent(inout) :: de(:,:)
class(grd2_compute_data_t), intent(inout) :: gcomp
logical, intent(in), optional :: cam
real(kind=dp), intent(in), optional :: alpha
real(kind=dp), intent(in), optional :: beta
real(kind=dp), intent(in), optional :: mu
Calls
Called by
Call graph
grd2_driver calls get_density, show_message, alloc, allreduce, clean, compute, init, set, set_ids, grd2_rys_compute, ints_exchange
grd2_rys_compute calls evaluate
ints_exchange calls show_message, alloc, compute, set, libint2_cleanup_eri, libint2_init_eri, clean, init, set_ids, genr22, int2_rys_compute, libint_compute_eri
genr22 calls fgrid, rfinc, rmr, xgrid
int2_rys_compute calls evaluate
libint_compute_eri calls ab_x, ab_y, ab_z, alpha1over_zetapluseta, alpha1rho_over_zeta2, alpha2over_zetapluseta, alpha2rho_over_zeta2, alpha3over_zetapluseta, alpha3rho_over_eta2, alpha4over_zetapluseta, alpha4rho_over_eta2, cd_x, cd_y, cd_z, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_0, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_1, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_10, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_11, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_12, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_13, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_14, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_15, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_16, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_17, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_18, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_19, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_2, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_20, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_3, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_4, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_5, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_6, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_7, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_8, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_9, fgrid, igrid, irgrd, oo2e, oo2z, oo2ze, pa_x, pa_y, pa_z, qc_x, qc_y, qc_z, rfinc, rho12_over_alpha1, rho12_over_alpha2, rho34_over_alpha3, rho34_over_alpha4, rmr, roe, roz, two_alpha0_bra, two_alpha0_ket, two_alpha1bra, two_alpha1ket, wp_x, wp_y, wp_z, wq_x, wq_y, wq_z
hf_gradient calls grd2_driver
tdhf_2e_grad calls grd2_driver
tdhf_gradient calls tdhf_2e_grad
tdhf_gradient_c calls tdhf_gradient