guess_hcore_C – OPENQP
guess_hcore_C Subroutine
8 statements
Source File
public subroutine guess_hcore_C(c_handle) bind(C, name="guess_hcore")
Uses
c_interop
types
Arguments
Type Intent Optional Attributes Name
type(oqp_handle_t) :: c_handle
Calls
Source Code
  subroutine guess_hcore_C(c_handle) bind(C, name="guess_hcore")
    use c_interop, only: oqp_handle_t, oqp_handle_get_info
    use types, only: information
    type(oqp_handle_t) :: c_handle
    type(information), pointer :: inf
    inf => oqp_handle_get_info(c_handle)
    call guess_hcore(inf)
  end subroutine guess_hcore_C
Call graph
guess_hcore_c calls oqp_handle_get_info, guess_hcore
guess_hcore calls data_has_tags, show_message, tagarray_get_data, get_ab_initio_density, get_ab_initio_orbital, matrix_invsqrt, measure_time, print_module_info, remove_records, reserve_data
get_ab_initio_density calls show_message, orb_to_dens
get_ab_initio_orbital calls show_message, unpack_matrix, diag_symm_full, oqp_dgemm_i64, orthogonal_transform
matrix_invsqrt calls show_message, diag_symm_packed
unpack_matrix calls unpack_f90
diag_symm_full calls show_message, dsyev
diag_symm_packed calls show_message, dspev, dspevx
oqp_dgemm_i64 calls show_message, dgemm
orb_to_dens calls pack_matrix, oqp_dsyr2k_i64
orthogonal_transform calls show_message, oqp_dgemm_i64
pack_matrix calls pack_f90
oqp_dsyr2k_i64 calls show_message, dsyr2k
unpack_f90 calls show_message, oqp_dtpttr_i64
oqp_dtpttr_i64 calls show_message, dtpttr
pack_f90 calls show_message, oqp_dtrttp_i64
oqp_dtrttp_i64 calls show_message, dtrttp