guess_json_C – OPENQP
guess_json_C Subroutine
8 statements
Source File
public subroutine guess_json_C(c_handle) bind(C, name="guess_json")
Uses
c_interop
types
Arguments
Type Intent Optional Attributes Name
type(oqp_handle_t) :: c_handle
Calls
Source Code
  subroutine guess_json_C(c_handle) bind(C, name="guess_json")
    use c_interop, only: oqp_handle_t, oqp_handle_get_info
    use types, only: information
    type(oqp_handle_t) :: c_handle
    type(information), pointer :: inf
    inf => oqp_handle_get_info(c_handle)
    call guess_json(inf)
  end subroutine guess_json_C
Call graph
guess_json_c calls oqp_handle_get_info, guess_json
guess_json calls data_has_tags, tagarray_get_data, barrier, bcast, init, get_ab_initio_density, measure_time, print_module_info, reserve_data
get_ab_initio_density calls show_message, orb_to_dens
orb_to_dens calls pack_matrix, oqp_dsyr2k_i64
pack_matrix calls pack_f90
oqp_dsyr2k_i64 calls show_message, dsyr2k
pack_f90 calls show_message, oqp_dtrttp_i64
oqp_dtrttp_i64 calls show_message, dtrttp