guess_huckel_C – OPENQP
guess_huckel_C Subroutine
8 statements
Source File
public subroutine guess_huckel_C(c_handle) bind(C, name="guess_huckel")
Uses
c_interop
types
Arguments
Type Intent Optional Attributes Name
type(oqp_handle_t) :: c_handle
Calls
Source Code
  subroutine guess_huckel_C(c_handle) bind(C, name="guess_huckel")
    use c_interop, only: oqp_handle_t, oqp_handle_get_info
    use types, only: information
    type(oqp_handle_t) :: c_handle
    type(information), pointer :: inf
    inf => oqp_handle_get_info(c_handle)
    call guess_huckel(inf)
  end subroutine guess_huckel_C
Call graph
guess_huckel_c calls oqp_handle_get_info, guess_huckel
guess_huckel calls data_has_tags, tagarray_get_data, barrier, bcast, from_file, init, get_ab_initio_density, huckel_guess, measure_time, print_module_info, remove_records, reserve_data
get_ab_initio_density calls show_message, orb_to_dens
huckel_guess calls show_message, unpack_matrix, basis_overlap, corresponding_orbital_projection, diag_symm_full, matrix_invsqrt, mksphar, oqp_dgemm_i64, oqp_dgeqrf_i64, oqp_dormqr_i64, oqp_dsymm_i64, orthogonal_transform_sym, overlap
unpack_matrix calls unpack_f90
basis_overlap calls alloc2, fetch_by_id, shell_pair2, comp_kin_ovl_int1_prim, update_rectangular_matrix
corresponding_orbital_projection calls show_message, diag_symm_full, oqp_dgemm_i64, oqp_dswap_i64, oqp_dsyrk_i64, schmd
diag_symm_full calls show_message, dsyev
matrix_invsqrt calls show_message, diag_symm_packed
mksphar calls show_message
oqp_dgemm_i64 calls show_message, dgemm
oqp_dgeqrf_i64 calls show_message, dgeqrf
oqp_dormqr_i64 calls show_message, dormqr
oqp_dsymm_i64 calls show_message, dsymm
orb_to_dens calls pack_matrix, oqp_dsyr2k_i64
orthogonal_transform_sym calls show_message, oqp_dgemm_i64, oqp_dsymm_i64, oqp_dtpttr_i64, oqp_dtrttp_i64
overlap calls alloc, fetch_by_id, shell_pair, comp_kin_ovl_int1_prim, update_triang_matrix
pack_matrix calls pack_f90
comp_kin_ovl_int1_prim calls doquadgausshermite
diag_symm_packed calls show_message, dspev, dspevx
get_element_id calls to_upper
oqp_dswap_i64 calls show_message, dswap
oqp_dsyr2k_i64 calls show_message, dsyr2k
oqp_dsyrk_i64 calls show_message, dsyrk
oqp_dtpttr_i64 calls show_message, dtpttr
oqp_dtrttp_i64 calls show_message, dtrttp
schmd calls show_message, oqp_dgeqrf_i64, oqp_dorgqr_i64
unpack_f90 calls show_message, oqp_dtpttr_i64
doquadgausshermite calls abrt
oqp_dorgqr_i64 calls show_message, dorgqr
pack_f90 calls show_message, oqp_dtrttp_i64