hf_energy – OPENQP
hf_energy Subroutine
39 statements
Source File
public subroutine hf_energy(infos)
Uses
dft
scf
printing
messages
oqp_tagarray_driver
types
io_constants
basis_tools
mod_dft_molgrid
strings
Arguments
Type Intent Optional Attributes Name
type(information), intent(inout), target :: infos
Calls
Source Code
  subroutine hf_energy(infos)
    use io_constants, only: iw
    use basis_tools, only: basis_set
    use messages, only: show_message
    use scf, only: scf_driver
    use dft, only: dft_initialize, dftclean
    use types, only: information
    use oqp_tagarray_driver
    use strings, only: Cstring, fstring
    use mod_dft_molgrid, only: dft_grid_t
    use printing, only: print_module_info
    implicit none
    character(len=*), parameter :: subroutine_name = "hf_energy_mod"
    type(information), target, intent(inout) :: infos
    integer :: nbf2, nbf, nsh2
    logical :: urohf, dft
    type(basis_set), pointer :: basis
    type(dft_grid_t) :: molGrid
    urohf = infos%control%scftype == 2 .or. infos%control%scftype == 3
    dft = infos%control%hamilton == 20
!   3. LOG: Write: Main output file
    open (unit=iw, file=infos%log_filename, position="append")
!
    call print_module_info('HF_DFT_Energy','Computing HF/DFT SCF Energy')
!   Load basis set
    basis => infos%basis
    basis%atoms => infos%atoms
!   Allocate memory
    nbf = basis%nbf
    nbf2 = nbf*(nbf+1)/2
    nsh2 = (basis%nshell**2+basis%nshell)/2
    ! clean data
    call infos%dat%remove_records((/ character(len=80) :: OQP_FOCK_A, OQP_FOCK_B /))
    call infos%dat%reserve_data(OQP_FOCK_A, TA_TYPE_REAL64, nbf2, comment=OQP_FOCK_A_comment)
    call check_status(infos%dat%get_status(), module_name, subroutine_name, OQP_FOCK_A)
    if (urohf) then
      call infos%dat%reserve_data(OQP_FOCK_B, TA_TYPE_REAL64, nbf2, comment=OQP_FOCK_B_comment)
      call check_status(infos%dat%get_status(), module_name, subroutine_name, OQP_FOCK_B)
    end if
!   Prepare dft grid
    if (dft) call dft_initialize(infos, basis, molGrid, verbose=.true.)
!   Run HF/DFT calculation
    call scf_driver(basis, infos, molGrid)
!   Cleanup
    if (dft) call dftclean(infos)
    close(iw)
  end subroutine hf_energy
Call graph
hf_energy calls get_status, check_status, dft_initialize, dftclean, print_module_info, scf_driver, remove_records, reserve_data
check_status calls get_status_message, show_message
dft_initialize calls show_message, add_atomic_grid, add_grid, compress, find_neighbours, reset, set_screening, c_f_char, dft_fc_blk, get_radial_grid, libxc_input, set_bragg_slater
dftclean calls libxc_destroy
scf_driver calls data_has_tags, show_message, tagarray_get_data, unpack_matrix, add_data, bcast, clean, get_fock, init, run, set_screening, build_pfon_density, dftexcor, e_charge_repulsion, form_rohf_fock, get_ab_initio_density, get_ab_initio_orbital, matrix_invsqrt, measure_time, mo_reorder, mo_to_ao, pfon_occupations, print_mo_range, print_scf_energy, traceprod_sym_packed
unpack_matrix calls unpack_f90
build_pfon_density calls pack_matrix
dft_fc_blk calls getbyid, set
dftexcor calls dmatd_blk
form_rohf_fock calls unpack_matrix, dsymm, pack_matrix, orthogonal_transform2, orthogonal_transform_sym, triangular_to_full
get_ab_initio_density calls show_message, orb_to_dens
get_ab_initio_orbital calls show_message, unpack_matrix, diag_symm_full, oqp_dgemm_i64, orthogonal_transform
get_radial_grid calls set, transform
libxc_destroy calls destroy
libxc_input calls show_message, add_functional, can_calculate, xc_f03_reference, xc_f03_reference_doi, xc_f03_version_string
matrix_invsqrt calls show_message, diag_symm_packed
mo_reorder calls dgemm, reordermos
mo_to_ao calls unpack_matrix, pack_matrix, oqp_dgemm_i64, oqp_dsymm_i64
print_mo_range calls print_eigvec_vals_labeled
pack_matrix calls pack_f90
diag_symm_full calls show_message, dsyev
diag_symm_packed calls show_message, dspev, dspevx
dmatd_blk calls init, clean, run_xc
ints_exchange calls show_message, alloc, compute, set, libint2_cleanup_eri, libint2_init_eri, clean, init, set_ids, genr22, int2_rys_compute, libint_compute_eri
lebedev_get_grid calls show_message
libint_static_init calls libint2_static_init
oqp_dgemm_i64 calls show_message, dgemm
oqp_dsymm_i64 calls show_message, dsymm
orb_to_dens calls pack_matrix, oqp_dsyr2k_i64
orthogonal_transform calls show_message, oqp_dgemm_i64
orthogonal_transform2 calls show_message, oqp_dgemm_i64
orthogonal_transform_sym calls show_message, oqp_dgemm_i64, oqp_dsymm_i64, oqp_dtpttr_i64, oqp_dtrttp_i64
print_eigvec_vals_labeled calls data_has_tags, tagarray_get_data, bf_label
reordermos calls dswap
triangular_to_full calls show_message
unpack_f90 calls show_message, oqp_dtpttr_i64
genr22 calls fgrid, rfinc, rmr, xgrid
int2_rys_compute calls evaluate
libint_compute_eri calls ab_x, ab_y, ab_z, alpha1over_zetapluseta, alpha1rho_over_zeta2, alpha2over_zetapluseta, alpha2rho_over_zeta2, alpha3over_zetapluseta, alpha3rho_over_eta2, alpha4over_zetapluseta, alpha4rho_over_eta2, cd_x, cd_y, cd_z, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_0, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_1, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_10, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_11, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_12, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_13, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_14, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_15, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_16, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_17, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_18, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_19, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_2, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_20, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_3, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_4, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_5, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_6, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_7, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_8, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_9, fgrid, igrid, irgrd, oo2e, oo2z, oo2ze, pa_x, pa_y, pa_z, qc_x, qc_y, qc_z, rfinc, rho12_over_alpha1, rho12_over_alpha2, rho34_over_alpha3, rho34_over_alpha4, rmr, roe, roz, two_alpha0_bra, two_alpha0_ket, two_alpha1bra, two_alpha1ket, wp_x, wp_y, wp_z, wq_x, wq_y, wq_z
oqp_dsyr2k_i64 calls show_message, dsyr2k
oqp_dtpttr_i64 calls show_message, dtpttr
oqp_dtrttp_i64 calls show_message, dtrttp
pack_f90 calls show_message, oqp_dtrttp_i64
run_xc calls parallel_start, parallel_stop, update, allreduce, compaos, compxc, getslicenonzero, getstats, init, pruneaos, resetpointers, postUpdate
compute calls calc_evfxc, calc_evxc, calc_xc, scalexc
init calls clean, resetenergy
mo_tran_gemm_ calls oqp_dgemm_i64
mo_tran_symm_ calls oqp_dsymm_i64