hf_gradient – OPENQP
hf_gradient Subroutine
46 statements
Source File
public subroutine hf_gradient(infos)
Uses
dft
printing
util
io_constants
mod_dft_molgrid
strings
grd1
Arguments
Type Intent Optional Attributes Name
type(information), intent(inout), target :: infos
Calls
Source Code
  subroutine hf_gradient(infos)
    use io_constants, only: iw
    use grd1, only: print_gradient
    use dft, only: dft_initialize, dftclean, dftder
    use strings, only: Cstring, fstring
    use mod_dft_molgrid, only: dft_grid_t
    use util, only: measure_time
    use printing, only: print_module_info
    implicit none
    type(information), target, intent(inout) :: infos
    integer :: b_size, c_size, s_size
    type(basis_Set), pointer :: basis
    logical :: urohf, dft
    type(dft_grid_t) :: molGrid
!   3. LOG: Write: Main output file
    open (unit=IW, file=infos%log_filename, position="append")
!
    call print_module_info('HF_DFT_Gradient','Computing Gradient of HF/DFT')
    urohf = infos%control%scftype == 2 .or. infos%control%scftype == 3
    dft = infos%control%hamilton == 20
!   Load basis set
    basis => infos%basis
    basis%atoms => infos%atoms
!   Allocate memory
    b_size = basis%nbf*(basis%nbf+1)/2
    c_size = basis%nbf
    s_size = (basis%nshell**2+basis%nshell)/2
!   Compute 1e gradient
    write(iw,"(/' ..... Beginning Gradient Calculation...'/)")
    call flush(iw)
    call hf_1e_grad(infos, basis)
    write(iw,"(' ..... End Of 1-Eelectron Gradient ......')")
    call measure_time(print_total=1, log_unit=iw)
    call flush(iw)
!   Calculate DFT contribution
    if (dft) then
      write(iw,"(/' ..... Gradient XC terms...'/)")
      call dft_initialize(infos, basis, molGrid, verbose=.true.)
      call dftder(basis, infos, molGrid)
      call dftclean(infos)
      write(iw,"(' ..... End of gradient XC terms......')")
      call measure_time(print_total=1, log_unit=iw)
      call flush(iw)
    end if
!   Compute 2e gradient
    call hf_2e_grad(basis, infos)
    write(iw, fmt="(' ...... End Of 2-Electron Gradient ......')")
    call measure_time(print_total=1, log_unit=iw)
    call flush(iw)
!   Print out gradient
    call print_gradient(infos)
!   Print timings
    call measure_time(print_total=1, log_unit=iw)
    close(iw)
  end subroutine hf_gradient
Call graph
hf_gradient calls clean, init, show_message, tagarray_get_data, check_status, dft_initialize, dftclean, dftder, eijden, grad_1e_ecp, grad_ee_kinetic, grad_ee_overlap, grad_en_hellman_feynman, grad_en_pulay, grad_nn, grd2_driver, measure_time, print_gradient, print_module_info
check_status calls show_message, get_status_message
dft_initialize calls show_message, add_atomic_grid, add_grid, compress, find_neighbours, reset, set_screening, c_f_char, dft_fc_blk, get_radial_grid, libxc_input, set_bragg_slater
dftclean calls libxc_destroy
dftder calls show_message, tagarray_get_data, check_status, unpack_matrix, derexc_blk
eijden calls tagarray_get_data, data_has_tags, unpack_matrix, orthogonal_transform_sym
grad_1e_ecp calls bcast, init, add_ecpder
grad_ee_kinetic calls bas_norm_matrix, unpack_matrix, alloc, fetch_by_id, shell_pair, comp_kinetic_der1
grad_ee_overlap calls bas_norm_matrix, unpack_matrix, alloc, fetch_by_id, shell_pair, comp_overlap_der1
grad_en_hellman_feynman calls bas_norm_matrix, unpack_matrix, alloc, fetch_by_id, shell_pair, comp_coulomb_helfeyder1
grad_en_pulay calls bas_norm_matrix, unpack_matrix, alloc, fetch_by_id, shell_pair, comp_coulomb_der1
grd2_driver calls show_message, get_density, alloc, allreduce, clean, compute, init, set, set_ids, grd2_rys_compute, ints_exchange
unpack_matrix calls unpack_f90
add_ecpder calls compute_first_derivs, free_integrator, free_result, init_integrator, init_integrator_instance, set_ecp_basis, bf_to_shell
comp_coulomb_der1 calls evaluate
comp_coulomb_helfeyder1 calls evaluate
comp_kinetic_der1 calls doquadgausshermite
comp_overlap_der1 calls doquadgausshermite
derexc_blk calls init, clean, run_xc
dft_fc_blk calls getbyid, set
get_radial_grid calls set, transform
grd2_rys_compute calls evaluate
ints_exchange calls show_message, alloc, compute, set, libint2_cleanup_eri, libint2_init_eri, clean, init, set_ids, genr22, int2_rys_compute, libint_compute_eri
libxc_destroy calls destroy
libxc_input calls show_message, add_functional, can_calculate, xc_f03_reference, xc_f03_reference_doi, xc_f03_version_string
orthogonal_transform_sym calls show_message, oqp_dgemm_i64, oqp_dsymm_i64, oqp_dtpttr_i64, oqp_dtrttp_i64
doquadgausshermite calls abrt
genr22 calls fgrid, rfinc, rmr, xgrid
int2_rys_compute calls evaluate
lebedev_get_grid calls show_message
libint_compute_eri calls ab_x, ab_y, ab_z, alpha1over_zetapluseta, alpha1rho_over_zeta2, alpha2over_zetapluseta, alpha2rho_over_zeta2, alpha3over_zetapluseta, alpha3rho_over_eta2, alpha4over_zetapluseta, alpha4rho_over_eta2, cd_x, cd_y, cd_z, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_0, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_1, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_10, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_11, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_12, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_13, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_14, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_15, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_16, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_17, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_18, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_19, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_2, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_20, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_3, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_4, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_5, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_6, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_7, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_8, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_9, fgrid, igrid, irgrd, oo2e, oo2z, oo2ze, pa_x, pa_y, pa_z, qc_x, qc_y, qc_z, rfinc, rho12_over_alpha1, rho12_over_alpha2, rho34_over_alpha3, rho34_over_alpha4, rmr, roe, roz, two_alpha0_bra, two_alpha0_ket, two_alpha1bra, two_alpha1ket, wp_x, wp_y, wp_z, wq_x, wq_y, wq_z
oqp_dgemm_i64 calls show_message, dgemm
oqp_dsymm_i64 calls show_message, dsymm
oqp_dtpttr_i64 calls show_message, dtpttr
oqp_dtrttp_i64 calls show_message, dtrttp
run_xc calls allreduce, compaos, compxc, getslicenonzero, getstats, init, pruneaos, resetpointers, parallel_start, parallel_stop, postUpdate, update
unpack_f90 calls show_message, oqp_dtpttr_i64
compute calls calc_evfxc, calc_evxc, calc_xc, scalexc
init calls clean, resetenergy
mo_tran_gemm_ calls oqp_dgemm_i64
mo_tran_symm_ calls oqp_dsymm_i64