huckel_guess – OPENQP
huckel_guess Subroutine
42 statements
Source File
public subroutine huckel_guess(ovl, orbitals, infos, basis, huckel_basis)
Uses
messages
int1
guess
types
constants
mathlib
basis_tools
Arguments
Type Intent Optional Attributes Name
real(kind=dp) :: ovl(*)
real(kind=dp) :: orbitals(*)
type(information), intent(in) :: infos
type(basis_set), intent(in) :: basis
type(basis_set), intent(in) :: huckel_basis
Calls
Called by
Source Code
 subroutine huckel_guess(ovl, orbitals, infos, basis, huckel_basis)
   use constants, only: tol_int
   use types,     only: information
   use messages,  only: show_message, WITH_ABORT
   use mathlib, only: matrix_invsqrt
   use basis_tools, only: basis_set
   use int1, only: basis_overlap
   use guess, only: corresponding_orbital_projection
   implicit none
   type(information), intent(in) :: infos
   type(basis_set), intent(in) :: basis, huckel_basis
   real(kind=dp) :: ovl(*), orbitals(*)
   integer :: nat, i, ok, l0, l0co, nbf, nbf2, nbf_co, nact, ndoc, nproj
   real(kind=dp), allocatable :: scr(:)
   real(kind=dp), allocatable :: q(:)
   real(kind=dp), allocatable :: vec(:,:)
   real(kind=dp), allocatable :: sco(:,:)
   nbf = basis%nbf
   nbf2 = nbf*(nbf+1)/2
   nat = infos%mol_prop%natom
!  Number of orbitals in MINI basis used in Huckel
   nbf_co = huckel_basis%nbf
   allocate(scr(nbf), &
            q(nbf*nbf), &
            vec(nbf_co,nbf_co),     &
            sco(nbf_co,nbf),     &
            stat=ok)
   if (ok/=0) call show_message('Cannot allocate memory', WITH_ABORT)
!  Get overlap between the minimal basis set and the input basis
   call basis_overlap(sco, basis, huckel_basis, tol=log(10.0d0)*tol_int)
   do i = 1, nbf
     sco(:,i) = sco(:,i)*basis%bfnrm(i) * huckel_basis%bfnrm
   end do
!  Determine which orbitals should be projected
   if (infos%control%scftype == 1) then
     ndoc = infos%mol_prop%nelec/2
     nact = 0
   else if (infos%control%scftype >= 2) then
     ndoc = infos%mol_prop%nelec_b
     nact = infos%mol_prop%nelec_a-infos%mol_prop%nelec_b
   end if
!  Extended Huckel calculation in mini basis set
   call huckel_calc(huckel_basis, vec, l0co, nat, infos%atoms%zn, tol_int)
!  Do at most 5 virtuals from the huckel
   nproj = min(l0co,ndoc+nact+5)
!  Get canonical orbitals in input basis space
   call matrix_invsqrt(ovl, q, nbf, qrnk=l0)
   orbitals(1:nbf*nbf) = q(1:nbf*nbf)
!  Project minimal basis set guess onto the input canonical orbitals,
   call corresponding_orbital_projection(vec, sco, orbitals, ndoc, nact, nproj, nbf, nbf_co, l0)
   deallocate(vec, sco)
   call orthogonalize_orbitals(q, ovl, orbitals, nproj, l0, nbf, nbf)
 end subroutine huckel_guess
Call graph
huckel_guess calls show_message, unpack_matrix, basis_overlap, corresponding_orbital_projection, diag_symm_full, matrix_invsqrt, mksphar, oqp_dgemm_i64, oqp_dgeqrf_i64, oqp_dormqr_i64, oqp_dsymm_i64, orthogonal_transform_sym, overlap
unpack_matrix calls unpack_f90
basis_overlap calls alloc2, fetch_by_id, shell_pair2, comp_kin_ovl_int1_prim, update_rectangular_matrix
corresponding_orbital_projection calls show_message, diag_symm_full, oqp_dgemm_i64, oqp_dswap_i64, oqp_dsyrk_i64, schmd
diag_symm_full calls show_message, dsyev
matrix_invsqrt calls show_message, diag_symm_packed
mksphar calls show_message
oqp_dgemm_i64 calls show_message, dgemm
oqp_dgeqrf_i64 calls show_message, dgeqrf
oqp_dormqr_i64 calls show_message, dormqr
oqp_dsymm_i64 calls show_message, dsymm
orthogonal_transform_sym calls show_message, oqp_dgemm_i64, oqp_dsymm_i64, oqp_dtpttr_i64, oqp_dtrttp_i64
overlap calls alloc, fetch_by_id, shell_pair, comp_kin_ovl_int1_prim, update_triang_matrix
comp_kin_ovl_int1_prim calls doquadgausshermite
diag_symm_packed calls show_message, dspev, dspevx
oqp_dswap_i64 calls show_message, dswap
oqp_dsyrk_i64 calls show_message, dsyrk
oqp_dtpttr_i64 calls show_message, dtpttr
oqp_dtrttp_i64 calls show_message, dtrttp
schmd calls show_message, oqp_dgeqrf_i64, oqp_dorgqr_i64
unpack_f90 calls show_message, oqp_dtpttr_i64
doquadgausshermite calls abrt
oqp_dorgqr_i64 calls show_message, dorgqr
guess_huckel calls huckel_guess
guess_huckel_c calls guess_huckel