iatogen – OPENQP
iatogen Subroutine
13 statements
Source File
public subroutine iatogen(pv, av, nocca, noccb)
Uses
precision
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in), contiguous, target :: pv(:)
real(kind=dp), intent(out) :: av(:,:)
integer, intent(in) :: nocca
integer, intent(in) :: noccb
Called by
Source Code
  subroutine iatogen(pv,av,nocca,noccb)
    use precision, only: dp
    implicit none
    real(kind=dp), intent(in), contiguous, target :: pv(:)
    real(kind=dp), intent(out) :: av(:,:)
    integer, intent(in) :: nocca, noccb
    real(kind=dp), pointer :: ppv(:,:)
    integer :: nbf
    nbf = ubound(av, 1)
    ppv(1:nocca, noccb+1:nbf) => pv(:)
    av = 0.0_dp
    av(1:nocca, noccb+1:nbf) = ppv(1:nocca, noccb+1:nbf)
  end subroutine iatogen
Call graph
get_td_transition_dipole calls iatogen
get_transition_density calls iatogen
oqp_tdhf_z_vector calls iatogen
sfdmat calls iatogen
tdhf_energy calls iatogen, get_td_transition_dipole
tdhf_gradient calls iatogen
tdhf_mrsf_energy calls iatogen, get_transition_density
tdhf_sf_energy calls iatogen, get_transition_density, sfdmat
tdhf_energy_c calls tdhf_energy
tdhf_gradient_c calls tdhf_gradient
tdhf_mrsf_energy_c calls tdhf_mrsf_energy
tdhf_sf_energy_c calls tdhf_sf_energy
tdhf_z_vector_c calls oqp_tdhf_z_vector