int2_rpagrd_data_t_parallel_stop – OPENQP
int2_rpagrd_data_t_parallel_stop Subroutine
23 statements
Source File
public subroutine int2_rpagrd_data_t_parallel_stop(this)
Type Bound
int2_rpagrd_data_t
Arguments
Type Intent Optional Attributes Name
class(int2_rpagrd_data_t), intent(inout) :: this
Calls
Call graph
int2_rpagrd_data_t_parallel_stop calls allreduce, symmetrize_matrices
symmetrize_matrices calls symmetrize_matrix