lebedev_get_grid – OPENQP
lebedev_get_grid Subroutine
131 statements
Source File
public subroutine lebedev_get_grid(npts, xyz, w, grid_type)
Uses
messages
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: npts
real(kind=dp), intent(inout) :: xyz(npts,*)
real(kind=dp), intent(inout) :: w(*)
integer, intent(in), optional :: grid_type
Calls
Called by
Call graph
lebedev_get_grid calls show_message
oqp_resp_charges calls lebedev_get_grid
dft_initialize calls add_grid
resp_charges_c calls oqp_resp_charges
hf_energy calls dft_initialize
hf_gradient calls dft_initialize
oqp_tdhf_z_vector calls dft_initialize
tdhf_energy calls dft_initialize
tdhf_gradient calls dft_initialize
tdhf_energy_c calls tdhf_energy
tdhf_gradient_c calls tdhf_gradient
tdhf_z_vector_c calls oqp_tdhf_z_vector