libint_static_init – OPENQP
libint_static_init Subroutine
3 statements
Source File
public subroutine libint_static_init()
Arguments
None
Calls
Called by
Call graph
libint_static_init calls libint2_static_init
fock_jk calls init
oqp_tdhf_z_vector calls init
scf_driver calls init
tdhf_energy calls init
tdhf_mrsf_energy calls init
tdhf_sf_energy calls init
hf_energy calls scf_driver
tdhf_energy_c calls tdhf_energy
tdhf_mrsf_energy_c calls tdhf_mrsf_energy
tdhf_sf_energy_c calls tdhf_sf_energy
tdhf_z_vector_c calls oqp_tdhf_z_vector