libint_compute_eri – OPENQP
libint_compute_eri Subroutine
157 statements
Source File
public subroutine libint_compute_eri(basis, ppairs, cutoffs, shell_ids, deriv_order, erieval, flips, zero_shq)
Uses
boys_lut
basis_tools
Arguments
Type Intent Optional Attributes Name
type(basis_set), intent(in) :: basis
type(int2_pair_storage), intent(in) :: ppairs
type(int2_cutoffs_t), intent(in) :: cutoffs
integer, intent(in) :: shell_ids(4)
integer, intent(in) :: deriv_order
type(libint_t), intent(out) :: erieval(*)
integer, intent(out) :: flips(4)
logical, intent(out) :: zero_shq
Calls
Called by
Call graph
libint_compute_eri calls ab_x, ab_y, ab_z, alpha1over_zetapluseta, alpha1rho_over_zeta2, alpha2over_zetapluseta, alpha2rho_over_zeta2, alpha3over_zetapluseta, alpha3rho_over_eta2, alpha4over_zetapluseta, alpha4rho_over_eta2, cd_x, cd_y, cd_z, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_0, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_1, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_10, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_11, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_12, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_13, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_14, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_15, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_16, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_17, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_18, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_19, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_2, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_20, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_3, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_4, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_5, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_6, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_7, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_8, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_9, fgrid, igrid, irgrd, oo2e, oo2z, oo2ze, pa_x, pa_y, pa_z, qc_x, qc_y, qc_z, rfinc, rho12_over_alpha1, rho12_over_alpha2, rho34_over_alpha3, rho34_over_alpha4, rmr, roe, roz, two_alpha0_bra, two_alpha0_ket, two_alpha1bra, two_alpha1ket, wp_x, wp_y, wp_z, wq_x, wq_y, wq_z
ints_exchange calls libint_compute_eri
grd2_driver calls ints_exchange
fock_jk calls run, set_screening
hf_gradient calls grd2_driver
oqp_tdhf_z_vector calls run, set_screening
scf_driver calls run, set_screening
tdhf_2e_grad calls grd2_driver
tdhf_energy calls run, set_screening
tdhf_mrsf_energy calls run, set_screening
tdhf_sf_energy calls run, set_screening
hf_energy calls scf_driver
tdhf_energy_c calls tdhf_energy
tdhf_gradient calls tdhf_2e_grad
tdhf_mrsf_energy_c calls tdhf_mrsf_energy
tdhf_sf_energy_c calls tdhf_sf_energy
tdhf_z_vector_c calls oqp_tdhf_z_vector
tdhf_gradient_c calls tdhf_gradient