libint_print_eri – OPENQP
libint_print_eri Subroutine
44 statements
Source File
public subroutine libint_print_eri(basis, shell_ids, deriv_order, erieval, flips)
Uses
basis_tools
constants
Arguments
Type Intent Optional Attributes Name
type(basis_set) :: basis
integer, intent(in) :: shell_ids(4)
integer, intent(in) :: deriv_order
type(libint_t), intent(in), dimension(*) :: erieval
integer, intent(in) :: flips(4)
Called by
Call graph
fock_jk calls run
oqp_tdhf_z_vector calls run
scf_driver calls run
tdhf_energy calls run
tdhf_mrsf_energy calls run
tdhf_sf_energy calls run
hf_energy calls scf_driver
tdhf_energy_c calls tdhf_energy
tdhf_mrsf_energy_c calls tdhf_mrsf_energy
tdhf_sf_energy_c calls tdhf_sf_energy
tdhf_z_vector_c calls oqp_tdhf_z_vector