measure_time – OPENQP
measure_time Subroutine
29 statements
Source File
public subroutine measure_time(print_total, log_unit)
Uses
iso_fortran_env
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: print_total
integer, intent(in) :: log_unit
Called by
Source Code
  subroutine measure_time(print_total, log_unit)
    use iso_fortran_env, only: int64, real64
    implicit none
    integer, intent(in) :: print_total, log_unit
    integer(int64), save :: start_clock, previous_clock
    integer(int64) :: clock_rate, current_clock
    real(real64), save :: start_cpu_time, previous_cpu_time
    real(real64) :: current_cpu_time, elapsed_cpu_time, elapsed_wall_time
    logical, save :: first_call = .true.
    if (first_call) then
      call system_clock(start_clock, clock_rate)
      call cpu_time(start_cpu_time)
      previous_clock = start_clock
      previous_cpu_time = start_cpu_time
      first_call = .false.
    end if
    call system_clock(current_clock, clock_rate)
    call cpu_time(current_cpu_time)
    elapsed_wall_time = real(current_clock - previous_clock, &
                             real64) / real(clock_rate, real64)
    elapsed_cpu_time = current_cpu_time - previous_cpu_time
    write(log_unit, "(3X, A, F10.3, 3X, A, F10.3)") &
            "Step  CPU time (seconds): ", elapsed_cpu_time, &
            "Wall time (seconds): ", elapsed_wall_time
    previous_clock = current_clock
    previous_cpu_time = current_cpu_time
    if (print_total /= 0) then
      elapsed_wall_time = real(current_clock-start_clock, &
                               real64) / real(clock_rate, real64)
      elapsed_cpu_time = current_cpu_time - start_cpu_time
      write(log_unit, "(3X, A, F10.3, 3X, A, F10.3)") &
              "Total CPU time (seconds): ", elapsed_cpu_time, &
              "Wall time (seconds): ", elapsed_wall_time
    end if
  end subroutine measure_time
Call graph
fock_jk calls measure_time
get_states_overlap calls measure_time
get_structures_ao_overlap calls measure_time
guess_hcore calls measure_time
guess_huckel calls measure_time
guess_json calls measure_time
hf_gradient calls measure_time
oqp_tdhf_z_vector calls measure_time
scf_driver calls measure_time
tdhf_energy calls measure_time
tdhf_gradient calls measure_time
tdhf_mrsf_energy calls measure_time
tdhf_sf_energy calls measure_time
get_state_overlap_c calls get_states_overlap
get_structures_ao_overlap_c calls get_structures_ao_overlap
guess_hcore_c calls guess_hcore
guess_huckel_c calls guess_huckel
guess_json_c calls guess_json
hf_energy calls scf_driver
tdhf_energy_c calls tdhf_energy
tdhf_gradient_c calls tdhf_gradient
tdhf_mrsf_energy_c calls tdhf_mrsf_energy
tdhf_sf_energy_c calls tdhf_sf_energy
tdhf_z_vector_c calls oqp_tdhf_z_vector