mo_tran_symm_ – OPENQP
mo_tran_symm_ Subroutine
6 statements
Source File
public subroutine mo_tran_symm_(numAOs, nVecs, nPts, A, B, C)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: numAOs
integer, intent(in) :: nVecs
integer, intent(in) :: nPts
real(kind=fp), intent(in) :: A(*)
real(kind=fp), intent(in) :: B(*)
real(kind=fp), intent(inout) :: C(*)
Calls
Called by
Call graph
mo_tran_symm_ calls oqp_dsymm_i64
oqp_dsymm_i64 calls dsymm, show_message
run_xc calls compxc
derexc_blk calls run_xc
dmatd_blk calls run_xc
tddft_fxc calls run_xc
tddft_gxc calls run_xc
tddft_xc_gradient calls run_xc
utddft_fxc calls run_xc
utddft_xc_gradient calls run_xc
dftder calls derexc_blk
dftexcor calls dmatd_blk
oqp_tdhf_z_vector calls tddft_fxc, tddft_gxc
tdhf_energy calls tddft_fxc
tdhf_gradient calls tddft_xc_gradient
hf_gradient calls dftder
scf_driver calls dftexcor
tdhf_energy_c calls tdhf_energy
tdhf_gradient_c calls tdhf_gradient
tdhf_z_vector_c calls oqp_tdhf_z_vector
hf_energy calls scf_driver