mo_to_ao – OPENQP
mo_to_ao Subroutine
18 statements
Source File
public subroutine mo_to_ao(fao, fmo, s, v, nmo, nbf)
Uses
mathlib
oqp_linalg
@brief Back-transform a symmetric operator Fmo expressed in the MO basis V to the AO basis @detail compute the transformation: Fao = S*V * Fmo * (SV)^T
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(out) :: fao(*)
real(kind=dp), intent(in) :: fmo(*)
real(kind=dp), intent(in) :: s(*)
real(kind=dp), intent(in) :: v(*)
integer, intent(in) :: nmo
integer, intent(in) :: nbf
Calls
Called by
Source Code
  subroutine mo_to_ao(fao, fmo, s, v, nmo, nbf)
    use mathlib, only: pack_matrix, unpack_matrix
    use oqp_linalg
    implicit none
    real(kind=dp), intent(in) :: fmo(*), s(*), v(*)
    real(kind=dp), intent(out) :: fao(*)
    integer, intent(in) :: nmo, nbf
    integer :: nbf2
    real(kind=dp), allocatable :: sv(:,:), ftmp(:,:), wrk(:,:)
    allocate(ftmp(nbf,nbf), sv(nbf,nmo), wrk(nbf,nbf))
    call unpack_matrix(fmo, ftmp)
    call unpack_matrix(s, wrk)
    ! compute S*V
    call dsymm('l', 'u', nbf, nmo, &
               1.0_dp, wrk, nbf, &
                       v,  nbf, &
               0.0_dp, sv, nbf)
    ! compute (S * V) * Fmo
    call dsymm('r', 'u', nbf, nmo, &
               1.0d0, ftmp, nbf, &
                      sv,  nbf, &
               0.0d0, wrk, nbf)
    ! compute ((S * V) * Fmo) * (S * V)^T
    call dgemm('n', 't', nbf, nbf, nmo, &
               1.0d0, wrk, nbf, &
                      sv, nbf, &
               0.0d0, ftmp, nbf)
    nbf2 = nbf*(nbf+1)/2
    call pack_matrix(ftmp, fao(:nbf2))
  end subroutine mo_to_ao
Call graph
mo_to_ao calls pack_matrix, unpack_matrix, oqp_dgemm_i64, oqp_dsymm_i64
pack_matrix calls pack_f90
unpack_matrix calls unpack_f90
oqp_dgemm_i64 calls dgemm, show_message
oqp_dsymm_i64 calls dsymm, show_message
pack_f90 calls show_message, oqp_dtrttp_i64
unpack_f90 calls show_message, oqp_dtpttr_i64
oqp_dtpttr_i64 calls show_message, dtpttr
oqp_dtrttp_i64 calls show_message, dtrttp
scf_driver calls mo_to_ao
hf_energy calls scf_driver