multipole_integrals – OPENQP
multipole_integrals Subroutine
43 statements
Source File
public subroutine multipole_integrals(basis, ints, r, mxmom, debug, logtol)
Uses
io_constants
basis_tools
printing
precision
@brief Driver for multipole integrals @details Compute one electron multipole integrals Integrals are evaluated by Gauss-Hermite quadrature, @author Vladimir Mironov @date Feb, 2023 Initial release
@param[in,out] ints integrals, packed format @param[in] dbug flag for debug output
Arguments
Type Intent Optional Attributes Name
type(basis_set), intent(in) :: basis
real(kind=real64), intent(inout), contiguous :: ints(:,:)
real(kind=real64), intent(in) :: r(:)
integer, intent(in) :: mxmom
logical, intent(in), optional :: debug
real(kind=real64), intent(in), optional :: logtol
Calls
Called by
Call graph
multipole_integrals calls bas_norm_matrix, show_message, alloc, fetch_by_id, shell_pair, comp_allmult_int1_prim, print_sym_labeled, update_triang_matrix
comp_allmult_int1_prim calls mulquadgausshermite
print_sym_labeled calls bf_label
mulquadgausshermite calls abrt
electric_moments calls multipole_integrals
get_td_transition_dipole calls multipole_integrals
get_transition_dipole calls multipole_integrals
tdhf_energy calls get_td_transition_dipole
tdhf_mrsf_energy calls get_transition_dipole
tdhf_sf_energy calls get_transition_dipole
tdhf_energy_c calls tdhf_energy
tdhf_mrsf_energy_c calls tdhf_mrsf_energy
tdhf_sf_energy_c calls tdhf_sf_energy