omp_hst – OPENQP
omp_hst Subroutine
62 statements
Source File
public subroutine omp_hst(basis, coord, zq, h, s, t, z, debug, logtol, comm, usempi)
Uses
parallel
printing
iso_c_binding
precision
io_constants
basis_tools
ecp_tool
iso_fortran_env
@brief Driver for conventional h, S, and T integrals @details Compute one electron integrals and core Hamiltonian, - S is evaluated by Gauss-Hermite quadrature, - T is an overlap with -2,0,+2 angular momentum shifts, - V is evaluated by Gauss-Rys quadrature, then \f$ h = T+V \f$ Also, do \f$ L_z \f$ integrals if requested
Note
Based on HSANDT subroutine from file INT1.SRC @author Vladimir Mironov @date Sep, 2018 Initial release
@param[in,out] h one-electron Hamiltonian matrix in packet format @param[in,out] s packed matrix of overlap integrals @param[in,out] t packed matrix of kinetic energy integrals @param[in,out] z packed matrix of z-angular momentum (Lz) integrals @param[in] dbug flag for debug output
Arguments
Type Intent Optional Attributes Name
type(basis_set), intent(in) :: basis
real(kind=real64), intent(in), contiguous :: coord(:,:)
real(kind=real64), intent(in), contiguous :: zq(:)
real(kind=real64), intent(inout), contiguous :: h(:)
real(kind=real64), intent(inout), contiguous :: s(:)
real(kind=real64), intent(inout), contiguous :: t(:)
real(kind=real64), intent(inout), optional, contiguous :: z(:)
logical, intent(in), optional :: debug
real(kind=real64), intent(in), optional :: logtol
integer(kind=int32) :: comm
logical(kind=c_bool), intent(in) :: usempi
Calls
Called by
Call graph
omp_hst calls bas_norm_matrix, int1_coul, alloc, bcast, fetch_by_id, init, shell_pair, add_ecpint, comp_kin_ovl_int1_prim, comp_lz_int1_prim, print_sym_labeled, update_triang_matrix
add_ecpint calls compute_integrals, free_integrator, free_result, init_integrator, init_integrator_instance, set_ecp_basis, bf_to_shell
comp_kin_ovl_int1_prim calls doquadgausshermite
comp_lz_int1_prim calls doquadgausshermite
print_sym_labeled calls bf_label
doquadgausshermite calls abrt
int1e calls omp_hst