oqp_dsymm_i64 – OPENQP
oqp_dsymm_i64 Subroutine
31 statements
Source File
public subroutine oqp_dsymm_i64(side, uplo, m, n, alpha, a, lda, b, ldb, beta, c, ldc)
Arguments
Type Intent Optional Attributes Name
character(len=1) :: side
character(len=1) :: uplo
integer :: m
integer :: n
double precision :: alpha
double precision :: a(lda,*)
integer :: lda
double precision :: b(ldb,*)
integer :: ldb
double precision :: beta
double precision :: c(ldc,*)
integer :: ldc
Calls
Called by
Source Code
  subroutine oqp_dsymm_i64(side, uplo, m, n, alpha, a, lda, b, ldb, beta, c, ldc)
    double precision :: alpha
    double precision :: beta
    integer :: lda
    integer :: ldb
    integer :: ldc
    integer :: m
    integer :: n
    character :: side
    character :: uplo
    double precision :: a(lda,*)
    double precision :: b(ldb,*)
    double precision :: c(ldc,*)
    integer(blas_int) :: m_, n_, lda_, ldb_, ldc_
    logical :: ok
    if (ARG_CHECK) then
      ok = .true.
      ok = ok .and. abs(m   ) <= HUGE_BLAS_INT-1
      ok = ok .and. abs(n   ) <= HUGE_BLAS_INT-1
      ok = ok .and. abs(lda ) <= HUGE_BLAS_INT-1
      ok = ok .and. abs(ldb ) <= HUGE_BLAS_INT-1
      ok = ok .and. abs(ldc ) <= HUGE_BLAS_INT-1
      if (.not.ok) call show_message(ERRMSG, WITH_ABORT)
    end if
    m_   = int(m   , blas_int)
    n_   = int(n   , blas_int)
    lda_ = int(lda , blas_int)
    ldb_ = int(ldb , blas_int)
    ldc_ = int(ldc , blas_int)
    call dsymm(side, uplo, m_, n_, alpha, a, lda_, b, ldb_, beta, c, ldc_)
  end subroutine oqp_dsymm_i64
Call graph
oqp_dsymm_i64 calls dsymm, show_message
huckel_guess calls oqp_dsymm_i64, orthogonal_transform_sym
mo_to_ao calls oqp_dsymm_i64
mo_tran_symm_ calls oqp_dsymm_i64
orthogonal_transform_sym calls oqp_dsymm_i64
eijden calls orthogonal_transform_sym
form_rohf_fock calls orthogonal_transform_sym
guess_huckel calls huckel_guess
scf_driver calls add_data, mo_to_ao, form_rohf_fock, dftexcor
tdhf_mrsf_energy calls orthogonal_transform_sym
tdhf_sf_energy calls orthogonal_transform_sym
guess_huckel_c calls guess_huckel
hf_energy calls scf_driver
hf_gradient calls eijden, dftder
tdhf_1e_grad calls eijden
tdhf_mrsf_energy_c calls tdhf_mrsf_energy
tdhf_sf_energy_c calls tdhf_sf_energy
run_xc calls compxc
tdhf_gradient calls tdhf_1e_grad, tddft_xc_gradient
derexc_blk calls run_xc
dmatd_blk calls run_xc
tddft_fxc calls run_xc
tddft_gxc calls run_xc
tddft_xc_gradient calls run_xc
tdhf_gradient_c calls tdhf_gradient
utddft_fxc calls run_xc
utddft_xc_gradient calls run_xc
dftder calls derexc_blk
dftexcor calls dmatd_blk
oqp_tdhf_z_vector calls tddft_fxc, tddft_gxc
tdhf_energy calls tddft_fxc
tdhf_energy_c calls tdhf_energy
tdhf_z_vector_c calls oqp_tdhf_z_vector