oqp_dorgqr_i64 – OPENQP
oqp_dorgqr_i64 Subroutine
22 statements
Source File
public subroutine oqp_dorgqr_i64(m, n, k, a, lda, tau, work, lwork, info)
Arguments
Type Intent Optional Attributes Name
integer :: m
integer :: n
integer :: k
real(kind=dp) :: a(lda,*)
integer :: lda
real(kind=dp) :: tau(*)
real(kind=dp) :: work(*)
integer :: lwork
integer :: info
Calls
Called by
Call graph
oqp_dorgqr_i64 calls dorgqr, show_message
schmd calls oqp_dorgqr_i64
corresponding_orbital_projection calls schmd
huckel_guess calls corresponding_orbital_projection
guess_huckel calls huckel_guess
guess_huckel_c calls guess_huckel