oqp_dtrttp_i64 – OPENQP
oqp_dtrttp_i64 Subroutine
17 statements
Source File
public subroutine oqp_dtrttp_i64(uplo, n, a, lda, ap, info)
Arguments
Type Intent Optional Attributes Name
character(len=*) :: uplo
integer :: n
real(kind=dp) :: a(lda,*)
integer :: lda
real(kind=dp) :: ap(*)
integer :: info
Calls
Called by
Call graph
oqp_dtrttp_i64 calls dtrttp, show_message
orthogonal_transform_sym calls oqp_dtrttp_i64
pack_f90 calls oqp_dtrttp_i64
rpaeig calls oqp_dtrttp_i64
pack_matrix calls pack_f90
eijden calls orthogonal_transform_sym
form_rohf_fock calls orthogonal_transform_sym, pack_matrix
huckel_guess calls orthogonal_transform_sym
tdhf_energy calls rpaeig, get_td_transition_dipole
tdhf_mrsf_energy calls orthogonal_transform_sym, rpaeig, get_transition_dipole
tdhf_sf_energy calls orthogonal_transform_sym, rpaeig, get_spin_square, get_transition_dipole, sfdmat
build_pfon_density calls pack_matrix
get_spin_square calls pack_matrix
get_td_transition_dipole calls pack_matrix
get_transition_dipole calls pack_matrix
guess_huckel calls huckel_guess, get_ab_initio_density
hf_gradient calls eijden
mo_to_ao calls pack_matrix
oqp_tdhf_z_vector calls pack_matrix, tdhf_unrelaxed_density
orb_to_dens calls pack_matrix
scf_driver calls form_rohf_fock, add_data, build_pfon_density, mo_to_ao, get_ab_initio_density
sfdmat calls pack_matrix
tdhf_1e_grad calls eijden
tdhf_energy_c calls tdhf_energy
tdhf_mrsf_energy_c calls tdhf_mrsf_energy
tdhf_sf_energy_c calls tdhf_sf_energy
tdhf_unrelaxed_density calls pack_matrix
get_ab_initio_density calls orb_to_dens
guess_huckel_c calls guess_huckel
hf_energy calls scf_driver
tdhf_gradient calls tdhf_1e_grad
tdhf_z_vector_c calls oqp_tdhf_z_vector
guess_hcore calls get_ab_initio_density
guess_json calls get_ab_initio_density
tdhf_gradient_c calls tdhf_gradient
guess_hcore_c calls guess_hcore
guess_json_c calls guess_json