oqp_dtpttr_i64 – OPENQP
oqp_dtpttr_i64 Subroutine
17 statements
Source File
public subroutine oqp_dtpttr_i64(uplo, n, ap, a, lda, info)
Arguments
Type Intent Optional Attributes Name
character(len=*) :: uplo
integer :: n
real(kind=dp) :: ap(*)
real(kind=dp) :: a(lda,*)
integer :: lda
integer :: info
Calls
Called by
Call graph
oqp_dtpttr_i64 calls dtpttr, show_message
orthogonal_transform_sym calls oqp_dtpttr_i64
unpack_f90 calls oqp_dtpttr_i64
unpack_matrix calls unpack_f90
eijden calls orthogonal_transform_sym, unpack_matrix
form_rohf_fock calls orthogonal_transform_sym, unpack_matrix
huckel_guess calls orthogonal_transform_sym, unpack_matrix
tdhf_mrsf_energy calls orthogonal_transform_sym, unpack_matrix
tdhf_sf_energy calls orthogonal_transform_sym, unpack_matrix, get_spin_square
dftder calls unpack_matrix
get_ab_initio_orbital calls unpack_matrix
get_spin_square calls unpack_matrix
grad_ee_kinetic calls unpack_matrix
grad_ee_overlap calls unpack_matrix
grad_en_hellman_feynman calls unpack_matrix
grad_en_pulay calls unpack_matrix
guess_huckel calls huckel_guess
hf_gradient calls eijden, dftder, grad_ee_kinetic, grad_ee_overlap, grad_en_hellman_feynman, grad_en_pulay
mo_to_ao calls unpack_matrix
oqp_tdhf_z_vector calls unpack_matrix
run_population_analysis calls unpack_matrix
scf_driver calls unpack_matrix, form_rohf_fock, add_data, get_ab_initio_orbital, mo_to_ao
tdhf_1e_grad calls eijden, grad_ee_kinetic, grad_ee_overlap, grad_en_hellman_feynman, grad_en_pulay
tdhf_gradient calls unpack_matrix, tdhf_1e_grad
tdhf_mrsf_energy_c calls tdhf_mrsf_energy
tdhf_sf_energy_c calls tdhf_sf_energy
guess_hcore calls get_ab_initio_orbital
guess_huckel_c calls guess_huckel
hf_energy calls scf_driver
lowdin calls run_population_analysis
mulliken calls run_population_analysis
tdhf_gradient_c calls tdhf_gradient
tdhf_z_vector_c calls oqp_tdhf_z_vector
guess_hcore_c calls guess_hcore