oqp_dsysv_i64 – OPENQP
oqp_dsysv_i64 Subroutine
27 statements
Source File
public subroutine oqp_dsysv_i64(uplo, n, nrhs, a, lda, ipiv, b, ldb, work, lwork, info)
Arguments
Type Intent Optional Attributes Name
character(len=*) :: uplo
integer :: n
integer :: nrhs
real(kind=dp) :: a(*)
integer :: lda
integer :: ipiv(*)
real(kind=dp) :: b(*)
integer :: ldb
real(kind=dp) :: work(*)
integer :: lwork
integer :: info
Calls
Called by
Call graph
oqp_dsysv_i64 calls dsysv, show_message
solve_linear_equations calls oqp_dsysv_i64