oqp_dgesv_i64 – OPENQP
oqp_dgesv_i64 Subroutine
24 statements
Source File
public subroutine oqp_dgesv_i64(n, nrhs, a, lda, ipiv, b, ldb, info)
Arguments
Type Intent Optional Attributes Name
integer :: n
integer :: nrhs
real(kind=dp) :: a(lda,*)
integer :: lda
integer :: ipiv(*)
real(kind=dp) :: b(ldb,*)
integer :: ldb
integer :: info
Calls
Called by
Call graph
oqp_dgesv_i64 calls dgesv, show_message
oqp_resp_charges calls oqp_dgesv_i64
resp_charges_c calls oqp_resp_charges