oqp_dsyr2k_i64 – OPENQP
oqp_dsyr2k_i64 Subroutine
31 statements
Source File
public subroutine oqp_dsyr2k_i64(uplo, trans, n, k, alpha, a, lda, b, ldb, beta, c, ldc)
Arguments
Type Intent Optional Attributes Name
character(len=1) :: uplo
character(len=1) :: trans
integer :: n
integer :: k
double precision :: alpha
double precision :: a(lda,*)
integer :: lda
double precision :: b(ldb,*)
integer :: ldb
double precision :: beta
double precision :: c(ldc,*)
integer :: ldc
Calls
Called by
Source Code
  subroutine oqp_dsyr2k_i64(uplo, trans, n, k, alpha, a, lda, b, ldb, beta, c, ldc)
    double precision :: alpha
    double precision :: beta
    integer :: k
    integer :: lda
    integer :: ldb
    integer :: ldc
    integer :: n
    character :: trans
    character :: uplo
    double precision :: a(lda,*)
    double precision :: b(ldb,*)
    double precision :: c(ldc,*)
    integer(blas_int) :: n_, k_, lda_, ldb_, ldc_
    logical :: ok
    if (ARG_CHECK) then
      ok = .true.
      ok = ok .and. abs(n   ) <= HUGE_BLAS_INT-1
      ok = ok .and. abs(k   ) <= HUGE_BLAS_INT-1
      ok = ok .and. abs(lda ) <= HUGE_BLAS_INT-1
      ok = ok .and. abs(ldb ) <= HUGE_BLAS_INT-1
      ok = ok .and. abs(ldc ) <= HUGE_BLAS_INT-1
      if (.not.ok) call show_message(ERRMSG, WITH_ABORT)
    end if
    n_   = int(n   , blas_int)
    k_   = int(k   , blas_int)
    lda_ = int(lda , blas_int)
    ldb_ = int(ldb , blas_int)
    ldc_ = int(ldc , blas_int)
    call dsyr2k(uplo, trans, n_, k_, alpha, a, lda_, b, ldb_, beta, c, ldc_)
  end subroutine oqp_dsyr2k_i64
Call graph
oqp_dsyr2k_i64 calls dsyr2k, show_message
oqp_tdhf_z_vector calls oqp_dsyr2k_i64
orb_to_dens calls oqp_dsyr2k_i64
get_ab_initio_density calls orb_to_dens
tdhf_z_vector_c calls oqp_tdhf_z_vector
guess_hcore calls get_ab_initio_density
guess_huckel calls get_ab_initio_density
guess_json calls get_ab_initio_density
scf_driver calls get_ab_initio_density
guess_hcore_c calls guess_hcore
guess_huckel_c calls guess_huckel
guess_json_c calls guess_json
hf_energy calls scf_driver