oqp_banner_C – OPENQP
oqp_banner_C Subroutine
8 statements
Source File
public subroutine oqp_banner_C(c_handle) bind(C, name="oqp_banner")
Uses
c_interop
types
Arguments
Type Intent Optional Attributes Name
type(oqp_handle_t) :: c_handle
Calls
Source Code
  subroutine oqp_banner_C(c_handle) bind(C, name="oqp_banner")
    use c_interop, only: oqp_handle_t, oqp_handle_get_info
    use types, only: information
    type(oqp_handle_t) :: c_handle
    type(information), pointer :: inf
    inf => oqp_handle_get_info(c_handle)
    call oqp_banner(inf)
  end subroutine oqp_banner_C
Call graph
oqp_banner_c calls oqp_handle_get_info, oqp_banner
oqp_banner calls data_has_tags, tagarray_get_data, get_hostnames, init