oqp_dormqr_i64 – OPENQP
oqp_dormqr_i64 Subroutine
25 statements
Source File
public subroutine oqp_dormqr_i64(side, trans, m, n, k, a, lda, tau, c, ldc, work, lwork, info)
Arguments
Type Intent Optional Attributes Name
character(len=*) :: side
character(len=*) :: trans
integer :: m
integer :: n
integer :: k
real(kind=dp) :: a(lda,*)
integer :: lda
real(kind=dp) :: tau(*)
real(kind=dp) :: c(ldc,*)
integer :: ldc
real(kind=dp) :: work(*)
integer :: lwork
integer :: info
Calls
Called by
Call graph
oqp_dormqr_i64 calls dormqr, show_message
huckel_guess calls oqp_dormqr_i64
guess_huckel calls huckel_guess
guess_huckel_c calls guess_huckel