oqp_tdhf_z_vector – OPENQP
oqp_tdhf_z_vector Subroutine
149 statements
Source File
public subroutine oqp_tdhf_z_vector(infos)
Uses
mod_dft_gridint_gxc
dft
printing
tdhf_lib
mod_dft_gridint_fxc
messages
oqp_tagarray_driver
pcg_mod
tdhf_sf_lib
util
mathlib
mod_dft_molgrid
strings
Arguments
Type Intent Optional Attributes Name
type(information), intent(inout), target :: infos
Calls
Called by
Source Code
  subroutine oqp_tdhf_z_vector(infos)
    use oqp_tagarray_driver
    use strings, only: Cstring, fstring
    use messages, only: show_message, with_abort
    use util, only: measure_time
    use tdhf_lib, only: iatogen, mntoia, esum, &
      tdhf_unrelaxed_density
    use tdhf_sf_lib, only: sfrorhs, &
      sfromcal, sfrogen, sfrolhs, &
      pcgb, sfropcal, sfrowcal
    use dft, only: dft_initialize, dftclean
    use mod_dft_gridint_fxc, only: tddft_fxc
    use mod_dft_gridint_gxc, only: tddft_gxc
    use mathlib, only: symmetrize_matrix, orthogonal_transform
    use mod_dft_molgrid, only: dft_grid_t
    use mathlib, only: pack_matrix, unpack_matrix
    use mathlib, only: triangular_to_full
    use tdhf_lib, only: int2_rpagrd_data_t
    use pcg_mod
    use printing, only: print_module_info
    implicit none
    character(len=*), parameter :: subroutine_name = "oqp_tdhf_z_vector"
    type(basis_set), pointer :: basis
    type(information), target, intent(inout) :: infos
    type(dft_grid_t), target :: molGrid
    type(int2_compute_t), target :: int2_driver
    class(int2_fock_data_t), allocatable, target :: int2_data
    type(tdhf_cg_data) :: cgdata
    type(pcg_t) :: pcg
    real(kind=dp), allocatable :: hpp(:,:,:), hpt(:,:,:), hmm(:,:,:), gxp(:,:,:)
    real(kind=dp), allocatable, target :: wrk1(:,:), &
            rhs(:), xm(:), zvec(:), xminv(:), pa(:,:,:)
    real(kind=dp), contiguous, pointer :: ppa(:,:,:,:), &
            pxm(:,:), prhs(:,:), wmo(:,:)
    logical :: dft, tda
    integer :: scf_type, mol_mult
    integer :: i, j, iter, ok
    integer :: nocc, nvir, lexc, nbf, nbf2
    real(kind=dp) :: cnvtol, scale_exch
    ! tagarray
    real(kind=dp), contiguous, pointer :: &
      mo_a(:,:), mo_energy_a(:), wao(:), td_p(:,:), td_t(:,:), &
      ta(:), xpy(:,:), xmy(:,:), td_energies(:)
    character(len=*), parameter :: &
      tags_required(*) = [  character(len=80) :: &
        OQP_E_MO_A, OQP_VEC_MO_A, OQP_TD_T, OQP_TD_XPY, OQP_TD_XMY, &
        OQP_td_energies &
      ]
  ! Log file
    open (unit=IW, file=infos%log_filename, position="append")
  !
    call print_module_info('TDHF_Z_Vector','Solving Z-Vector for TDDFT')
    mol_mult = infos%mol_prop%mult
    scf_type = infos%control%scftype
    dft = infos%control%hamilton == 20
    tda = infos%tddft%tda
  ! Load basis set
    basis => infos%basis
    basis%atoms => infos%atoms
    nbf = basis%nbf
    nbf2 = nbf*(nbf+1)/2
    if (dft) call dft_initialize(infos, basis, molGrid)
  ! Parameter it should be inputed later
  ! convergence tolerance in the iterative TD-DFT step.
    cnvtol = infos%tddft%zvconv
    nocc = infos%mol_prop%nocc
    nvir = nbf-nocc
    lexc = nocc*nvir
    allocate(&
      rhs(lexc), &
      pa(nbf,nbf,1), &
      wrk1(nbf,nbf), &
      stat=ok, &
      source=0.0_dp)
    if( ok/=0 ) call show_message('Cannot allocate memory', with_abort)
    call infos%dat%remove_records([character(80) :: OQP_WAO, OQP_TD_P])
    call data_has_tags(infos%dat, tags_required, module_name, subroutine_name, WITH_ABORT)
    call tagarray_get_data(infos%dat, OQP_E_MO_A, mo_energy_a)
    call tagarray_get_data(infos%dat, OQP_VEC_MO_A, mo_a)
    call tagarray_get_data(infos%dat, OQP_TD_T, td_t)
    call tagarray_get_data(infos%dat, OQP_TD_XPY, xpy)
    call tagarray_get_data(infos%dat, OQP_TD_XMY, xmy)
    call tagarray_get_data(infos%dat, OQP_td_energies, td_energies)
    ta => td_t(:,1)
    write(iw,'(/1x,71("-")&
             &/19x,"TD-DFT ENERGY GRADIENT CALCULATION"&
             &/1x,71("-")/)')
    write(iw,fmt='(5x,a/&
                  &5x,16("-")/&
                  &5x,a,x,i0,x,f17.10,x,"Hartree"/&
                  &5x,a,x,i0/&
                  &5x,a,x,e10.4/&
                  &5x,a,x,i0)') &
        'Z-vector options' &
      , 'Target state       is', infos%tddft%target_state, infos%mol_energy%energy+td_energies(infos%tddft%target_state) &
      , 'Multiplicity       is', infos%tddft%mult &
      , 'Convergence        is', infos%tddft%zvconv &
      , 'Maximum iterations is', infos%control%maxit_zv
    call flush(iw)
!   1. Compute right-hand side of Z-vector equation
    allocate(hpp(nbf,nbf,1), & ! H+[X+Y]
             hpt(nbf,nbf,1), & ! H+[T]
             hmm(nbf,nbf,1), & ! H-[X-Y]
             gxp(nbf,nbf,1), & ! g_xc[X+Y][X+Y]
             source=0.0d0)
    call tdhf_unrelaxed_density(xmy(:,infos%tddft%target_state), xpy(:,infos%tddft%target_state), mo_a, td_t(:,1), nocc, tda)
    ! Initialize ERI calculations
    call int2_driver%init(basis, infos)
    call int2_driver%set_screening()
    ! Compute H+[X+Y], H+[T], H-[X-Y], and G_xc
    call compute_r_terms(infos, basis, int2_driver, molGrid, mo_a, xpy(:,infos%tddft%target_state), &
                         xmy(:,infos%tddft%target_state), ta, hpp, hpt, hmm, gxp)
    ! Transform Gxc to MO basis
    call orthogonal_transform('n', nbf, mo_a, gxp(:,:,1))
    ! Assemble RHS in MO basis
    prhs(1:nocc,1:nvir) => rhs(1:)
    call compute_r_mo(prhs, mo_a, xpy(:,infos%tddft%target_state), xmy(:,infos%tddft%target_state), hpt, hpp, hmm, gxp(:,:,1))
    rhs = -rhs
!   2. Initialize CG for Z-vector solution
    write(iw,'(/3x,25("-")&
             &/6x,"START Z-VECTOR LOOP"&
             &/3x,25("-")/)')
    call flush(iw)
    allocate(xminv(lexc), &
             xm(lexc), &
             stat=ok, &
             source=0.0_dp)
    if( ok/=0 ) call show_message('Cannot allocate memory', with_abort)
    scale_exch = 1.0_dp
    if (dft) scale_exch = infos%dft%HFscale
    int2_data = int2_td_data_t(d2=pa, &
            int_apb=.true., &
            int_amb=.false., &
            tamm_dancoff=tda, &
            scale_exchange=scale_exch)
    pxm(1:nocc, 1:nvir) => xm(1:)
    do i = 1, nvir
      do j = 1, nocc
        pxm(j,i) = mo_energy_a(nocc+i) - mo_energy_a(j)
      end do
    end do
    xminv = 1.0d0/xm
    cgdata = tdhf_cg_data( &
        infos=infos, int2_driver=int2_driver, &
        int2_data=int2_data, molgrid=molgrid, &
        wrk=wrk1, mo=mo_a, pa=pa, xm=xm, xminv=xminv, &
        nbf=nbf, nocc = nocc, dft = dft &
      )
    call pcg%init(b=rhs, &
      update=compute_apbx, precond=precond, &
      dat=cgdata, tol=sqrt(abs(cnvtol)))
    write(iw,'(" INITIAL ERROR =",3X,1P,E10.3,1X,"/",1P,E10.3)') pcg%error**2, cnvtol
    ! Begin CG iterations
    do iter = 1, infos%control%maxit_zv
      if (pcg%errcode /= PCG_OK) exit
      call pcg%step()
      write(iw,'(" ITER#",I2," ERROR =",3X,1P,E10.3,1X,"/",1P,E10.3)') &
              iter, pcg%error**2, cnvtol
      call flush(iw)
    end do
    select case (pcg%errcode)
    case (PCG_CONVERGED)
      write(iw,'(/3x,24("-")&
               &/6x,"Z-Vector converged"&
               &/3x,24("-")/)')
      infos%mol_energy%Z_Vector_converged=.true.
    case default
      write(iw,'(/3x,24("-")&
               &/6x,"Z-Vector not converged"&
               &/3x,24("-")/)')
      infos%mol_energy%Z_Vector_converged=.false.
    end select
    call flush(iw)
!   Save Z-vector and clean up memory
    deallocate(xminv, rhs, xm)
    call int2_data%clean()
    deallocate(int2_data)
    allocate(zvec, source=pcg%x)
    call pcg%clean()
!   3. Now, compute relaxed energy-weighted difference density matrix W
    ! Convert Z-vector from MO to AO and assemble P = T+Z
    pa = 0
    call iatogen(zvec, pa(:,:,1), nocc, nocc)
    call symmetrize_matrix(pa(:,:,1), nbf)
    pa(:,:,1) = 0.5*pa(:,:,1)
    call orthogonal_transform('t', nbf, mo_a, pa(:,:,1))
    call unpack_matrix(ta, wrk1) ! T
    pa(:,:,1) = pa(:,:,1) + wrk1 ! T+Z
    ! Store relaxed difference density matrix P to global memory
    call infos%dat%reserve_data(OQP_td_p, TA_TYPE_REAL64, nbf2, [nbf2, 1], comment=OQP_td_p_comment)
    call tagarray_get_data(infos%dat, OQP_td_p, td_p)
    call pack_matrix(pa(:,:,1), td_p(:,1))
    ! Compute H+[P]
    ppa(1:nbf,1:nbf, 1:1, 1:1) => pa
    int2_data = int2_rpagrd_data_t(&
            xpy=null(), &
            xmy=null(), &
            t=ppa, &
            nspin = 1, &
            tamm_dancoff=tda, &
            scale_exchange=scale_exch)
    call int2_driver%run(int2_data, &
            cam=dft.and.infos%dft%cam_flag, &
            alpha=infos%dft%cam_alpha, &
            beta=infos%dft%cam_beta,&
            mu=infos%dft%cam_mu)
    select type (int2_data)
    type is (int2_rpagrd_data_t)
      hpt = int2_data%hpt(:,:,:,1,1)
    end select
    call int2_data%clean()
    deallocate(int2_data)
    if (dft) then
      pa = pa*2
      call tddft_fxc(basis=basis, &
             molGrid=molGrid, &
             isVecs=.true., &
             wf=MO_A, &
             fx=hpt(:,:,1:1), &
             dx=pa(:,:,1:1), &
             nmtx=1, &
             !threshold=1.0d-15, &
             threshold=0.0d0, &
             infos=infos)
    end if
    ! Transform H+[P], H+[X+Y], H-[X-Y] from AO to MO basis
    call orthogonal_transform('n', nbf, mo_a, hpt(:,:,1), wrk=wrk1) ! P
    call orthogonal_transform('n', nbf, mo_a, hpp(:,:,1), wrk=wrk1) ! X+Y
    call orthogonal_transform('n', nbf, mo_a, hmm(:,:,1), wrk=wrk1) ! X-Y
    ! Calculate W in MO basis
    wmo(1:nbf,1:nbf) => wrk1
    call compute_w_mo(wmo, xpy(:,infos%tddft%target_state), xmy(:,infos%tddft%target_state), zvec, &
            hpt(:,:,1), hpp(:,:,1), hmm(:,:,1), &
            mo_energy_a, td_energies(infos%tddft%target_state), nocc, gxp(:,:,1))
    ! Transform W from MO to AO basis
    call orthogonal_transform('t', nbf, mo_a, wmo)
    ! Store W to global memory
    call infos%dat%reserve_data(OQP_WAO, TA_TYPE_REAL64, nbf2, comment=OQP_WAO_comment)
    call tagarray_get_data(infos%dat, OQP_WAO, wao)
    call pack_matrix(wmo, wao)
    wao = wao*0.5_dp
    ! Cleanup
    call int2_driver%clean()
    if (dft) call dftclean(infos)
    call measure_time(print_total=1, log_unit=iw)
    close(iw)
  end subroutine oqp_tdhf_z_vector
Call graph
oqp_tdhf_z_vector calls data_has_tags, pack_matrix, show_message, tagarray_get_data, unpack_matrix, clean, init, run, set_screening, step, dft_initialize, dftclean, iatogen, int2_rpagrd_data_t_clean, measure_time, oqp_dgemm_i64, oqp_dsyr2k_i64, orthogonal_transform, print_module_info, symmetrize_matrix, tddft_fxc, tddft_gxc, tdhf_unrelaxed_density, triangular_to_full, remove_records, reserve_data
pack_matrix calls pack_f90
unpack_matrix calls unpack_f90
dft_initialize calls show_message, add_atomic_grid, add_grid, compress, find_neighbours, reset, set_screening, c_f_char, dft_fc_blk, get_radial_grid, libxc_input, set_bragg_slater
dftclean calls libxc_destroy
oqp_dgemm_i64 calls show_message, dgemm
oqp_dsyr2k_i64 calls show_message, dsyr2k
orthogonal_transform calls show_message, oqp_dgemm_i64
tddft_fxc calls triangular_to_full, clean, init, run_xc
tddft_gxc calls triangular_to_full, clean, init, run_xc
tdhf_unrelaxed_density calls pack_matrix, oqp_dgemm_i64, orthogonal_transform
triangular_to_full calls show_message
dft_fc_blk calls getbyid, set
get_radial_grid calls set, transform
ints_exchange calls show_message, alloc, compute, set, libint2_cleanup_eri, libint2_init_eri, clean, init, set_ids, genr22, int2_rys_compute, libint_compute_eri
libint_static_init calls libint2_static_init
libxc_destroy calls destroy
libxc_input calls show_message, add_functional, can_calculate, xc_f03_reference, xc_f03_reference_doi, xc_f03_version_string
pack_f90 calls show_message, oqp_dtrttp_i64
run_xc calls allreduce, compaos, compxc, getslicenonzero, getstats, init, pruneaos, resetpointers, parallel_start, parallel_stop, postUpdate, update
unpack_f90 calls show_message, oqp_dtpttr_i64
genr22 calls fgrid, rfinc, rmr, xgrid
int2_rys_compute calls evaluate
lebedev_get_grid calls show_message
libint_compute_eri calls ab_x, ab_y, ab_z, alpha1over_zetapluseta, alpha1rho_over_zeta2, alpha2over_zetapluseta, alpha2rho_over_zeta2, alpha3over_zetapluseta, alpha3rho_over_eta2, alpha4over_zetapluseta, alpha4rho_over_eta2, cd_x, cd_y, cd_z, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_0, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_1, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_10, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_11, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_12, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_13, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_14, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_15, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_16, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_17, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_18, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_19, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_2, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_20, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_3, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_4, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_5, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_6, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_7, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_8, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_9, fgrid, igrid, irgrd, oo2e, oo2z, oo2ze, pa_x, pa_y, pa_z, qc_x, qc_y, qc_z, rfinc, rho12_over_alpha1, rho12_over_alpha2, rho34_over_alpha3, rho34_over_alpha4, rmr, roe, roz, two_alpha0_bra, two_alpha0_ket, two_alpha1bra, two_alpha1ket, wp_x, wp_y, wp_z, wq_x, wq_y, wq_z
oqp_dtpttr_i64 calls show_message, dtpttr
oqp_dtrttp_i64 calls show_message, dtrttp
compute calls calc_evfxc, calc_evxc, calc_xc, scalexc
init calls clean, resetenergy
mo_tran_gemm_ calls oqp_dgemm_i64
mo_tran_symm_ calls oqp_dsymm_i64
oqp_dsymm_i64 calls show_message, dsymm
tdhf_z_vector_c calls oqp_tdhf_z_vector