oqp_dgemm_i64 – OPENQP
oqp_dgemm_i64 Subroutine
34 statements
Source File
public subroutine oqp_dgemm_i64(transa, transb, m, n, k, alpha, a, lda, b, ldb, beta, c, ldc)
Arguments
Type Intent Optional Attributes Name
character(len=1) :: transa
character(len=1) :: transb
integer :: m
integer :: n
integer :: k
double precision :: alpha
double precision :: a(lda,*)
integer :: lda
double precision :: b(ldb,*)
integer :: ldb
double precision :: beta
double precision :: c(ldc,*)
integer :: ldc
Calls
Called by
Source Code
  subroutine oqp_dgemm_i64(transa, transb, m, n, k, alpha, a, lda, b, ldb, beta, c, ldc)
    double precision :: alpha
    double precision :: beta
    integer :: k
    integer :: lda
    integer :: ldb
    integer :: ldc
    integer :: m
    integer :: n
    character :: transa
    character :: transb
    double precision :: a(lda,*)
    double precision :: b(ldb,*)
    double precision :: c(ldc,*)
    integer(blas_int) :: m_, n_, k_, lda_, ldb_, ldc_
    logical :: ok
    if (ARG_CHECK) then
      ok = .true.
      ok = ok .and. abs(m   ) <= HUGE_BLAS_INT-1
      ok = ok .and. abs(n   ) <= HUGE_BLAS_INT-1
      ok = ok .and. abs(k   ) <= HUGE_BLAS_INT-1
      ok = ok .and. abs(lda ) <= HUGE_BLAS_INT-1
      ok = ok .and. abs(ldb ) <= HUGE_BLAS_INT-1
      ok = ok .and. abs(ldc ) <= HUGE_BLAS_INT-1
      if (.not.ok) call show_message(ERRMSG, WITH_ABORT)
    end if
    m_   = int(m   , blas_int)
    n_   = int(n   , blas_int)
    k_   = int(k   , blas_int)
    lda_ = int(lda , blas_int)
    ldb_ = int(ldb , blas_int)
    ldc_ = int(ldc , blas_int)
    call dgemm(transa, transb, m_, n_, k_, alpha, a, lda_, b, ldb_, beta, c, ldc_)
  end subroutine oqp_dgemm_i64
Call graph
oqp_dgemm_i64 calls dgemm, show_message
corresponding_orbital_projection calls oqp_dgemm_i64
get_ab_initio_orbital calls oqp_dgemm_i64, orthogonal_transform
get_spin_square calls oqp_dgemm_i64
huckel_guess calls oqp_dgemm_i64, corresponding_orbital_projection, orthogonal_transform_sym
mntoia calls oqp_dgemm_i64
mo_to_ao calls oqp_dgemm_i64
mo_tran_gemm_ calls oqp_dgemm_i64
mrsfcbc calls oqp_dgemm_i64
mrsfesum calls oqp_dgemm_i64
mrsfmntoia calls oqp_dgemm_i64
mrsfqrorhs calls oqp_dgemm_i64
mrsfsp calls oqp_dgemm_i64
oqp_resp_charges calls oqp_dgemm_i64
oqp_tdhf_z_vector calls oqp_dgemm_i64, orthogonal_transform, tdhf_unrelaxed_density, tddft_fxc, tddft_gxc
orthogonal_transform calls oqp_dgemm_i64
orthogonal_transform2 calls oqp_dgemm_i64
orthogonal_transform_sym calls oqp_dgemm_i64
rpaeig calls oqp_dgemm_i64
rpaexpndv calls oqp_dgemm_i64
rparedms calls oqp_dgemm_i64
run_population_analysis calls oqp_dgemm_i64
sfdmat calls oqp_dgemm_i64, orthogonal_transform
sfresvec calls oqp_dgemm_i64
sfrorhs calls oqp_dgemm_i64
sfrowcal calls oqp_dgemm_i64
tdhf_mrsf_energy calls oqp_dgemm_i64, mntoia, mrsfcbc, mrsfesum, mrsfmntoia, orthogonal_transform, orthogonal_transform_sym, rpaeig, rparedms, sfresvec, trfrmb, get_transition_dipole
tdhf_sf_energy calls oqp_dgemm_i64, get_spin_square, mntoia, orthogonal_transform_sym, rpaeig, rparedms, sfdmat, sfresvec, trfrmb, get_transition_dipole
tdhf_unrelaxed_density calls oqp_dgemm_i64, orthogonal_transform
trfrmb calls oqp_dgemm_i64
eijden calls orthogonal_transform_sym
form_rohf_fock calls orthogonal_transform2, orthogonal_transform_sym
get_td_transition_dipole calls orthogonal_transform
get_transition_dipole calls orthogonal_transform
guess_hcore calls get_ab_initio_orbital
guess_huckel calls huckel_guess
lowdin calls run_population_analysis
mulliken calls run_population_analysis
resp_charges_c calls oqp_resp_charges
scf_driver calls add_data, get_ab_initio_orbital, mo_to_ao, form_rohf_fock, dftexcor
tdhf_energy calls mntoia, orthogonal_transform, rpaeig, rpaexpndv, rparedms, get_td_transition_dipole, tddft_fxc
tdhf_gradient calls orthogonal_transform, tdhf_1e_grad, tddft_xc_gradient
tdhf_mrsf_energy_c calls tdhf_mrsf_energy
tdhf_sf_energy_c calls tdhf_sf_energy
tdhf_z_vector_c calls oqp_tdhf_z_vector
guess_hcore_c calls guess_hcore
guess_huckel_c calls guess_huckel
hf_energy calls scf_driver
hf_gradient calls eijden, dftder
tdhf_1e_grad calls eijden
tdhf_energy_c calls tdhf_energy
tdhf_gradient_c calls tdhf_gradient
run_xc calls compxc
derexc_blk calls run_xc
dmatd_blk calls run_xc
tddft_fxc calls run_xc
tddft_gxc calls run_xc
tddft_xc_gradient calls run_xc
utddft_fxc calls run_xc
utddft_xc_gradient calls run_xc
dftder calls derexc_blk
dftexcor calls dmatd_blk