orb_to_dens – OPENQP
orb_to_dens Subroutine
16 statements
Source File
public subroutine orb_to_dens(d, v, x, m, n, ldv)
Uses
precision
@brief Compute density matrix from a set of orbitals and respective occupation numbers @detail Compute the transformation: D = V * X * V^T @param[out] d density matrix @param[in] v matrix of orbitals @param[in] x vector of occupation numbers @param[in] m number of columns in V @param[in] n dimension of D @param[in] ldv leading dimension of V
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(out) :: d(*)
real(kind=dp), intent(in) :: v(ldv,*)
real(kind=dp), intent(in) :: x(*)
integer, intent(in) :: m
integer, intent(in) :: n
integer, intent(in) :: ldv
Calls
Called by
Call graph
orb_to_dens calls pack_matrix, oqp_dsyr2k_i64
pack_matrix calls pack_f90
oqp_dsyr2k_i64 calls dsyr2k, show_message
pack_f90 calls show_message, oqp_dtrttp_i64
oqp_dtrttp_i64 calls show_message, dtrttp
get_ab_initio_density calls orb_to_dens
guess_hcore calls get_ab_initio_density
guess_huckel calls get_ab_initio_density
guess_json calls get_ab_initio_density
scf_driver calls get_ab_initio_density
guess_hcore_c calls guess_hcore
guess_huckel_c calls guess_huckel
guess_json_c calls guess_json
hf_energy calls scf_driver