orthogonal_transform_sym – OPENQP
orthogonal_transform_sym Subroutine
24 statements
Source File
public subroutine orthogonal_transform_sym(n, m, a, u, ldu, b)
Uses
messages
@brief Compute orthogonal transformation of a symmetric marix A in packed format: B = U^T * A * U @param[in] a Matrix to transform @param[in] u Orthogonal matrix U(ldu,m) @param[in] n dimension of matrix A @param[in] m dimension of matrix B @param[in] ldu leading dimension of matrix U @param[out] b Result @param[inout] wrk Scratch space @author Vladimir Mironov
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
integer, intent(in) :: m
real(kind=8), intent(in) :: a(*)
real(kind=8), intent(in) :: u(n,*)
integer, intent(in) :: ldu
real(kind=8), intent(out) :: b(*)
Calls
Called by
Call graph
orthogonal_transform_sym calls show_message, oqp_dgemm_i64, oqp_dsymm_i64, oqp_dtpttr_i64, oqp_dtrttp_i64
oqp_dgemm_i64 calls show_message, dgemm
oqp_dsymm_i64 calls show_message, dsymm
oqp_dtpttr_i64 calls show_message, dtpttr
oqp_dtrttp_i64 calls show_message, dtrttp
eijden calls orthogonal_transform_sym
form_rohf_fock calls orthogonal_transform_sym
huckel_guess calls orthogonal_transform_sym
tdhf_mrsf_energy calls orthogonal_transform_sym
tdhf_sf_energy calls orthogonal_transform_sym
guess_huckel calls huckel_guess
hf_gradient calls eijden
scf_driver calls form_rohf_fock
tdhf_1e_grad calls eijden
tdhf_mrsf_energy_c calls tdhf_mrsf_energy
tdhf_sf_energy_c calls tdhf_sf_energy
guess_huckel_c calls guess_huckel
hf_energy calls scf_driver
tdhf_gradient calls tdhf_1e_grad
tdhf_gradient_c calls tdhf_gradient