orthogonal_transform2 – OPENQP
orthogonal_transform2 Subroutine
20 statements
Source File
public subroutine orthogonal_transform2(trans, m, n, u, ldu, a, lda, b, ldb, wrk)
Uses
messages
@brief Compute orthogonal transformation of a square marix @param[in] trans If trans='n' compute B = U^T * A * U If trans='t' compute B = U * A * U^T @param[in] ld Dimension of matrices @param[in] u Square orthogonal matrix @param[in] a Matrix to transform @param[out] b Result @param[inout] wrk Scratch space @author Vladimir Mironov
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: trans
integer :: m
integer :: n
real(kind=dp), intent(in) :: u(*)
integer :: ldu
real(kind=dp), intent(in) :: a(*)
integer :: lda
real(kind=dp), intent(out) :: b(*)
integer :: ldb
real(kind=dp), intent(inout) :: wrk(*)
Calls
Called by
Call graph
orthogonal_transform2 calls show_message, oqp_dgemm_i64
oqp_dgemm_i64 calls show_message, dgemm
form_rohf_fock calls orthogonal_transform2
scf_driver calls form_rohf_fock
hf_energy calls scf_driver