orthogonal_transform – OPENQP
orthogonal_transform Subroutine
36 statements
Source File
public subroutine orthogonal_transform(trans, ld, u, a, b, wrk)
Uses
messages
@brief Compute orthogonal transformation of a square marix @param[in] trans If trans='n' compute B = U^T * A * U If trans='t' compute B = U * A * U^T @param[in] ld Dimension of matrices @param[in] u Square orthogonal matrix @param[inout] a Matrix to transform, optionally output matrix @param[out] b Result, can be absent for in-place transform of matrix A @param[inout] wrk Scratch space, optional @author Vladimir Mironov
Arguments
Type Intent Optional Attributes Name
character(len=1), intent(in) :: trans
integer :: ld
real(kind=dp), intent(in) :: u(*)
real(kind=dp), intent(in) :: a(*)
real(kind=dp), intent(out), optional :: b(*)
real(kind=dp), intent(inout), optional, target :: wrk(*)
Calls
Called by
Call graph
orthogonal_transform calls show_message, oqp_dgemm_i64
oqp_dgemm_i64 calls show_message, dgemm
get_ab_initio_orbital calls orthogonal_transform
get_td_transition_dipole calls orthogonal_transform
get_transition_dipole calls orthogonal_transform
oqp_tdhf_z_vector calls orthogonal_transform, tdhf_unrelaxed_density
sfdmat calls orthogonal_transform
tdhf_energy calls orthogonal_transform, get_td_transition_dipole
tdhf_gradient calls orthogonal_transform
tdhf_mrsf_energy calls orthogonal_transform, get_transition_dipole
tdhf_unrelaxed_density calls orthogonal_transform
guess_hcore calls get_ab_initio_orbital
scf_driver calls get_ab_initio_orbital
tdhf_energy_c calls tdhf_energy
tdhf_gradient_c calls tdhf_gradient
tdhf_mrsf_energy_c calls tdhf_mrsf_energy
tdhf_sf_energy calls get_transition_dipole, sfdmat
tdhf_z_vector_c calls oqp_tdhf_z_vector
guess_hcore_c calls guess_hcore
hf_energy calls scf_driver
tdhf_sf_energy_c calls tdhf_sf_energy