overlap – OPENQP
overlap Subroutine
23 statements
Source File
public subroutine overlap(s, basis, tol)
@brief Compute overlap and integrals @details Overlap integrals are computed using Gauss-Hermite quadrature formula @author Vladimir Mironov @date Mar, 2023 Initial release
@param[in,out] s packed matrix of overlap integrals @param[in] basis basis w/ SP-shells separated @param[in] tol 1-e exponential prefactor tolerance
Arguments
Type Intent Optional Attributes Name
real(kind=REAL64), intent(inout), CONTIGUOUS :: s(:)
type(basis_set), intent(in) :: basis
real(kind=REAL64), intent(in) :: tol
Calls
Called by
Call graph
overlap calls alloc, fetch_by_id, shell_pair, comp_kin_ovl_int1_prim, update_triang_matrix
comp_kin_ovl_int1_prim calls doquadgausshermite
doquadgausshermite calls abrt
huckel_guess calls overlap
guess_huckel calls huckel_guess
guess_huckel_c calls guess_huckel