PACK_F90 – OPENQP
PACK_F90 Subroutine
12 statements
Source File
public subroutine PACK_F90(A, AP, UPLO)
@brief Fortran-90 routine for packing symmetric matrix to 1D array
@date 6 October 2021 - Initial release - @author Igor S. Gerasimov
@param[in] A - matrix for packing (N x N) @param[out] AP - packed matrix (N*(N+1)/2) @param[in,optional] UPLO - format of packed matrix, U for upper and L for lower
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: A(:,:)
real(kind=dp), intent(out) :: AP(:)
character(len=1), intent(in), optional :: UPLO
Calls
Called by
Source Code
  subroutine PACK_F90(A, AP, UPLO)
    real(dp), intent(IN) :: A(:, :)
    real(dp), intent(OUT) :: AP(:)
    character(len=1), intent(in), optional :: UPLO
    character(len=1) :: DUPLO
    if (.not. present(UPLO)) then
      DUPLO = 'U'
    else
      DUPLO = UPLO
    end if
    call PACK_F77(A, size(A, 1), AP, DUPLO)
  end subroutine PACK_F90
Call graph
pack_f90 calls show_message, oqp_dtrttp_i64
oqp_dtrttp_i64 calls show_message, dtrttp
pack_matrix calls pack_f90
build_pfon_density calls pack_matrix
form_rohf_fock calls pack_matrix
get_spin_square calls pack_matrix
get_td_transition_dipole calls pack_matrix
get_transition_dipole calls pack_matrix
mo_to_ao calls pack_matrix
oqp_tdhf_z_vector calls pack_matrix, tdhf_unrelaxed_density
orb_to_dens calls pack_matrix
sfdmat calls pack_matrix
tdhf_unrelaxed_density calls pack_matrix
get_ab_initio_density calls orb_to_dens
scf_driver calls add_data, build_pfon_density, form_rohf_fock, mo_to_ao, get_ab_initio_density
tdhf_energy calls get_td_transition_dipole
tdhf_mrsf_energy calls get_transition_dipole
tdhf_sf_energy calls get_spin_square, get_transition_dipole, sfdmat
tdhf_z_vector_c calls oqp_tdhf_z_vector
guess_hcore calls get_ab_initio_density
guess_huckel calls get_ab_initio_density
guess_json calls get_ab_initio_density
hf_energy calls scf_driver
tdhf_energy_c calls tdhf_energy
tdhf_mrsf_energy_c calls tdhf_mrsf_energy
tdhf_sf_energy_c calls tdhf_sf_energy
guess_hcore_c calls guess_hcore
guess_huckel_c calls guess_huckel
guess_json_c calls guess_json