pcg_optimize – OPENQP
pcg_optimize Subroutine
37 statements
Source File
public subroutine pcg_optimize(b, update, precond, dat, mxit, x0, tol, err, cgiters)
Uses
messages
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: b(:)
procedure(pcg_matvec) :: update
procedure(pcg_matvec) :: precond
type(*), intent(in) :: dat
integer, intent(in) :: mxit
real(kind=dp), intent(in), optional :: x0(:)
real(kind=dp), intent(in) :: tol
real(kind=dp), intent(out), optional :: err
real(kind=dp), intent(out), optional :: cgiters
Calls
Call graph
pcg_optimize calls show_message, init, step