print_sym_labeled – OPENQP
print_sym_labeled Subroutine
22 statements
Source File
public subroutine print_sym_labeled(d, n, basis)
Uses
io_constants
basis_tools
precision
@brief Print symmetric packed matrix d of dimension n @detail The rows will be labeled with basis function tags
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: d(*)
integer, intent(in) :: n
type(basis_set), intent(in) :: basis
Calls
Called by
Source Code
  subroutine print_sym_labeled(d, n, basis)
    use precision, only: dp
    use io_constants, only: iw
    use basis_tools, only: basis_set
    implicit none
    real(kind=dp), intent(in) :: d(*)
    integer, intent(in) :: n
    type(basis_set), intent(in) :: basis
    integer, parameter :: maxcolumns = 5
    integer :: i0, ila, i, j0, j1
    do i0 = 1, n, maxcolumns
      write(iw, '(/,15x,*(4x,i4,3x))') (i, i=i0, min(n, i0+maxcolumns-1))
      write(iw,'(G0)')
      ila = 0
      do i = i0, n
        j0 = i0 + i*(i-1)/2
        j1 = j0 + min(ila, maxcolumns-1)
        write (iw,'(i5,2x,a8,*(f11.6))') i, basis%bf_label(i), d(j0:j1)
        ila = ila + 1
      end do
    end do
  end subroutine print_sym_labeled
Call graph
print_sym_labeled calls bf_label
int1e calls print_sym_labeled, omp_hst
multipole_integrals calls print_sym_labeled
omp_hst calls print_sym_labeled
electric_moments calls multipole_integrals
get_td_transition_dipole calls multipole_integrals
get_transition_dipole calls multipole_integrals
tdhf_energy calls get_td_transition_dipole
tdhf_mrsf_energy calls get_transition_dipole
tdhf_sf_energy calls get_transition_dipole
tdhf_energy_c calls tdhf_energy
tdhf_mrsf_energy_c calls tdhf_mrsf_energy
tdhf_sf_energy_c calls tdhf_sf_energy