print_module_info – OPENQP
print_module_info Subroutine
6 statements
Source File
public subroutine print_module_info(module_title, module_info)
Uses
io_constants
@brief Print MODULE information @detail Printout the information of each MODULES of OQP
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: module_title
character(len=*), intent(in) :: module_info
Called by
Source Code
  subroutine print_module_info(module_title,module_info)
    use io_constants, only: iw
    implicit none
    character(len=*), intent(in) :: module_title, module_info
    write(iw,'(/20x,40("+")/&
             &23X,"MODULE: ",A/&
             &23X,A/&
             &20X,40("+"))') module_title, module_info
  end subroutine print_module_info
Call graph
guess_hcore calls print_module_info
guess_huckel calls print_module_info
guess_json calls print_module_info
hf_energy calls print_module_info
hf_gradient calls print_module_info
int1e calls print_module_info
oqp_tdhf_z_vector calls print_module_info
tdhf_energy calls print_module_info
tdhf_gradient calls print_module_info
tdhf_mrsf_energy calls print_module_info
tdhf_sf_energy calls print_module_info
guess_hcore_c calls guess_hcore
guess_huckel_c calls guess_huckel
guess_json_c calls guess_json
tdhf_energy_c calls tdhf_energy
tdhf_gradient_c calls tdhf_gradient
tdhf_mrsf_energy_c calls tdhf_mrsf_energy
tdhf_sf_energy_c calls tdhf_sf_energy
tdhf_z_vector_c calls oqp_tdhf_z_vector