print_mo_range – OPENQP
print_mo_range Subroutine
14 statements
Source File
public subroutine print_mo_range(basis, infos, mostart, moend)
Uses
io_constants
basis_tools
types
@brief Printing out MOs
Arguments
Type Intent Optional Attributes Name
type(basis_set), intent(in) :: basis
type(information), intent(inout) :: infos
integer, intent(in) :: mostart
integer, intent(in) :: moend
Calls
Called by
Source Code
  subroutine print_mo_range(basis, infos, mostart, moend)
    use io_constants, only: iw
    use types, only: information
    use basis_tools, only: basis_set
    implicit none
    type(basis_set), intent(in) :: basis
    type(information), intent(inout) :: infos
    integer, intent(in) :: mostart, moend
    integer :: mo0, mo1
    write (iw,fmt="(/&
            &10x, 31('=')/&
            &10x, 'Molecular Orbitals and Energies'/&
            &10x, 31('='))")
    mo0 = max(mostart, 1)
    mo1 = min(moend, basis%nbf)
    call print_eigvec_vals_labeled(basis, infos, mo0, mo1)
  end subroutine print_mo_range
Call graph
print_mo_range calls print_eigvec_vals_labeled
print_eigvec_vals_labeled calls data_has_tags, tagarray_get_data, bf_label
scf_driver calls print_mo_range
hf_energy calls scf_driver