reordermos – OPENQP
reordermos Subroutine
52 statements
Source File
public subroutine reordermos(V, E, Smo, l0, nbf, lr1, lr2)
Uses
precision
@brief This routine reorders orbitals to maximum overlap.
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout), dimension(nbf,*) :: V
real(kind=dp), intent(in), dimension(*) :: E
real(kind=dp), intent(in), dimension(l0,*) :: Smo
integer :: l0
integer :: nbf
integer :: lr1
integer :: lr2
Calls
Called by
Call graph
reordermos calls dswap
mo_reorder calls reordermos
scf_driver calls mo_reorder
hf_energy calls scf_driver