resp_charges_C – OPENQP
resp_charges_C Subroutine
9 statements
Source File
public subroutine resp_charges_C(c_handle) bind(C, name="resp_charges")
Uses
c_interop
strings
types
@brief Compute ESP charges fitted by modified Merz-Kollman method @details This is a C interface for a Fortran subroutine
@param[in] c_handle OQP handle @author Vladimir Mironov @date Mar, 2023 Initial release
Arguments
Type Intent Optional Attributes Name
type(oqp_handle_t) :: c_handle
Calls
Source Code
  subroutine resp_charges_C(c_handle) bind(C, name="resp_charges")
    use c_interop, only: oqp_handle_t, oqp_handle_get_info, oqp_handle_refresh_ptr
    use strings, only: Cstring
    use types, only: information
    type(oqp_handle_t) :: c_handle
    type(information), pointer :: inf
    inf => oqp_handle_get_info(c_handle)
    call oqp_resp_charges(inf)
  end subroutine resp_charges_C
Call graph
resp_charges_c calls oqp_handle_get_info, oqp_resp_charges
oqp_resp_charges calls data_has_tags, show_message, tagarray_get_data, electrostatic_potential, lebedev_get_grid, oqp_dgemm_i64, oqp_dgemv_i64, oqp_dgesv_i64
electrostatic_potential calls bas_denorm_matrix, bas_norm_matrix, alloc, fetch_by_id, shell_pair, comp_coulpot_prim, density_ordered
lebedev_get_grid calls show_message
oqp_dgemm_i64 calls show_message, dgemm
oqp_dgemv_i64 calls show_message, dgemv
oqp_dgesv_i64 calls show_message, dgesv
comp_coulpot_prim calls evaluate