run_population_analysis – OPENQP
run_population_analysis Subroutine
45 statements
Source File
public subroutine run_population_analysis(infos, basis, orbital_pop, chg, sel)
Uses
messages
oqp_tagarray_driver
precision
types
mathlib
basis_tools
@brief Run population analysis
@param[in] infos QOP handle, fortran @param[in] basis basis set @param[out] orbital_pop AO population @param[out] chg atomic partial charges @param[in] sel Mulliken(0) or Lowdin(1) analysis selector @author Vladimir Mironov @date Mar, 2023 Initial release
Arguments
Type Intent Optional Attributes Name
type(information), intent(inout) :: infos
type(basis_set), intent(in) :: basis
real(kind=dp), intent(inout), allocatable :: orbital_pop(:)
real(kind=dp), intent(inout), allocatable :: chg(:)
integer, intent(in) :: sel
Calls
Called by
Call graph
run_population_analysis calls data_has_tags, show_message, tagarray_get_data, unpack_matrix, diag_symm_packed, oqp_dgemm_i64
unpack_matrix calls unpack_f90
diag_symm_packed calls show_message, dspev, dspevx
oqp_dgemm_i64 calls show_message, dgemm
unpack_f90 calls show_message, oqp_dtpttr_i64
oqp_dtpttr_i64 calls show_message, dtpttr
lowdin calls run_population_analysis
mulliken calls run_population_analysis