run_xc – OPENQP
run_xc Subroutine
72 statements
Source File
public subroutine run_xc(xc_opts, xc_dat, basis)
Uses
basis_tools
Arguments
Type Intent Optional Attributes Name
type(xc_options_t), intent(in) :: xc_opts
class(xc_consumer_t), intent(inout) :: xc_dat
type(basis_set), intent(in) :: basis
Calls
Called by
Call graph
run_xc calls allreduce, compaos, compxc, getslicenonzero, getstats, init, pruneaos, resetpointers, parallel_start, parallel_stop, postUpdate, update
compute calls calc_evfxc, calc_evxc, calc_xc, scalexc
init calls clean, resetenergy
mo_tran_gemm_ calls oqp_dgemm_i64
mo_tran_symm_ calls oqp_dsymm_i64
oqp_dgemm_i64 calls show_message, dgemm
oqp_dsymm_i64 calls show_message, dsymm
derexc_blk calls run_xc
dmatd_blk calls run_xc
tddft_fxc calls run_xc
tddft_gxc calls run_xc
tddft_xc_gradient calls run_xc
utddft_fxc calls run_xc
utddft_xc_gradient calls run_xc
dftder calls derexc_blk
dftexcor calls dmatd_blk
oqp_tdhf_z_vector calls tddft_fxc, tddft_gxc
tdhf_energy calls tddft_fxc
tdhf_gradient calls tddft_xc_gradient
hf_gradient calls dftder
scf_driver calls dftexcor
tdhf_energy_c calls tdhf_energy
tdhf_gradient_c calls tdhf_gradient
tdhf_z_vector_c calls oqp_tdhf_z_vector
hf_energy calls scf_driver