rys_print_eri – OPENQP
rys_print_eri Subroutine
30 statements
Source File
public subroutine rys_print_eri(gdat, ints)
Uses
constants
Arguments
Type Intent Optional Attributes Name
type(int2_rys_data_t), intent(in) :: gdat
real(kind=dp), intent(in) :: ints(:,:,:,:)
Called by
Call graph
fock_jk calls run
oqp_tdhf_z_vector calls run
scf_driver calls run
tdhf_energy calls run
tdhf_mrsf_energy calls run
tdhf_sf_energy calls run
hf_energy calls scf_driver
tdhf_energy_c calls tdhf_energy
tdhf_mrsf_energy_c calls tdhf_mrsf_energy
tdhf_sf_energy_c calls tdhf_sf_energy
tdhf_z_vector_c calls oqp_tdhf_z_vector