set_bragg_slater – OPENQP
set_bragg_slater Subroutine
14 statements
Source File
public subroutine set_bragg_slater(array, bstype)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(out) :: array(:)
integer, intent(in) :: bstype
Called by
Call graph
dft_initialize calls set_bragg_slater
hf_energy calls dft_initialize
hf_gradient calls dft_initialize
oqp_tdhf_z_vector calls dft_initialize
tdhf_energy calls dft_initialize
tdhf_gradient calls dft_initialize
tdhf_energy_c calls tdhf_energy
tdhf_gradient_c calls tdhf_gradient
tdhf_z_vector_c calls oqp_tdhf_z_vector