solve_linear_equations – OPENQP
solve_linear_equations Subroutine
22 statements
Source File
public subroutine solve_linear_equations(a, b, n, nrhs, lda, ierr)
Uses
precision
messages
@brief Compute the solution to a real system of linear equations A * X = B @detai Wrapper for DSYSV from Lapack @param[in,out] A general matrix, destroyed on exit. @param[in,out] B RHS on entry. The solution on exit. @param[in] n size of the problem. @param[in] nrhs number of RHS vectors @param[in] lda leading dimension of matrix A @param[out] ierr Error flag, ierr=0 if no errors. Read DSYEV manual for details
Arguments
Type Intent Optional Attributes Name
real(kind=dp) :: a(*)
real(kind=dp) :: b(*)
integer, intent(in) :: n
integer, intent(in) :: nrhs
integer, intent(in) :: lda
integer, intent(inout) :: ierr
Calls
Call graph
solve_linear_equations calls show_message, oqp_dsysv_i64
oqp_dsysv_i64 calls show_message, dsysv