symmetrize_matrix – OPENQP
symmetrize_matrix Subroutine
10 statements
Source File
public subroutine symmetrize_matrix(a, n)
Uses
precision
@brief Compute A = A + A^T of a square matrix @param[inout] a square NxN matrix @param[in] n matrix dimension
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: a(n,*)
integer, intent(in) :: n
Called by
Source Code
  subroutine symmetrize_matrix(a,n)
    use precision, only: dp
    real(kind=dp), intent(inout) :: a(n,*)
    integer, intent(in) :: n
    integer :: i
    do i = 1, n
      a(i:n,i) = a(i:n,i) + a(i,i:n)
      a(1:i-1,i) = a(i,1:i-1)
    end do
  end subroutine symmetrize_matrix
Call graph
get_spin_square calls symmetrize_matrix
get_td_transition_dipole calls symmetrize_matrix
get_transition_dipole calls symmetrize_matrix
int2_td_data_t_parallel_stop calls symmetrize_matrix
oqp_tdhf_z_vector calls symmetrize_matrix
symmetrize_matrices calls symmetrize_matrix
tdhf_energy calls symmetrize_matrix, get_td_transition_dipole
tdhf_gradient calls symmetrize_matrix
int2_rpagrd_data_t_parallel_stop calls symmetrize_matrices
tdhf_energy_c calls tdhf_energy
tdhf_gradient_c calls tdhf_gradient
tdhf_mrsf_energy calls get_transition_dipole
tdhf_sf_energy calls get_spin_square, get_transition_dipole
tdhf_z_vector_c calls oqp_tdhf_z_vector
tdhf_mrsf_energy_c calls tdhf_mrsf_energy
tdhf_sf_energy_c calls tdhf_sf_energy