tddft_gxc – OPENQP
tddft_gxc Subroutine
71 statements
Source File
public subroutine tddft_gxc(basis, molGrid, isVecs, wf, fx, dx, nMtx, threshold, infos)
Uses
mod_dft_gridint
types
mathlib
basis_tools
mod_dft_molgrid
@brief Compute derivative XC contribution to the TD-DFT KS-like matrices @param[in] basis basis set @param[in] isVecs .true. if orbitals are provided instead of density matrix @param[in] wf density matrix/orbitals @param[inout] fx fock-like matrices @param[inout] dx densities @param[in] nMtx number of density/Fock-like matrices @param[in] threshold tolerance @param[in] infos OQP metadata @author Vladimir Mironov
Arguments
Type Intent Optional Attributes Name
type(basis_set) :: basis
type(dft_grid_t), intent(in), target :: molGrid
logical, intent(in) :: isVecs
real(kind=fp), intent(in) :: wf(:,:)
real(kind=fp), intent(inout) :: fx(:,:,:)
real(kind=fp), intent(inout), target :: dx(:,:,:)
integer, intent(in) :: nMtx
real(kind=fp), intent(in) :: threshold
type(information), intent(in), target :: infos
Calls
Called by
Call graph
tddft_gxc calls clean, init, run_xc, triangular_to_full
run_xc calls allreduce, compaos, compxc, getslicenonzero, getstats, init, pruneaos, resetpointers, parallel_start, parallel_stop, postUpdate, update
triangular_to_full calls show_message
compute calls calc_evfxc, calc_evxc, calc_xc, scalexc
init calls clean, resetenergy
mo_tran_gemm_ calls oqp_dgemm_i64
mo_tran_symm_ calls oqp_dsymm_i64
oqp_dgemm_i64 calls show_message, dgemm
oqp_dsymm_i64 calls show_message, dsymm
oqp_tdhf_z_vector calls tddft_gxc
tdhf_z_vector_c calls oqp_tdhf_z_vector