tdhf_1e_grad – OPENQP
tdhf_1e_grad Subroutine
41 statements
Source File
public subroutine tdhf_1e_grad(infos, basis)
Uses
messages
oqp_tagarray_driver
precision
types
util
constants
mathlib
basis_tools
grd1
Arguments
Type Intent Optional Attributes Name
type(information), intent(inout) :: infos
type(basis_set), intent(inout) :: basis
Calls
Called by
Call graph
tdhf_1e_grad calls data_has_tags, show_message, tagarray_get_data, eijden, grad_1e_ecp, grad_ee_kinetic, grad_ee_overlap, grad_en_hellman_feynman, grad_en_pulay, grad_nn
eijden calls data_has_tags, tagarray_get_data, unpack_matrix, orthogonal_transform_sym
grad_1e_ecp calls bcast, init, add_ecpder
grad_ee_kinetic calls bas_norm_matrix, unpack_matrix, alloc, fetch_by_id, shell_pair, comp_kinetic_der1
grad_ee_overlap calls bas_norm_matrix, unpack_matrix, alloc, fetch_by_id, shell_pair, comp_overlap_der1
grad_en_hellman_feynman calls bas_norm_matrix, unpack_matrix, alloc, fetch_by_id, shell_pair, comp_coulomb_helfeyder1
grad_en_pulay calls bas_norm_matrix, unpack_matrix, alloc, fetch_by_id, shell_pair, comp_coulomb_der1
unpack_matrix calls unpack_f90
add_ecpder calls compute_first_derivs, free_integrator, free_result, init_integrator, init_integrator_instance, set_ecp_basis, bf_to_shell
comp_coulomb_der1 calls evaluate
comp_coulomb_helfeyder1 calls evaluate
comp_kinetic_der1 calls doquadgausshermite
comp_overlap_der1 calls doquadgausshermite
orthogonal_transform_sym calls show_message, oqp_dgemm_i64, oqp_dsymm_i64, oqp_dtpttr_i64, oqp_dtrttp_i64
doquadgausshermite calls abrt
oqp_dgemm_i64 calls show_message, dgemm
oqp_dsymm_i64 calls show_message, dsymm
oqp_dtpttr_i64 calls show_message, dtpttr
oqp_dtrttp_i64 calls show_message, dtrttp
unpack_f90 calls show_message, oqp_dtpttr_i64
tdhf_gradient calls tdhf_1e_grad
tdhf_gradient_c calls tdhf_gradient