tdhf_gradient – OPENQP
tdhf_gradient Subroutine
74 statements
Source File
public subroutine tdhf_gradient(infos)
Uses
dft
printing
tdhf_lib
oqp_tagarray_driver
messages
mod_dft_gridint_tdxc_grad
types
util
mathlib
io_constants
basis_tools
mod_dft_molgrid
strings
grd1
Arguments
Type Intent Optional Attributes Name
type(information), intent(inout), target :: infos
Calls
Called by
Source Code
  subroutine tdhf_gradient(infos)
    use io_constants, only: iw
    use oqp_tagarray_driver
    use types, only: information
    use strings, only: Cstring, fstring
    use basis_tools, only: basis_set
    use messages, only: show_message, with_abort
    use grd1, only: eijden, print_gradient
    use util, only: measure_time
    use tdhf_lib, only: &
      iatogen, mntoia
    use dft, only: dft_initialize, dftclean
    use mathlib, only: symmetrize_matrix, orthogonal_transform
    use mod_dft_molgrid, only: dft_grid_t
    use mod_dft_gridint_tdxc_grad, only: tddft_xc_gradient
    use mathlib, only: unpack_matrix
    use printing, only: print_module_info
    implicit none
    character(len=*), parameter :: subroutine_name = "tdhf_gradient"
    type(basis_set), pointer :: basis
    type(information), target, intent(inout) :: infos
    integer :: nbf, nocc
    type(dft_grid_t) :: molGrid
  ! General data
    logical :: dft
    integer :: scf_type, mol_mult
    real(kind=dp), allocatable :: p(:,:,:), d(:,:,:), xpy2(:,:,:), xmy2(:,:,:), wrk1(:,:), wrk2(:,:)
    ! tagarray
    real(kind=dp), contiguous, pointer :: &
      dmat_a(:), mo_a(:,:), td_p(:,:), xpy(:), xmy(:)
    character(len=*), parameter :: tags_general(*) = [ character(len=80) :: &
      OQP_TD_XPY, OQP_TD_XMY, OQP_DM_A, OQP_VEC_MO_A, OQP_TD_P ]
    mol_mult = infos%mol_prop%mult
    if (mol_mult/=1) call show_message(&
            'RPA-TDDFT are only available for RHF reference', with_abort)
    scf_type = infos%control%scftype
    if (scf_type/=1) error stop
    dft = infos%control%hamilton == 20
  ! Files open
    open (unit=IW, file=infos%log_filename, position="append")
  !
    call print_module_info('TDHF_Grad','Computing Grdient of TDDFT')
!
    write(iw,'(/5X,"Gradient options"/&
                &5X,18("-")/&
                &5X,"Target State: ",I8/)') infos%tddft%target_state
   ! Load basis set
    basis => infos%basis
    basis%atoms => infos%atoms
    call data_has_tags(infos%dat, tags_general, module_name, subroutine_name, WITH_ABORT)
    call tagarray_get_data(infos%dat, OQP_DM_A, dmat_a)
    call tagarray_get_data(infos%dat, OQP_VEC_MO_A, mo_a)
    call tagarray_get_data(infos%dat, OQP_td_p, td_p)
    call tagarray_get_data(infos%dat, OQP_td_xpy, xpy)
    call tagarray_get_data(infos%dat, OQP_td_xmy, xmy)
  ! Allocate H, S ,T and D matrices
    nbf = basis%nbf
    nocc = infos%mol_prop%nocc
!   Compute 1e gradient
    call flush(iw)
    call tdhf_1e_grad(infos, basis)
    !call print_gradient(infos)
    write(iw,"(' ..... End Of 1-Eelectron Gradient ......')")
    call measure_time(print_total=1, log_unit=iw)
    call flush(iw)
    allocate(d(nbf,nbf,2), &
             p(nbf,nbf,2), &
             xpy2(nbf,nbf,2), &
             xmy2(nbf,nbf,2), &
             wrk1(nbf,nbf), &
             wrk2(nbf,nbf), &
             source=0.0d0)
    call iatogen(xpy, wrk1, nocc, nocc)
    call symmetrize_matrix(wrk1, nbf)
    wrk1 = wrk1*0.5
    call orthogonal_transform('t', nbf, mo_a, wrk1, xpy2(:,:,1), wrk2)
    call iatogen(xmy, wrk1, nocc, nocc)
    call orthogonal_transform('t', nbf, mo_a, wrk1, xmy2(:,:,1), wrk2)
    call unpack_matrix(td_p(:,1), p(:,:,1))
    call unpack_matrix(dmat_a, d(:,:,1))
!   Compute xc gradient
    if (dft) then
      call dft_initialize(infos, basis, molGrid)
      d(:,:,2) = d(:,:,1)
      p(:,:,2) = p(:,:,1)
      xpy2(:,:,2) = xpy2(:,:,1)
      call tddft_xc_gradient(basis=basis, &
             molGrid=molGrid, &
             dedft=infos%atoms%grad, &
             da=d(:,:,1), &
             pa=p(:,:,1:1), &
             xa=xpy2(:,:,1:1), &
             nmtx=1, &
             threshold=1.0d-14, &
             infos=infos)
      call dftclean(infos)
      call measure_time(print_total=1, log_unit=iw)
      call flush(iw)
    end if
!   Compute 2e gradient
    call tdhf_2e_grad(basis, infos, d(:,:,1:1), p(:,:,1:1), xpy2(:,:,1:1), xmy2(:,:,1:1))
    call print_gradient(infos)
!   Print timings
    call measure_time(print_total=1, log_unit=iw)
    close(iw)
  end subroutine tdhf_gradient
Call graph
tdhf_gradient calls data_has_tags, show_message, tagarray_get_data, unpack_matrix, dft_initialize, dftclean, iatogen, measure_time, orthogonal_transform, print_gradient, print_module_info, symmetrize_matrix, tddft_xc_gradient, tdhf_1e_grad, tdhf_2e_grad
unpack_matrix calls unpack_f90
dft_initialize calls show_message, add_atomic_grid, add_grid, compress, find_neighbours, reset, set_screening, c_f_char, dft_fc_blk, get_radial_grid, libxc_input, set_bragg_slater
dftclean calls libxc_destroy
orthogonal_transform calls show_message, oqp_dgemm_i64
tddft_xc_gradient calls clean, init, run_xc
tdhf_1e_grad calls data_has_tags, show_message, tagarray_get_data, eijden, grad_1e_ecp, grad_ee_kinetic, grad_ee_overlap, grad_en_hellman_feynman, grad_en_pulay, grad_nn
tdhf_2e_grad calls show_message, clean, init, grd2_driver
dft_fc_blk calls getbyid, set
eijden calls data_has_tags, tagarray_get_data, unpack_matrix, orthogonal_transform_sym
get_radial_grid calls set, transform
grad_1e_ecp calls init, bcast, add_ecpder
grad_ee_kinetic calls unpack_matrix, bas_norm_matrix, alloc, fetch_by_id, shell_pair, comp_kinetic_der1
grad_ee_overlap calls unpack_matrix, bas_norm_matrix, alloc, fetch_by_id, shell_pair, comp_overlap_der1
grad_en_hellman_feynman calls unpack_matrix, bas_norm_matrix, alloc, fetch_by_id, shell_pair, comp_coulomb_helfeyder1
grad_en_pulay calls unpack_matrix, bas_norm_matrix, alloc, fetch_by_id, shell_pair, comp_coulomb_der1
grd2_driver calls show_message, init, get_density, alloc, allreduce, clean, compute, set, set_ids, grd2_rys_compute, ints_exchange
libxc_destroy calls destroy
libxc_input calls show_message, add_functional, can_calculate, xc_f03_reference, xc_f03_reference_doi, xc_f03_version_string
oqp_dgemm_i64 calls show_message, dgemm
run_xc calls allreduce, compaos, compxc, getslicenonzero, getstats, init, pruneaos, resetpointers, parallel_start, parallel_stop, postUpdate, update
unpack_f90 calls show_message, oqp_dtpttr_i64
add_ecpder calls compute_first_derivs, free_integrator, free_result, init_integrator, init_integrator_instance, set_ecp_basis, bf_to_shell
comp_coulomb_der1 calls evaluate
comp_coulomb_helfeyder1 calls evaluate
comp_kinetic_der1 calls doquadgausshermite
comp_overlap_der1 calls doquadgausshermite
grd2_rys_compute calls evaluate
ints_exchange calls show_message, alloc, compute, set, libint2_cleanup_eri, libint2_init_eri, clean, init, set_ids, genr22, int2_rys_compute, libint_compute_eri
lebedev_get_grid calls show_message
oqp_dtpttr_i64 calls show_message, dtpttr
orthogonal_transform_sym calls show_message, oqp_dgemm_i64, oqp_dtpttr_i64, oqp_dsymm_i64, oqp_dtrttp_i64
compute calls calc_evfxc, calc_evxc, calc_xc, scalexc
doquadgausshermite calls abrt
genr22 calls fgrid, rfinc, rmr, xgrid
init calls clean, resetenergy
int2_rys_compute calls evaluate
libint_compute_eri calls ab_x, ab_y, ab_z, alpha1over_zetapluseta, alpha1rho_over_zeta2, alpha2over_zetapluseta, alpha2rho_over_zeta2, alpha3over_zetapluseta, alpha3rho_over_eta2, alpha4over_zetapluseta, alpha4rho_over_eta2, cd_x, cd_y, cd_z, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_0, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_1, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_10, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_11, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_12, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_13, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_14, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_15, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_16, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_17, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_18, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_19, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_2, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_20, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_3, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_4, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_5, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_6, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_7, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_8, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_9, fgrid, igrid, irgrd, oo2e, oo2z, oo2ze, pa_x, pa_y, pa_z, qc_x, qc_y, qc_z, rfinc, rho12_over_alpha1, rho12_over_alpha2, rho34_over_alpha3, rho34_over_alpha4, rmr, roe, roz, two_alpha0_bra, two_alpha0_ket, two_alpha1bra, two_alpha1ket, wp_x, wp_y, wp_z, wq_x, wq_y, wq_z
oqp_dsymm_i64 calls show_message, dsymm
oqp_dtrttp_i64 calls show_message, dtrttp
mo_tran_gemm_ calls oqp_dgemm_i64
mo_tran_symm_ calls oqp_dsymm_i64
tdhf_gradient_c calls tdhf_gradient