tdhf_energy – OPENQP
tdhf_energy Subroutine
186 statements
Source File
public subroutine tdhf_energy(infos)
Uses
dft
printing
int2_compute
tdhf_lib
oqp_tagarray_driver
messages
mod_dft_gridint_fxc
precision
types
util
mathlib
io_constants
basis_tools
mod_dft_molgrid
strings
Arguments
Type Intent Optional Attributes Name
type(information), intent(inout), target :: infos
Calls
Called by
Source Code
  subroutine tdhf_energy(infos)
    use io_constants, only: iw
    use oqp_tagarray_driver
    use types, only: information
    use strings, only: Cstring, fstring
    use basis_tools, only: basis_set
    use messages, only: show_message, with_abort
    use precision, only: dp
    use int2_compute, only: int2_compute_t
    use tdhf_lib, only: int2_td_data_t
    use tdhf_lib, only: &
      inivec, iatogen, mntoia, rparedms, rpaeig, rpavnorm, &
      rpaechk, rpaprint, rparesvec, rpaexpndv, rpanewb, esum, &
      tdhf_unrelaxed_density
    use dft, only: dft_initialize, dftclean
    use mod_dft_gridint_fxc, only: tddft_fxc
    use util, only: measure_time
    use mathlib, only: symmetrize_matrix, orthogonal_transform
    use mod_dft_molgrid, only: dft_grid_t
    use mathlib, only: unpack_matrix
    use printing, only: print_module_info
    implicit none
    character(len=*), parameter :: subroutine_name = "tdhf_energy"
    type(basis_set), pointer :: basis
    type(information), target, intent(inout) :: infos
    integer :: ok
    real(kind=dp), allocatable :: scr2(:)
    real(kind=dp), allocatable :: ab1_mo(:,:), ab2_mo(:,:), abxc(:,:), scr3(:,:)
    real(kind=dp), allocatable :: eex(:)
    real(kind=dp), allocatable :: abm_l(:,:), abp_r(:,:), amb(:,:), &
                                  apb(:,:), vlo(:,:), vro(:,:)
    real(kind=dp), allocatable, target :: vl(:), vr(:)
    real(kind=dp), pointer :: vl_p(:,:), vr_p(:,:)
    real(kind=dp), allocatable :: xm(:)
    real(kind=dp), allocatable :: bvec_mo(:,:)
    real(kind=dp), allocatable, target :: bvec(:,:,:)
    real(kind=dp), allocatable :: scr1(:,:)
    real(kind=dp), allocatable :: errors(:)
    real(kind=dp), pointer :: ab2(:,:,:)
    real(kind=dp), pointer :: ab1(:,:,:)
    real(kind=dp), allocatable :: dip(:,:)
    integer :: nocc, nvir
    integer :: nbf, nbf2, lexc
    integer :: ndsr, mxvec, nmax, ist, iend, nvec, novec
    integer :: iter, istart, nv, iv, ivec
    integer :: mxiter
    logical :: do_apb,do_amb, tamm_dancoff   ! SWITCH FOR a-b, a+b, tANDAMM COFF
    integer :: imax
    logical :: converged
    integer :: ierr
    real(kind=dp) :: mxerr, cnvtol, scale_exch, norm
    integer :: maxvec, nstates
    type(int2_compute_t) :: int2_driver
    type(int2_td_data_t), target :: int2_data
    type(dft_grid_t) :: molGrid
    logical :: dft
    ! tagarray
    real(kind=dp), contiguous, pointer :: &
      mo_energy_a(:), mo_a(:,:), td_t(:,:), &
      xpy(:,:), xmy(:,:), td_energies(:)
    character(len=*), parameter :: tags_alloc(4) = (/ character(len=80) :: &
      OQP_td_t, OQP_td_xpy, OQP_td_xmy, OQP_td_energies /)
    character(len=*), parameter :: tags_alpha(2) = (/ character(len=80) :: &
      OQP_E_MO_A, OQP_VEC_MO_A /)
    dft = infos%control%hamilton == 20
  ! Files open
  ! 3. LOG: Write: Main output file
    open (unit=IW, file=infos%log_filename, position="append")
  !
    call print_module_info('THDF_Energy','Computing Energy of TDDFT')
  ! Readings
  ! Load basis set
    basis => infos%basis
    basis%atoms => infos%atoms
  ! Allocate H, S ,T and D matrices
    nbf = basis%nbf
    nbf2 = nbf*(nbf+1)/2
    call data_has_tags(infos%dat, tags_alpha, module_name, subroutine_name, WITH_ABORT)
    call tagarray_get_data(infos%dat, OQP_E_MO_A, mo_energy_a)
    call tagarray_get_data(infos%dat, OQP_VEC_MO_A, mo_a)
    if (dft) call dft_initialize(infos, basis, molGrid, verbose=.true.)
    nstates = infos%tddft%nstate
    maxvec = infos%tddft%maxvec
    cnvtol = infos%tddft%cnvtol
    do_apb = .true.  ! Always do A+B part
    do_amb = .true.  ! = isGGA ! Do A-B part if a hybrid functional.
    tamm_dancoff = infos%tddft%tda  ! Tamm/Dancoff approximation
    nocc = infos%mol_prop%nocc
    nvir = nbf-nocc
    lexc = nocc*nvir
    mxvec = min(maxvec*nstates,lexc)
    nvec = min(nstates,mxvec)
    ndsr = nvec
    nmax = 2*nvec
    !nvec = 2*nvec
  ! Allocate TDDFT variables
    allocate(xm(lexc), &
             abxc(nbf,nbf), &
             bvec_mo(lexc,mxvec), &
             ab1_mo(lexc,mxvec), &
             ab2_mo(lexc,mxvec), &
             bvec(nbf,nbf,nmax), &
             eex(mxvec), &
             errors(mxvec), &
             apb(mxvec,mxvec), &
             amb(mxvec,mxvec), &
             vr(mxvec*mxvec), &
             vro(lexc,mxvec), &
             vl(mxvec*mxvec), &
             vlo(lexc,mxvec), &
             abp_r(lexc,mxvec), &
             abm_l(lexc,mxvec), &
             dip(3,nstates), &
             scr1(nbf,nbf), &
             scr2(mxvec*mxvec), &
             scr3(lexc,nmax), &
             source=0.0d0, &
             stat=ok)
    if( ok/=0 ) &
      call show_message('Cannot allocate memory', with_abort)
  ! Initialize ERI calculations
    call int2_driver%init(basis, infos)
    call int2_driver%set_screening()
    scale_exch = 1.0_dp
    if (dft) scale_exch = infos%dft%HFscale
  ! Construct TD trial vector
    call inivec(mo_energy_a,mo_energy_a,bvec_mo,xm,nocc,nocc,nvec)
    ist = 1
    istart = 1
    iend = nvec
    iter = 0
    mxiter = infos%control%maxit_dav
    ierr = 0
    do iter = 1, mxiter
      nv = iend-ist+1
!$omp parallel private(iv,scr1,abxc,ivec)
!$omp do schedule(static)
      do ivec = ist, iend
        iv = ivec-ist+1
        call iatogen(bvec_mo(:,ivec),abxc,nocc,nocc)
        call orthogonal_transform('t', nbf, mo_a, abxc, bvec(:,:,iv), scr1)
      end do
!$omp end do
!$omp end parallel
      int2_data = int2_td_data_t(d2=bvec(:,:,:nv), &
              int_apb=do_apb, int_amb=do_amb, tamm_dancoff=tamm_dancoff, &
              tamm_dancoff_coulomb=.true., &
              scale_exchange=scale_exch)
      call int2_driver%run(int2_data, &
                cam=dft.and.infos%dft%cam_flag, &
                alpha=infos%dft%cam_alpha, &
                beta=infos%dft%cam_beta,&
                mu=infos%dft%cam_mu)
      ab1 => int2_data%apb(:,:,:,1)
      ab2 => int2_data%amb(:,:,:,1)
      if (dft) then
        do ivec = ist, iend
          iv = ivec-ist+1
          call symmetrize_matrix(bvec(:,:,iv), nbf)
        end do
        call tddft_fxc(basis=basis, &
               molGrid=molGrid, &
               isVecs=.true., &
               wf=mo_a, &
               fx=ab1(:,:,:iv), &
               dx=bvec(:,:,:iv), &
               nmtx=iv, &
               !threshold=1.0d-15, &
               threshold=0.0d0, &
               infos=infos)
      end if
!$omp parallel private(iv,ivec)
!$omp do schedule(static)
      do ivec = ist, iend
        iv = ivec-ist+1
  !     Convert AO to MO basis
        if (tamm_dancoff) then
          ab1(:,:,iv) = 0.5_dp*ab1(:,:,iv) + ab2(:,:,iv)
        end if
        call mntoia(ab1(:,:,iv), ab1_mo(:,ivec), mo_a, mo_a, nocc, nocc)
  !     Product (A+B)*X
        call esum(mo_energy_a,ab1_mo,bvec_mo,nocc,ivec)
        if (.not.tamm_dancoff) then
!         Product (A-B)*X
          call mntoia(ab2(:,:,iv),ab2_mo(:,ivec),mo_a,mo_a,nocc,nocc)
          call esum(mo_energy_a,ab2_mo,bvec_mo,nocc,ivec)
        end if
      end do
!$omp end do
!$omp end parallel
      call rparedms(bvec_mo,ab1_mo,ab2_mo,apb,amb,nvec,tamm_dancoff)
      vl_p(1:nvec, 1:nvec) => vl(1:nvec*nvec)
      vr_p(1:nvec, 1:nvec) => vr(1:nvec*nvec)
      call rpaeig(eex,vl_p,vr_p,apb,amb,scr2,tamm_dancoff)
      call rpavnorm(vr_p,vl_p,tamm_dancoff)
      call rpaexpndv(vr_p,vl_p,vro,vlo,bvec_mo,bvec_mo,ndsr,tamm_dancoff)
      call rpaexpndv(vr_p,vl_p,abp_r,abm_l,ab1_mo,ab2_mo,ndsr,tamm_dancoff)
      call rpaechk(eex,nvec,ndsr,imax,tamm_dancoff)
!     Residual vectors W
!     Get perturbed vectors Q if required
      call rparesvec(scr3,abp_r,abm_l,vlo,vro,eex,xm,ndsr,errors,cnvtol,imax,tamm_dancoff)
      mxerr = maxval(errors(imax+1:ndsr))
      call rpaprint(eex, errors, cnvtol, iter, imax, ndsr)
!     Check convergence
      converged = mxerr<=cnvtol
      if (converged) exit
!     No space left for new vectors, exit
      if (nvec==mxvec) ierr = 1
      if (ierr/=0) exit
      call rpanewb(ndsr,bvec_mo,scr3,novec,nvec,ierr,tamm_dancoff)
  !   ierr=1 nvec over mxvec: not converged case
      if (ierr/=0) exit
      ist = novec+1
      iend = nvec
    end do
    if (iter >= mxiter .and. .not. converged) ierr = -1
    select case (ierr)
    case (-1)
      write(*,'(/,2X,"TD-DFT energies NOT CONVERGED after ",I4," iterations"/)') mxiter
      infos%mol_energy%Davidson_converged=.false.
!      call show_message("Aborting. Try to increase maxit or check your system.", WITH_ABORT)
    case (0)
      write(*,'(/,2X,"TD-DFT energies converged in ",I4," iterations"/)') iter
      infos%mol_energy%Davidson_converged=.true.
    case (1)
      write(*,'(/,2X,"..something is wrong.. nvec = mxvec")')
      infos%mol_energy%Davidson_converged=.false.
    case (2)
      write(*,'(/,2x,"..something is wrong..  nvec > mxvec")')
      write(*,'(3x,"nvec/mxvec =",I4,"/",I4)') nvec, mxvec
      infos%mol_energy%Davidson_converged=.false.
    case (3)
      write(*,'(/,2x,"..something is wrong.. No vectors were added")')
      infos%mol_energy%Davidson_converged=.false.
    end select
    call get_td_transition_dipole(basis, dip, mo_a, vro, vlo, nstates, nocc)
    call td_print_results(eex, dip, nstates)
    call measure_time(print_total=1, log_unit=iw)
    ! Bi-orthogonalize X+Y and X-Y:
    ! (X+Y)_i \dot (X-Y)_j = \delta_ij
    ! only normalization is needed
    ! RHF reference case: alpha == beta, additional factor of 1/sqrt(2)
    do ist = 1, nstates
        norm = 1/sqrt(2*dot_product(vlo(:,ist), vro(:,ist)))
        vlo(:,ist) = vlo(:,ist) * norm
        vro(:,ist) = vro(:,ist) * norm
    end do
    call infos%dat%remove_records(tags_alloc)
    call infos%dat%reserve_data(OQP_td_t, &
            TA_TYPE_REAL64, &
            nbf2, [nbf2, 1], &
            comment=OQP_td_t_comment)
    call infos%dat%reserve_data(OQP_td_xpy, &
            TA_TYPE_REAL64, &
            lexc*nstates, [lexc, nstates], &
            comment="(X+Y) vector for target state in TD-DFT calculations")
    call infos%dat%reserve_data(OQP_td_xmy, &
            TA_TYPE_REAL64, &
            lexc*nstates, [lexc, nstates], &
            comment="(X-Y) vector for target state in TD-DFT calculations")
    call infos%dat%reserve_data(OQP_td_energies, &
            TA_TYPE_REAL64, &
            nstates, [nstates], &
            comment=OQP_td_energies_comment)
    call tagarray_get_data(infos%dat, OQP_td_t, td_t)
    call tagarray_get_data(infos%dat, OQP_td_xpy, xpy)
    call tagarray_get_data(infos%dat, OQP_td_xmy, xmy)
    xpy = vro(:,:nstates)
    xmy = vlo(:,:nstates)
    call tagarray_get_data(infos%dat, OQP_td_energies, td_energies)
    td_energies = eex(:nstates)
    infos%mol_energy%excited_energy = td_energies(infos%tddft%target_state)
    call int2_driver%clean()
    if (dft) call dftclean(infos)
    close(iw)
  end subroutine tdhf_energy
Call graph
tdhf_energy calls data_has_tags, show_message, tagarray_get_data, clean, init, run, set_screening, dft_initialize, dftclean, esum, get_td_transition_dipole, iatogen, inivec, measure_time, mntoia, orthogonal_transform, print_module_info, rpaechk, rpaeig, rpaexpndv, rpanewb, rpaprint, rparedms, rparesvec, rpavnorm, symmetrize_matrix, td_print_results, tddft_fxc, remove_records, reserve_data
dft_initialize calls show_message, add_atomic_grid, add_grid, compress, find_neighbours, reset, set_screening, c_f_char, dft_fc_blk, get_radial_grid, libxc_input, set_bragg_slater
dftclean calls libxc_destroy
get_td_transition_dipole calls show_message, iatogen, orthogonal_transform, symmetrize_matrix, pack_matrix, atomic_structure_center, multipole_integrals, traceprod_sym_packed
mntoia calls oqp_dgemm_i64
orthogonal_transform calls show_message, oqp_dgemm_i64
rpaeig calls diag_symm_packed, oqp_dgemm_i64, oqp_dtrttp_i64
rpaexpndv calls oqp_dgemm_i64
rparedms calls oqp_dgemm_i64
tddft_fxc calls clean, init, run_xc, triangular_to_full
pack_matrix calls pack_f90
atomic_structure_center calls to_upper
dft_fc_blk calls getbyid, set
diag_symm_packed calls show_message, dspev, dspevx
get_radial_grid calls set, transform
ints_exchange calls show_message, alloc, compute, set, libint2_cleanup_eri, libint2_init_eri, clean, init, set_ids, genr22, int2_rys_compute, libint_compute_eri
libint_static_init calls libint2_static_init
libxc_destroy calls destroy
libxc_input calls show_message, add_functional, can_calculate, xc_f03_reference, xc_f03_reference_doi, xc_f03_version_string
multipole_integrals calls show_message, bas_norm_matrix, alloc, fetch_by_id, shell_pair, comp_allmult_int1_prim, print_sym_labeled, update_triang_matrix
oqp_dgemm_i64 calls show_message, dgemm
oqp_dtrttp_i64 calls show_message, dtrttp
run_xc calls allreduce, compaos, compxc, getslicenonzero, getstats, init, pruneaos, resetpointers, parallel_start, parallel_stop, postUpdate, update
triangular_to_full calls show_message
comp_allmult_int1_prim calls mulquadgausshermite
genr22 calls fgrid, rfinc, rmr, xgrid
int2_rys_compute calls evaluate
lebedev_get_grid calls show_message
libint_compute_eri calls ab_x, ab_y, ab_z, alpha1over_zetapluseta, alpha1rho_over_zeta2, alpha2over_zetapluseta, alpha2rho_over_zeta2, alpha3over_zetapluseta, alpha3rho_over_eta2, alpha4over_zetapluseta, alpha4rho_over_eta2, cd_x, cd_y, cd_z, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_0, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_1, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_10, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_11, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_12, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_13, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_14, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_15, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_16, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_17, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_18, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_19, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_2, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_20, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_3, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_4, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_5, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_6, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_7, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_8, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_9, fgrid, igrid, irgrd, oo2e, oo2z, oo2ze, pa_x, pa_y, pa_z, qc_x, qc_y, qc_z, rfinc, rho12_over_alpha1, rho12_over_alpha2, rho34_over_alpha3, rho34_over_alpha4, rmr, roe, roz, two_alpha0_bra, two_alpha0_ket, two_alpha1bra, two_alpha1ket, wp_x, wp_y, wp_z, wq_x, wq_y, wq_z
pack_f90 calls show_message, oqp_dtrttp_i64
print_sym_labeled calls bf_label
compute calls calc_evfxc, calc_evxc, calc_xc, scalexc
init calls clean, resetenergy
mulquadgausshermite calls abrt
mo_tran_gemm_ calls oqp_dgemm_i64
mo_tran_symm_ calls oqp_dsymm_i64
oqp_dsymm_i64 calls show_message, dsymm
tdhf_energy_c calls tdhf_energy