tdhf_mrsf_energy_C – OPENQP
tdhf_mrsf_energy_C Subroutine
8 statements
Source File
public subroutine tdhf_mrsf_energy_C(c_handle) bind(C, name="tdhf_mrsf_energy")
Uses
c_interop
types
Arguments
Type Intent Optional Attributes Name
type(oqp_handle_t) :: c_handle
Calls
Source Code
  subroutine tdhf_mrsf_energy_C(c_handle) bind(C, name="tdhf_mrsf_energy")
    use c_interop, only: oqp_handle_t, oqp_handle_get_info
    use types, only: information
    type(oqp_handle_t) :: c_handle
    type(information), pointer :: inf
    inf => oqp_handle_get_info(c_handle)
    call tdhf_mrsf_energy(inf)
  end subroutine tdhf_mrsf_energy_C
Call graph
tdhf_mrsf_energy_c calls oqp_handle_get_info, tdhf_mrsf_energy
tdhf_mrsf_energy calls data_has_tags, show_message, tagarray_get_data, unpack_matrix, clean, init, run, set_screening, get_mrsf_transition_density, get_mrsf_transitions, get_transition_density, get_transition_dipole, get_transitions, iatogen, inivec, measure_time, mntoia, mrinivec, mrsfcbc, mrsfesum, mrsfmntoia, mrsfqroesum, oqp_dgemm_i64, orthogonal_transform, orthogonal_transform_sym, print_module_info, print_results, rpaechk, rpaeig, rpanewb, rpaprint, rparedms, rpavnorm, sfqvec, sfresvec, trfrmb, remove_records, reserve_data
unpack_matrix calls unpack_f90
get_mrsf_transition_density calls show_message, get_trans_den
get_transition_density calls show_message, iatogen
get_transition_dipole calls show_message, orthogonal_transform, pack_matrix, atomic_structure_center, multipole_integrals, symmetrize_matrix, traceprod_sym_packed
mntoia calls oqp_dgemm_i64
mrsfcbc calls show_message, oqp_dgemm_i64
mrsfesum calls show_message, oqp_dgemm_i64
mrsfmntoia calls show_message, oqp_dgemm_i64, oqp_dgemv_i64
oqp_dgemm_i64 calls show_message, dgemm
orthogonal_transform calls show_message, oqp_dgemm_i64
orthogonal_transform_sym calls show_message, oqp_dgemm_i64, oqp_dsymm_i64, oqp_dtpttr_i64, oqp_dtrttp_i64
rpaeig calls oqp_dgemm_i64, diag_symm_packed, oqp_dtrttp_i64
rparedms calls oqp_dgemm_i64
sfresvec calls oqp_dgemm_i64
trfrmb calls oqp_dgemm_i64
pack_matrix calls pack_f90
atomic_structure_center calls to_upper
diag_symm_packed calls show_message, dspev, dspevx
ints_exchange calls show_message, alloc, compute, set, libint2_cleanup_eri, libint2_init_eri, clean, init, set_ids, genr22, int2_rys_compute, libint_compute_eri
libint_static_init calls libint2_static_init
multipole_integrals calls show_message, bas_norm_matrix, alloc, fetch_by_id, shell_pair, comp_allmult_int1_prim, print_sym_labeled, update_triang_matrix
oqp_dgemv_i64 calls show_message, dgemv
oqp_dsymm_i64 calls show_message, dsymm
oqp_dtpttr_i64 calls show_message, dtpttr
oqp_dtrttp_i64 calls show_message, dtrttp
unpack_f90 calls show_message, oqp_dtpttr_i64
comp_allmult_int1_prim calls mulquadgausshermite
genr22 calls fgrid, rfinc, rmr, xgrid
int2_rys_compute calls evaluate
libint_compute_eri calls ab_x, ab_y, ab_z, alpha1over_zetapluseta, alpha1rho_over_zeta2, alpha2over_zetapluseta, alpha2rho_over_zeta2, alpha3over_zetapluseta, alpha3rho_over_eta2, alpha4over_zetapluseta, alpha4rho_over_eta2, cd_x, cd_y, cd_z, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_0, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_1, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_10, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_11, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_12, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_13, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_14, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_15, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_16, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_17, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_18, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_19, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_2, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_20, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_3, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_4, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_5, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_6, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_7, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_8, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_9, fgrid, igrid, irgrd, oo2e, oo2z, oo2ze, pa_x, pa_y, pa_z, qc_x, qc_y, qc_z, rfinc, rho12_over_alpha1, rho12_over_alpha2, rho34_over_alpha3, rho34_over_alpha4, rmr, roe, roz, two_alpha0_bra, two_alpha0_ket, two_alpha1bra, two_alpha1ket, wp_x, wp_y, wp_z, wq_x, wq_y, wq_z
pack_f90 calls show_message, oqp_dtrttp_i64
print_sym_labeled calls bf_label
mulquadgausshermite calls abrt