tdhf_unrelaxed_density – OPENQP
tdhf_unrelaxed_density Subroutine
27 statements
Source File
public subroutine tdhf_unrelaxed_density(xmy, xpy, mo, t, nocc, tda)
Uses
mathlib
precision
@brief Compute unrelaxed difference density matrix for R-TDDFT
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: xmy(*)
real(kind=dp), intent(in) :: xpy(*)
real(kind=dp), intent(in) :: mo(:,:)
real(kind=dp), intent(out) :: t(*)
integer, intent(in) :: nocc
logical, intent(in) :: tda
Calls
Called by
Call graph
tdhf_unrelaxed_density calls pack_matrix, oqp_dgemm_i64, orthogonal_transform
pack_matrix calls pack_f90
oqp_dgemm_i64 calls dgemm, show_message
orthogonal_transform calls oqp_dgemm_i64, show_message
pack_f90 calls show_message, oqp_dtrttp_i64
oqp_dtrttp_i64 calls show_message, dtrttp
oqp_tdhf_z_vector calls tdhf_unrelaxed_density
tdhf_z_vector_c calls oqp_tdhf_z_vector