tdhf_z_vector_C – OPENQP
tdhf_z_vector_C Subroutine
9 statements
Source File
public subroutine tdhf_z_vector_C(c_handle) bind(C, name="tdhf_z_vector")
Uses
types
c_interop
strings
Arguments
Type Intent Optional Attributes Name
type(oqp_handle_t) :: c_handle
Calls
Call graph
tdhf_z_vector_c calls oqp_handle_get_info, oqp_tdhf_z_vector
oqp_tdhf_z_vector calls data_has_tags, pack_matrix, show_message, tagarray_get_data, unpack_matrix, clean, init, run, set_screening, step, dft_initialize, dftclean, iatogen, int2_rpagrd_data_t_clean, measure_time, oqp_dgemm_i64, oqp_dsyr2k_i64, orthogonal_transform, print_module_info, symmetrize_matrix, tddft_fxc, tddft_gxc, tdhf_unrelaxed_density, triangular_to_full, remove_records, reserve_data
pack_matrix calls pack_f90
unpack_matrix calls unpack_f90
dft_initialize calls show_message, add_atomic_grid, add_grid, compress, find_neighbours, reset, set_screening, c_f_char, dft_fc_blk, get_radial_grid, libxc_input, set_bragg_slater
dftclean calls libxc_destroy
oqp_dgemm_i64 calls show_message, dgemm
oqp_dsyr2k_i64 calls show_message, dsyr2k
orthogonal_transform calls show_message, oqp_dgemm_i64
tddft_fxc calls triangular_to_full, clean, init, run_xc
tddft_gxc calls triangular_to_full, clean, init, run_xc
tdhf_unrelaxed_density calls pack_matrix, oqp_dgemm_i64, orthogonal_transform
triangular_to_full calls show_message
dft_fc_blk calls getbyid, set
get_radial_grid calls set, transform
ints_exchange calls show_message, alloc, compute, set, libint2_cleanup_eri, libint2_init_eri, clean, init, set_ids, genr22, int2_rys_compute, libint_compute_eri
libint_static_init calls libint2_static_init
libxc_destroy calls destroy
libxc_input calls show_message, add_functional, can_calculate, xc_f03_reference, xc_f03_reference_doi, xc_f03_version_string
pack_f90 calls show_message, oqp_dtrttp_i64
run_xc calls allreduce, compaos, compxc, getslicenonzero, getstats, init, pruneaos, resetpointers, parallel_start, parallel_stop, postUpdate, update
unpack_f90 calls show_message, oqp_dtpttr_i64
genr22 calls fgrid, rfinc, rmr, xgrid
int2_rys_compute calls evaluate
lebedev_get_grid calls show_message
libint_compute_eri calls ab_x, ab_y, ab_z, alpha1over_zetapluseta, alpha1rho_over_zeta2, alpha2over_zetapluseta, alpha2rho_over_zeta2, alpha3over_zetapluseta, alpha3rho_over_eta2, alpha4over_zetapluseta, alpha4rho_over_eta2, cd_x, cd_y, cd_z, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_0, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_1, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_10, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_11, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_12, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_13, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_14, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_15, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_16, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_17, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_18, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_19, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_2, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_20, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_3, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_4, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_5, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_6, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_7, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_8, f_ab_s___0__s___1___twoprep_s___0__s___1___ab__up_9, fgrid, igrid, irgrd, oo2e, oo2z, oo2ze, pa_x, pa_y, pa_z, qc_x, qc_y, qc_z, rfinc, rho12_over_alpha1, rho12_over_alpha2, rho34_over_alpha3, rho34_over_alpha4, rmr, roe, roz, two_alpha0_bra, two_alpha0_ket, two_alpha1bra, two_alpha1ket, wp_x, wp_y, wp_z, wq_x, wq_y, wq_z
oqp_dtpttr_i64 calls show_message, dtpttr
oqp_dtrttp_i64 calls show_message, dtrttp
compute calls calc_evfxc, calc_evxc, calc_xc, scalexc
init calls clean, resetenergy
mo_tran_gemm_ calls oqp_dgemm_i64
mo_tran_symm_ calls oqp_dsymm_i64
oqp_dsymm_i64 calls show_message, dsymm