to_upper – OPENQP
to_upper Function
12 statements
Source File
public pure function to_upper(input_string) result(output_string)
@brief return string in upper case @author Igor S. Gerasimov @date Sep, 2019 --Initial release-- @date May, 2021 Moved to strings @date Sep, 2021 subroutine -> function @param line - (in)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: input_string
Return Value character(len=:), allocatable
Called by
Source Code
  pure function to_upper(input_string) result(output_string)
    character(*), intent(in) :: input_string
    character(:), allocatable :: output_string
    integer :: i, ic
    output_string = input_string
    do i = 1, len(output_string)
      ic = iachar(output_string(i:i))
      if (ic <= Z_LOWER .and. ic >= A_LOWER) then
        output_string(i:i) = achar(ic-UPPER_TO_LOWER)
      end if
    end do
  end function to_upper
Call graph
atomic_structure_center calls to_upper
get_element_id calls to_upper
get_td_transition_dipole calls atomic_structure_center
get_transition_dipole calls atomic_structure_center
tdhf_energy calls get_td_transition_dipole
tdhf_mrsf_energy calls get_transition_dipole
tdhf_sf_energy calls get_transition_dipole
guess_huckel calls from_file
tdhf_energy_c calls tdhf_energy
tdhf_mrsf_energy_c calls tdhf_mrsf_energy
tdhf_sf_energy_c calls tdhf_sf_energy
guess_huckel_c calls guess_huckel