traceprod_sym_packed – OPENQP
traceprod_sym_packed Function
13 statements
Source File
public function traceprod_sym_packed(a, b, n) result(res)
Uses
precision
@brief Compute the trace of the product of two symmetric matrices in packed format @detail The trace is actually an inner product of matrices, assuming they are vectors @param[in] a first matrix @param[in] b second matrix @param[in] n dimension of matrices A and B
Arguments
Type Intent Optional Attributes Name
real(kind=dp) :: a(*)
real(kind=dp) :: b(*)
integer :: n
Return Value real(kind=dp)
Called by
Call graph
electric_moments calls traceprod_sym_packed
get_spin_square calls traceprod_sym_packed
get_td_transition_dipole calls traceprod_sym_packed
get_transition_dipole calls traceprod_sym_packed
scf_driver calls traceprod_sym_packed
hf_energy calls scf_driver
tdhf_energy calls get_td_transition_dipole
tdhf_mrsf_energy calls get_transition_dipole
tdhf_sf_energy calls get_spin_square, get_transition_dipole
tdhf_energy_c calls tdhf_energy
tdhf_mrsf_energy_c calls tdhf_mrsf_energy
tdhf_sf_energy_c calls tdhf_sf_energy