triangular_to_full – OPENQP
triangular_to_full Subroutine
20 statements
Source File
public subroutine triangular_to_full(a, n, uplo)
Uses
precision
messages
@brief Fill the upper/lower triangle of the symmetric matrix @param[inout] a square NxN matrix in triangular form @param[in] n matrix dimension @param[in] uplo U if A is upper triangular, L if lower triangular
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: a(n,*)
integer, intent(in) :: n
character(len=1), intent(in) :: uplo
Calls
Called by
Source Code
  subroutine triangular_to_full(a,n,uplo)
    use precision, only: dp
    use messages, only: show_message, with_abort
    implicit none
    real(kind=dp), intent(inout) :: a(n,*)
    integer, intent(in) :: n
    character(len=1), intent(in) :: uplo
    integer :: i
    if (uplo=='u' .or. uplo=='U') then
      do i = 1, n
        a(i+1:n,i) = a(i,i+1:n)
      end do
    else if (uplo=='l' .or. uplo=='L') then
      do i = 1, n
        a(i,i+1:n) = a(i+1:n,i)
      end do
    else
      call show_message('Invalid parameter UPLO='//uplo// &
              ' in `triangular_to_full`. Use either `L` or `U`.', with_abort)
    end if
  end subroutine triangular_to_full
Call graph
triangular_to_full calls show_message
electric_moments calls triangular_to_full
form_rohf_fock calls triangular_to_full
oqp_tdhf_z_vector calls triangular_to_full, tddft_fxc, tddft_gxc
tddft_fxc calls triangular_to_full
tddft_gxc calls triangular_to_full
utddft_fxc calls triangular_to_full
scf_driver calls form_rohf_fock
tdhf_energy calls tddft_fxc
tdhf_z_vector_c calls oqp_tdhf_z_vector
hf_energy calls scf_driver
tdhf_energy_c calls tdhf_energy