update_rectangular_matrix – OPENQP
update_rectangular_matrix Subroutine
15 statements
Source File
public subroutine update_rectangular_matrix(shi, shj, mblk, m)
@brief Add contribution of the 1e-integral block to the rectangular matrix @param[in] shi first shell data @param[in] shj second shell data @param[in] mblk square block of 1e integrals passed as 1D array @param[inout] m rectangular matrix of 1-e integral contribution @author Igor S. Gerasimov @date Oct, 2022 Initial release
Arguments
Type Intent Optional Attributes Name
type(shell_t), intent(in) :: shi
type(shell_t), intent(in) :: shj
real(kind=REAL64), intent(in), CONTIGUOUS :: mblk(:)
real(kind=REAL64), intent(inout), CONTIGUOUS :: m(:,:)
Called by
Call graph
basis_overlap calls update_rectangular_matrix
get_structures_ao_overlap calls basis_overlap
huckel_guess calls basis_overlap
get_structures_ao_overlap_c calls get_structures_ao_overlap
guess_huckel calls huckel_guess
guess_huckel_c calls guess_huckel