update_triang_matrix – OPENQP
update_triang_matrix Subroutine
21 statements
Source File
public subroutine update_triang_matrix(shi, shj, mblk, m)
@brief Add contribution of the 1e-integral block to the triangular matrix @param[in] shi first shell data @param[in] shj second shell data @param[in] mblk square block of 1e integrals passed as 1D array @param[inout] m packed triangular matrix of 1e integral contribution @author Vladimir Mironov @date Sep, 2018 Initial release
Arguments
Type Intent Optional Attributes Name
type(shell_t), intent(in) :: shi
type(shell_t), intent(in) :: shj
real(kind=REAL64), intent(in), CONTIGUOUS :: mblk(:)
real(kind=REAL64), intent(inout), CONTIGUOUS :: m(:)
Called by
Call graph
multipole_integrals calls update_triang_matrix
omp_hst calls update_triang_matrix
overlap calls update_triang_matrix
electric_moments calls multipole_integrals
get_td_transition_dipole calls multipole_integrals
get_transition_dipole calls multipole_integrals
huckel_guess calls overlap
int1e calls omp_hst
guess_huckel calls huckel_guess
tdhf_energy calls get_td_transition_dipole
tdhf_mrsf_energy calls get_transition_dipole
tdhf_sf_energy calls get_transition_dipole
guess_huckel_c calls guess_huckel
tdhf_energy_c calls tdhf_energy
tdhf_mrsf_energy_c calls tdhf_mrsf_energy
tdhf_sf_energy_c calls tdhf_sf_energy