utddft_fxc – OPENQP
utddft_fxc Subroutine
82 statements
Source File
public subroutine utddft_fxc(basis, molGrid, isVecs, wfa, wfb, fxa, fxb, dxa, dxb, nMtx, threshold, infos)
Uses
mod_dft_gridint
types
mathlib
basis_tools
mod_dft_molgrid
@brief Compute derivative XC contribution to the TD-DFT KS-like matrices @param[in] basis basis set @param[in] isVecs .true. if orbitals are provided instead of density matrix @param[in] wf density matrix/orbitals @param[inout] fx fock-like matrices @param[inout] dx densities @param[in] nMtx number of density/Fock-like matrices @param[in] threshold tolerance @param[in] isGGA .TRUE. if GGA/mGGA functional used @param[in] infos OQP metadata @author Vladimir Mironov
Arguments
Type Intent Optional Attributes Name
type(basis_set) :: basis
type(dft_grid_t), intent(in), target :: molGrid
logical, intent(in) :: isVecs
real(kind=fp), intent(in) :: wfa(:,:)
real(kind=fp), intent(in) :: wfb(:,:)
real(kind=fp), intent(inout) :: fxa(:,:,:)
real(kind=fp), intent(inout) :: fxb(:,:,:)
real(kind=fp), intent(inout), target :: dxa(:,:,:)
real(kind=fp), intent(inout), target :: dxb(:,:,:)
integer, intent(in) :: nMtx
real(kind=fp), intent(in) :: threshold
type(information), intent(in), target :: infos
Calls
Call graph
utddft_fxc calls clean, run_xc, triangular_to_full
run_xc calls allreduce, compaos, compxc, getslicenonzero, getstats, init, pruneaos, resetpointers, parallel_start, parallel_stop, postUpdate, update
triangular_to_full calls show_message
compute calls calc_evfxc, calc_evxc, calc_xc, scalexc
init calls clean, resetenergy
mo_tran_gemm_ calls oqp_dgemm_i64
mo_tran_symm_ calls oqp_dsymm_i64
oqp_dgemm_i64 calls show_message, dgemm
oqp_dsymm_i64 calls show_message, dsymm