utddft_xc_gradient – OPENQP
utddft_xc_gradient Subroutine
96 statements
Source File
public subroutine utddft_xc_gradient(basis, molGrid, dedft, da, db, pa, pb, xa, xb, nMtx, threshold, infos)
Uses
types
basis_tools
mod_dft_gridint
mod_dft_molgrid
@brief Compute derivative XC contribution to the TD-DFT KS-like matrices @param[in] basis basis set @param[in] wf density matrix/orbitals @param[inout] fx fock-like matrices @param[inout] dx densities @param[in] nMtx number of density/Fock-like matrices @param[in] threshold tolerance @param[in] isGGA .TRUE. if GGA/mGGA functional used @param[in] infos OQP metadata @author Vladimir Mironov
Arguments
Type Intent Optional Attributes Name
type(basis_set) :: basis
type(dft_grid_t), intent(in), target :: molGrid
real(kind=fp), intent(out) :: dedft(:,:)
real(kind=fp), intent(inout), contiguous, target :: da(:,:)
real(kind=fp), intent(inout), contiguous, target :: db(:,:)
real(kind=fp), intent(inout), target :: pa(:,:,:)
real(kind=fp), intent(inout), target :: pb(:,:,:)
real(kind=fp), intent(inout), optional, target :: xa(:,:,:)
real(kind=fp), intent(inout), optional, target :: xb(:,:,:)
integer, intent(in) :: nMtx
real(kind=fp), intent(in) :: threshold
type(information), intent(in), target :: infos
Calls
Call graph
utddft_xc_gradient calls clean, init, run_xc
run_xc calls allreduce, compaos, compxc, getslicenonzero, getstats, init, pruneaos, resetpointers, parallel_start, parallel_stop, postUpdate, update
compute calls calc_evfxc, calc_evxc, calc_xc, scalexc
init calls clean, resetenergy
mo_tran_gemm_ calls oqp_dgemm_i64
mo_tran_symm_ calls oqp_dsymm_i64
oqp_dgemm_i64 calls show_message, dgemm
oqp_dsymm_i64 calls show_message, dsymm