module tdhf_mrsf_hessian_fock_response_mod

  use precision, only: dp
  use types, only: information
  use basis_tools, only: basis_set
  use mathlib, only: pack_matrix,unpack_matrix
  use scf_addons, only: fock_jk
  use fock_deriv_mod, only: fock_deriv_matrix_os

  implicit none

  private
  public :: build_orbital_density_derivatives
  public :: build_rohf_total_fock_derivatives

contains

!###############################################################################

  subroutine build_orbital_density_derivatives(mo,dmo,nocc, &
      density_derivative,status)
    ! AO density response generated by the complete moving-basis orbital
    ! connection for one spin: dP=dC_occ C_occ^T+C_occ dC_occ^T.

    real(kind=dp), intent(in) :: mo(:,:),dmo(:,:,:)
    integer, intent(in) :: nocc
    real(kind=dp), intent(out) :: density_derivative(:,:,:)
    integer, intent(out) :: status

    integer :: coordinate,nbf,ncoord

    nbf=size(mo,1)
    ncoord=size(dmo,3)
    status=0
    density_derivative=0.0_dp
    if(nbf<=0 .or. ncoord<=0 .or. nocc<0 .or. nocc>nbf .or. &
       any(shape(mo)/=[nbf,nbf]) .or. &
       any(shape(dmo)/=[nbf,nbf,ncoord]) .or. &
       any(shape(density_derivative)/=[nbf,nbf,ncoord])) then
      status=-1
      return
    end if
    do coordinate=1,ncoord
      density_derivative(:,:,coordinate)= &
        matmul(dmo(:,1:nocc,coordinate),transpose(mo(:,1:nocc)))+ &
        matmul(mo(:,1:nocc),transpose(dmo(:,1:nocc,coordinate)))
    end do
  end subroutine build_orbital_density_derivatives

!###############################################################################

  subroutine build_rohf_total_fock_derivatives(infos,hcore_derivative,pa,pb, &
      dpa,dpb,dfock_a,dfock_b,status,dvxc_a,dvxc_b)
    ! Assemble total AO spin-Fock derivatives needed by the one-electron MRSF
    ! operator response:
    !
    ! dF_s = dh + J^x[P_a+P_b] - c_H K^x[P_s]
    !          + J[dP_a+dP_b] - c_H K[dP_s] + dV_xc,s .
    !
    ! The first two-electron line is evaluated with derivative ERIs and the
    ! second with the ordinary SCF Fock builder.  For DFT the caller must
    ! provide the complete moving-grid/kernel XC derivative.  Range-separated
    ! response remains fail-closed until its derivative-integral split is
    ! verified.  This preserves Hiroya Nakata's founding spin-adapted two-SOMO
    ! response rather than introducing an alternate electronic-state model.

    type(information), target, intent(inout) :: infos
    real(kind=dp), intent(in) :: hcore_derivative(:,:,:),pa(:,:),pb(:,:), &
      dpa(:,:,:),dpb(:,:,:)
    real(kind=dp), intent(out) :: dfock_a(:,:,:),dfock_b(:,:,:)
    integer, intent(out) :: status
    real(kind=dp), intent(in), optional :: dvxc_a(:,:,:),dvxc_b(:,:,:)

    type(basis_set), pointer :: basis
    real(kind=dp), allocatable :: ptot(:,:),explicit_a(:,:,:,:), &
      explicit_b(:,:,:,:),packed_density(:,:),packed_fock(:,:),response(:,:)
    real(kind=dp) :: hfscale
    integer :: atom,cart,coordinate,natom,nbf,nbf2,ncoord
    logical :: dft

    basis=>infos%basis
    basis%atoms=>infos%atoms
    nbf=basis%nbf
    nbf2=nbf*(nbf+1)/2
    natom=size(basis%atoms%xyz,2)
    ncoord=3*natom
    dft=infos%control%hamilton==20
    status=0
    dfock_a=0.0_dp
    dfock_b=0.0_dp
    if(nbf<=0 .or. natom<=0 .or. any(shape(pa)/=[nbf,nbf]) .or. &
       any(shape(pb)/=[nbf,nbf]) .or. &
       any(shape(hcore_derivative)/=[nbf,nbf,ncoord]) .or. &
       any(shape(dpa)/=[nbf,nbf,ncoord]) .or. &
       any(shape(dpb)/=[nbf,nbf,ncoord]) .or. &
       any(shape(dfock_a)/=[nbf,nbf,ncoord]) .or. &
       any(shape(dfock_b)/=[nbf,nbf,ncoord])) then
      status=-1
      return
    end if
    if(dft .and. infos%dft%cam_flag) then
      status=-3
      return
    end if
    if(dft) then
      if(.not.present(dvxc_a) .or. .not.present(dvxc_b)) then
        status=-2
        return
      end if
      if(any(shape(dvxc_a)/=[nbf,nbf,ncoord]) .or. &
         any(shape(dvxc_b)/=[nbf,nbf,ncoord])) then
        status=-1
        return
      end if
      hfscale=infos%dft%hfscale
    else
      hfscale=1.0_dp
    end if

    allocate(ptot(nbf,nbf),explicit_a(nbf,nbf,3,natom), &
      explicit_b(nbf,nbf,3,natom),packed_density(nbf2,2), &
      packed_fock(nbf2,2),response(nbf,nbf),source=0.0_dp)
    ptot=pa+pb
    call fock_deriv_matrix_os(infos,basis,ptot,pa,hfscale,explicit_a)
    call fock_deriv_matrix_os(infos,basis,ptot,pb,hfscale,explicit_b)
    coordinate=0
    do atom=1,natom
      do cart=1,3
        coordinate=coordinate+1
        call pack_matrix(dpa(:,:,coordinate),packed_density(:,1))
        call pack_matrix(dpb(:,:,coordinate),packed_density(:,2))
        packed_fock=0.0_dp
        call fock_jk(basis,d=packed_density,f=packed_fock, &
          scale_exch=hfscale,infos=infos)
        call unpack_matrix(packed_fock(:,1),response)
        dfock_a(:,:,coordinate)=hcore_derivative(:,:,coordinate)+ &
          explicit_a(:,:,cart,atom)+response
        call unpack_matrix(packed_fock(:,2),response)
        dfock_b(:,:,coordinate)=hcore_derivative(:,:,coordinate)+ &
          explicit_b(:,:,cart,atom)+response
        if(dft) then
          dfock_a(:,:,coordinate)=dfock_a(:,:,coordinate)+ &
            dvxc_a(:,:,coordinate)
          dfock_b(:,:,coordinate)=dfock_b(:,:,coordinate)+ &
            dvxc_b(:,:,coordinate)
        end if
      end do
    end do
    deallocate(ptot,explicit_a,explicit_b,packed_density,packed_fock,response)
  end subroutine build_rohf_total_fock_derivatives

end module tdhf_mrsf_hessian_fock_response_mod
