from pathlib import Path
import json


ROOT = Path(__file__).resolve().parents[1]


def test_ispher_input_schema_defaults_enabled():
    text = (ROOT / "pyoqp/oqp/molecule/oqpdata.py").read_text()

    assert "'ispher': {'type': bool, 'default': 'True'}" in text
    assert "oqp_set_harmonic_active" in text


def test_ispher_cffi_binding_is_declared():
    header = (ROOT / "include/oqp.h").read_text()
    constants = (ROOT / "source/constants.F90").read_text()

    assert "void oqp_set_harmonic_active(bool flag);" in header
    assert 'bind(C, name="oqp_set_harmonic_active")' in constants
    assert "logical :: HARMONIC_ACTIVE = .true." in constants


def test_apply_basis_reports_runtime_cartesian_override():
    text = (ROOT / "source/modules/apply_basis.F90").read_text()

    assert "use constants, only: HARMONIC_ACTIVE, NUM_CART_BF" in text
    assert "if (HARMONIC_ACTIVE .and. nsphsh > 0) then" in text
    assert "AO angular type: Cartesian (6d/10f/15g)" in text


def test_auto_spherical_basis_uses_all_supported_transforms():
    set_basis = (ROOT / "pyoqp/oqp/library/set_basis.py").read_text()
    cart2sph = (ROOT / "source/integrals/cart2sph.F90").read_text()
    constants = (ROOT / "source/constants.F90").read_text()
    symmetry = (ROOT / "pyoqp/oqp/library/symmetry.py").read_text()

    assert "shell_harmonic = 1 if shell_is_spherical else 0" in set_basis
    assert "input.ispher=True only supports pure spherical shells through g" not in set_basis
    assert "integer, parameter :: BAS_MXANG = 6" in constants
    assert "integer, parameter :: NUM_SPH_BF(0:BAS_MXANG)  = [(2*i+1, i = 0, BAS_MXANG)]" in constants
    assert "c2s_build(l)" in cart2sph
    assert "c2s_h = c2s_build(l)" in cart2sph
    assert "c2s_i = c2s_build(l)" in cart2sph
    assert "do l = 2, BAS_MXANG" in cart2sph
    assert "pure spherical transforms are implemented only through g shells" not in cart2sph
    assert "5: [(5, 0, 0)" in symmetry
    assert "6: [(6, 0, 0)" in symmetry


def test_bse_function_type_drives_basis_native_cartesian_vs_spherical():
    import basis_set_exchange as bse

    set_basis = (ROOT / "pyoqp/oqp/library/set_basis.py").read_text()

    def d_shell_types(name):
        basis = bse.get_basis(name, elements=[8], fmt="json")
        if isinstance(basis, str):
            basis = json.loads(basis)
        return [
            shell.get("function_type", "gto")
            for shell in basis["elements"]["8"]["electron_shells"]
            if 2 in shell["angular_momentum"]
        ]

    assert "shell_ft = shell.get('function_type', 'gto')" in set_basis
    assert "shell_harmonic = 1 if shell_is_spherical else 0" in set_basis
    assert d_shell_types("6-31G*") == ["gto_cartesian"]
    assert d_shell_types("cc-pVDZ") == ["gto_spherical"]


def test_cartesian_override_keeps_cartesian_normalization():
    text = (ROOT / "source/basis_tools.F90").read_text()

    assert "if (HARMONIC_ACTIVE .and. basis%harmonic(i) == 1) then" in text


def test_two_e_backends_reduce_pure_blocks_before_consumers():
    int2 = (ROOT / "source/integrals/int2.F90").read_text()
    rot = (ROOT / "source/integrals/int_rotaxis.F90").read_text()
    rys = (ROOT / "source/integrals/int_rys.F90").read_text()
    pure_generated = (ROOT / "source/integrals/int2_pure_generated.F90").read_text()
    pure_generator = (ROOT / "tools/generate_int2_pure_kernels.py").read_text()

    assert "Generated by tools/generate_int2_pure_kernels.py" in pure_generated
    assert "INT2_PURE_MAX_TERMS = 4" in pure_generated
    assert "subroutine load_l2" in pure_generated
    assert "call add_term(proj,  1,  3" in pure_generated
    assert "def solid_harmonic_coefficients" in pure_generator
    assert "OUT = ROOT / \"source\" / \"integrals\" / \"int2_pure_generated.F90\"" in pure_generator
    assert "public genr22_reduce_pure" in rot
    assert "subroutine genr22_reduce_pure" in rot
    assert "if (.not. HARMONIC_ACTIVE) return" in rot
    assert "use int2_pure_generated, only: int2_project_pure_block" in rot
    assert "call int2_project_pure_block(grotspd, am_s, pure_s, nbf_s, nbf_out_s)" in rot
    assert "nbf = nbf_out_s([4,3,2,1])" in rot
    assert "public :: int2_rys_reduce_pure" in rys
    assert "subroutine int2_rys_reduce_pure" in rys
    assert "if (.not. HARMONIC_ACTIVE) return" in rys
    assert "type(int2_shell_projection_t) :: proj(4)" in rys
    assert "subroutine compute_ints_direct_pure" in rys
    assert "call int2_init_shell_projection(gdat%am(s), pure_s(s), gdat%proj(s))" in rys
    assert "* shells_pnrm2(i,gdat%am(1))" in rys
    assert "nbf_out = nbf_out_s([4,3,2,1])" in rys
    assert "call genr22_reduce_pure(basis, eri_data%ids, eri_data%flips" in int2
    assert "direct_pure=.true." in int2
    assert "if (eri_data%gdat%direct_pure) then" in int2
    assert "call int2_rys_reduce_pure(basis, eri_data%gdat, eri_data%ints, nbf)" in int2
    assert "call genr22_reduce_pure(basis, shell_ids, flips, ints, nbf)" in int2
    assert "call int2_rys_reduce_pure(basis, gdat, ints, nbf)" in int2
    assert "call normalize_ints(nbf, am(flips), pints)" in int2
    assert "nbf = NUM_CART_BF(am(flips))" in int2
