bas_norm_matrix – OPENQP
bas_norm_matrix Interface
4 statements
Source File
public interface bas_norm_matrix
Called by
Module Procedures
private subroutine bas_norm_matrix_tr(a, p, ld)
@brief Scale matrix A with matrix \f$ P \cdot P^T \f$ @details A is a packed square matrix, P is a column vector @author Vladimir Mironov @date -Sep, 2018- Initial release
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(inout) :: a(:)
real(kind=real64), intent(in), allocatable :: p(:)
integer, intent(in) :: ld
private subroutine bas_norm_matrix_sq(a, p, ld)
@brief Scale matrix A with matrix \f$ P \cdot P^T \f$ @details A is a full square matrix, P is a column vector @author Vladimir Mironov @date -Sep, 2018- Initial release
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(inout) :: a(:,:)
real(kind=real64), intent(in), allocatable :: p(:)
integer, intent(in) :: ld
Call graph
electrostatic_potential calls bas_norm_matrix
grad_ee_kinetic calls bas_norm_matrix
grad_ee_overlap calls bas_norm_matrix
grad_en_hellman_feynman calls bas_norm_matrix
grad_en_pulay calls bas_norm_matrix
multipole_integrals calls bas_norm_matrix
omp_hst calls bas_norm_matrix
electric_moments calls multipole_integrals
get_td_transition_dipole calls multipole_integrals
get_transition_dipole calls multipole_integrals
hf_gradient calls grad_ee_kinetic, grad_ee_overlap, grad_en_hellman_feynman, grad_en_pulay
int1e calls omp_hst
oqp_resp_charges calls electrostatic_potential
tdhf_1e_grad calls grad_ee_kinetic, grad_ee_overlap, grad_en_hellman_feynman, grad_en_pulay
resp_charges_c calls oqp_resp_charges
tdhf_energy calls get_td_transition_dipole
tdhf_gradient calls tdhf_1e_grad
tdhf_mrsf_energy calls get_transition_dipole
tdhf_sf_energy calls get_transition_dipole
tdhf_energy_c calls tdhf_energy
tdhf_gradient_c calls tdhf_gradient
tdhf_mrsf_energy_c calls tdhf_mrsf_energy
tdhf_sf_energy_c calls tdhf_sf_energy