compute_integrals – OPENQP
compute_integrals Interface
43 statements
Source File
interface
Called by
public function compute_integrals(integrator) bind(c, name="compute_integrals")
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: integrator
Return Value type(ecp_result)
Call graph
add_ecpint calls compute_integrals
omp_hst calls add_ecpint
int1e calls omp_hst