compute_first_derivs – OPENQP
compute_first_derivs Interface
43 statements
Source File
interface
Called by
public function compute_first_derivs(integrator) bind(c, name="compute_first_derivs")
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: integrator
Return Value type(ecp_result)
Call graph
add_ecpder calls compute_first_derivs
grad_1e_ecp calls add_ecpder
hf_gradient calls grad_1e_ecp
tdhf_1e_grad calls grad_1e_ecp
tdhf_gradient calls tdhf_1e_grad
tdhf_gradient_c calls tdhf_gradient