data_has_tags – OPENQP
data_has_tags Interface
3 statements
Source File
public interface data_has_tags
Called by
Module Procedures
private subroutine data_has_tags_location(container, tags, location, abort, status)
Arguments
Type Intent Optional Attributes Name
type(container_t), intent(inout) :: container
character(len=*), intent(in) :: tags(:)
character(len=*), intent(in) :: location
logical, intent(in), optional :: abort
integer(kind=c_int32_t), intent(out), optional :: status
private subroutine data_has_tags_ms(container, tags, modulename, subroutinename, abort, status)
Arguments
Type Intent Optional Attributes Name
type(container_t), intent(inout) :: container
character(len=*), intent(in) :: tags(:)
character(len=*), intent(in) :: modulename
character(len=*), intent(in) :: subroutinename
logical, intent(in), optional :: abort
integer(kind=c_int32_t), intent(out), optional :: status
Call graph
eijden calls data_has_tags
get_states_overlap calls data_has_tags
get_structures_ao_overlap calls data_has_tags
guess_hcore calls data_has_tags
guess_huckel calls data_has_tags
guess_json calls data_has_tags
int1e calls data_has_tags
oqp_apply_basis calls data_has_tags
oqp_banner calls data_has_tags
oqp_resp_charges calls data_has_tags
oqp_tdhf_z_vector calls data_has_tags
print_eigvec_vals_labeled calls data_has_tags
run_population_analysis calls data_has_tags
scf_driver calls data_has_tags, print_mo_range
tdhf_1e_grad calls data_has_tags, eijden
tdhf_energy calls data_has_tags
tdhf_gradient calls data_has_tags, tdhf_1e_grad
tdhf_mrsf_energy calls data_has_tags
tdhf_sf_energy calls data_has_tags
apply_basis_c calls oqp_apply_basis
get_state_overlap_c calls get_states_overlap
get_structures_ao_overlap_c calls get_structures_ao_overlap
guess_hcore_c calls guess_hcore
guess_huckel_c calls guess_huckel
guess_json_c calls guess_json
hf_energy calls scf_driver
hf_gradient calls eijden
lowdin calls run_population_analysis
mulliken calls run_population_analysis
oqp_banner_c calls oqp_banner
print_mo_range calls print_eigvec_vals_labeled
resp_charges_c calls oqp_resp_charges
tdhf_energy_c calls tdhf_energy
tdhf_gradient_c calls tdhf_gradient
tdhf_mrsf_energy_c calls tdhf_mrsf_energy
tdhf_sf_energy_c calls tdhf_sf_energy
tdhf_z_vector_c calls oqp_tdhf_z_vector