oqp_handle_get_info – OPENQP
oqp_handle_get_info Interface
4 statements
Source File
public interface oqp_handle_get_info
Called by
Module Procedures
private function oqp_handle_get_info_f(f_handle) result(res)
Arguments
Type Intent Optional Attributes Name
type(oqp_handle_t), target :: f_handle
Return Value type(information), pointer
private function oqp_handle_get_info_c(c_handle) result(res)
Arguments
Type Intent Optional Attributes Name
type(c_ptr) :: c_handle
Return Value type(information), pointer
Call graph
apply_basis_c calls oqp_handle_get_info
get_state_overlap_c calls oqp_handle_get_info
get_structures_ao_overlap_c calls oqp_handle_get_info
guess_hcore_c calls oqp_handle_get_info
guess_huckel_c calls oqp_handle_get_info
guess_json_c calls oqp_handle_get_info
oqp_banner_c calls oqp_handle_get_info
resp_charges_c calls oqp_handle_get_info
tdhf_energy_c calls oqp_handle_get_info
tdhf_gradient_c calls oqp_handle_get_info
tdhf_mrsf_energy_c calls oqp_handle_get_info
tdhf_sf_energy_c calls oqp_handle_get_info
tdhf_z_vector_c calls oqp_handle_get_info