set_ecp_basis – OPENQP
set_ecp_basis Interface
43 statements
Source File
interface
Called by
public subroutine set_ecp_basis(integrator, num_ecps, u_coords, u_exps, u_coefs, u_ams, u_ns, u_lengths) bind(c, name="set_ecp_basis")
Arguments
Type Intent Optional Attributes Name
type(c_ptr), value :: integrator
integer(kind=c_int), value :: num_ecps
real(kind=c_double), dimension(*) :: u_coords
real(kind=c_double), dimension(*) :: u_exps
real(kind=c_double), dimension(*) :: u_coefs
integer(kind=c_int), dimension(*) :: u_ams
integer(kind=c_int), dimension(*) :: u_ns
integer(kind=c_int), dimension(*) :: u_lengths
Call graph
add_ecpder calls set_ecp_basis
add_ecpint calls set_ecp_basis
grad_1e_ecp calls add_ecpder
omp_hst calls add_ecpint
hf_gradient calls grad_1e_ecp
int1e calls omp_hst
tdhf_1e_grad calls grad_1e_ecp
tdhf_gradient calls tdhf_1e_grad
tdhf_gradient_c calls tdhf_gradient