show_message – OPENQP
show_message Interface
3 statements
Source File
public interface show_message
Called by
Module Procedures
private subroutine show_message_text(message, stopmode)
@brief Print simple message @author Igor S. Gerasimov @date July, 2021 - Initial release - @params message (in) - message for displaying @params stopmode (in, optional) - is aborting required?
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: message
logical, intent(in), optional :: stopmode
private subroutine show_message_with_integer(format, message, value, stopmode)
@brief Print simple message @details write(,format) message, value @author Igor S. Gerasimov @date July, 2021 - Initial release - @params format (in) - format for displaying @params message (in) - message for displaying @params value (in) - value for displaying @params stopmode (in, optional) - is aborting required?
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: format
character(len=*), intent(in) :: message
integer, intent(in) :: value
logical, intent(in), optional :: stopmode
private subroutine show_message_with_double(format, message, value, stopmode)
@brief Print simple message @details write(,format) message, value @author Igor S. Gerasimov @date July, 2021 - Initial release - @params format (in) - format for displaying @params message (in) - message for displaying @params value (in) - value for displaying @params stopmode (in, optional) - is aborting required?
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: format
character(len=*), intent(in) :: message
real(kind=dp), intent(in) :: value
logical, intent(in), optional :: stopmode
private subroutine show_message_with_double_and_text(format, message1, value, message2, stopmode)
@brief Print simple message @details write(,format) message1, value, message2 @author Igor S. Gerasimov @date July, 2021 - Initial release - @params format (in) - format for displaying @params message1 (in) - message for displaying @params value (in) - value for displaying @params message2 (in) - message for displaying @params stopmode (in, optional) - is aborting required?
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: format
character(len=*), intent(in) :: message1
real(kind=dp), intent(in) :: value
character(len=*), intent(in) :: message2
logical, intent(in), optional :: stopmode
private subroutine show_message_with_integer_and_text(format, message1, value, message2, stopmode)
@brief Print simple message @details write(,format) message1, value, message2 @author Igor S. Gerasimov @date July, 2021 - Initial release - @params format (in) - format for displaying @params message1 (in) - message for displaying @params value (in) - value for displaying @params message2 (in) - message for displaying @params stopmode (in, optional) - is aborting required?
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: format
character(len=*), intent(in) :: message1
integer, intent(in) :: value
character(len=*), intent(in) :: message2
logical, intent(in), optional :: stopmode
private subroutine show_message_with_keys(message, format, keys, stopmode)
@brief Print simple message @details write(,'(A)') message write(,format) keys @author Igor S. Gerasimov @date July, 2021 - Initial release - @params message (in) - message for displaying @params format (in) - format for displaying @params keys (in) - keys for displaying @params stopmode (in, optional) - is aborting required?
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: message
character(len=*), intent(in) :: format
character(len=*), intent(in), optional :: keys(:)
logical, intent(in), optional :: stopmode
Call graph
check_status calls show_message
corresponding_orbital_projection calls show_message, diag_symm_full, oqp_dgemm_i64, oqp_dswap_i64, oqp_dsyrk_i64, schmd
dft_initialize calls show_message, libxc_input, add_grid
dftder calls show_message, check_status, unpack_matrix, derexc_blk
diag_symm_full calls show_message
diag_symm_packed calls show_message
electric_moments calls show_message, check_status, multipole_integrals, triangular_to_full
get_ab_initio_density calls show_message, orb_to_dens
get_ab_initio_orbital calls show_message, diag_symm_full, oqp_dgemm_i64, orthogonal_transform, unpack_matrix
get_mrsf_transition_density calls show_message
get_spin_square calls show_message, oqp_dgemm_i64, pack_matrix, unpack_matrix
get_states_overlap calls show_message, mrsfxvec
get_td_transition_dipole calls show_message, multipole_integrals, orthogonal_transform, pack_matrix
get_transition_density calls show_message
get_transition_dipole calls show_message, multipole_integrals, orthogonal_transform, pack_matrix
grd2_driver calls show_message, ints_exchange
guess_hcore calls show_message, get_ab_initio_density, get_ab_initio_orbital, matrix_invsqrt
hf_gradient calls show_message, check_status, dft_initialize, dftder, grd2_driver, eijden, grad_ee_kinetic, grad_ee_overlap, grad_en_hellman_feynman, grad_en_pulay
huckel_guess calls show_message, corresponding_orbital_projection, diag_symm_full, matrix_invsqrt, mksphar, oqp_dgemm_i64, oqp_dgeqrf_i64, oqp_dormqr_i64, oqp_dsymm_i64, orthogonal_transform_sym, unpack_matrix
ints_exchange calls show_message
lebedev_get_grid calls show_message
libxc_input calls show_message, add_functional
lowdin calls show_message, run_population_analysis
matrix_invsqrt calls show_message, diag_symm_packed
mksphar calls show_message
mrsfcbc calls show_message, oqp_dgemm_i64
mrsfesum calls show_message, oqp_dgemm_i64
mrsfmntoia calls show_message, oqp_dgemm_i64, oqp_dgemv_i64
mrsfsp calls show_message, oqp_dgemm_i64
mrsfxvec calls show_message
mulliken calls show_message, run_population_analysis
multipole_integrals calls show_message
oqp_caxpy_i64 calls show_message
oqp_ccopy_i64 calls show_message
oqp_cdotc_i64 calls show_message
oqp_cdotu_i64 calls show_message
oqp_cgbmv_i64 calls show_message
oqp_cgemm_i64 calls show_message
oqp_cgemv_i64 calls show_message
oqp_cgerc_i64 calls show_message
oqp_cgeru_i64 calls show_message
oqp_chbmv_i64 calls show_message
oqp_chemm_i64 calls show_message
oqp_chemv_i64 calls show_message
oqp_cher2_i64 calls show_message
oqp_cher2k_i64 calls show_message
oqp_cher_i64 calls show_message
oqp_cherk_i64 calls show_message
oqp_chpmv_i64 calls show_message
oqp_chpr2_i64 calls show_message
oqp_chpr_i64 calls show_message
oqp_cscal_i64 calls show_message
oqp_csrot_i64 calls show_message
oqp_csscal_i64 calls show_message
oqp_cswap_i64 calls show_message
oqp_csymm_i64 calls show_message
oqp_csyr2k_i64 calls show_message
oqp_csyrk_i64 calls show_message
oqp_ctbmv_i64 calls show_message
oqp_ctbsv_i64 calls show_message
oqp_ctpmv_i64 calls show_message
oqp_ctpsv_i64 calls show_message
oqp_ctrmm_i64 calls show_message
oqp_ctrmv_i64 calls show_message
oqp_ctrsm_i64 calls show_message
oqp_ctrsv_i64 calls show_message
oqp_dasum_i64 calls show_message
oqp_daxpy_i64 calls show_message
oqp_dcopy_i64 calls show_message
oqp_ddot_i64 calls show_message
oqp_dgbmv_i64 calls show_message
oqp_dgemm_i64 calls show_message
oqp_dgemv_i64 calls show_message
oqp_dgeqrf_i64 calls show_message
oqp_dger_i64 calls show_message
oqp_dgesv_i64 calls show_message
oqp_dgetri_i64 calls show_message
oqp_dgglse_i64 calls show_message
oqp_dnrm2_i64 calls show_message
oqp_dorgqr_i64 calls show_message
oqp_dormqr_i64 calls show_message
oqp_drot_i64 calls show_message
oqp_drotm_i64 calls show_message
oqp_dsbmv_i64 calls show_message
oqp_dscal_i64 calls show_message
oqp_dsdot_i64 calls show_message
oqp_dspmv_i64 calls show_message
oqp_dspr2_i64 calls show_message
oqp_dspr_i64 calls show_message
oqp_dswap_i64 calls show_message
oqp_dsymm_i64 calls show_message
oqp_dsymv_i64 calls show_message
oqp_dsyr2_i64 calls show_message
oqp_dsyr2k_i64 calls show_message
oqp_dsyr_i64 calls show_message
oqp_dsyrk_i64 calls show_message
oqp_dsysv_i64 calls show_message
oqp_dtbmv_i64 calls show_message
oqp_dtbsv_i64 calls show_message
oqp_dtpmv_i64 calls show_message
oqp_dtpsv_i64 calls show_message
oqp_dtpttr_i64 calls show_message
oqp_dtrmm_i64 calls show_message
oqp_dtrmv_i64 calls show_message
oqp_dtrsm_i64 calls show_message
oqp_dtrsv_i64 calls show_message
oqp_dtrttp_i64 calls show_message
oqp_dzasum_i64 calls show_message
oqp_dznrm2_i64 calls show_message
oqp_icamax_i64 calls show_message
oqp_idamax_i64 calls show_message
oqp_isamax_i64 calls show_message
oqp_izamax_i64 calls show_message
oqp_resp_charges calls show_message, lebedev_get_grid, oqp_dgemm_i64, oqp_dgemv_i64, oqp_dgesv_i64
oqp_sasum_i64 calls show_message
oqp_saxpy_i64 calls show_message
oqp_scasum_i64 calls show_message
oqp_scnrm2_i64 calls show_message
oqp_scopy_i64 calls show_message
oqp_sdot_i64 calls show_message
oqp_sdsdot_i64 calls show_message
oqp_sgbmv_i64 calls show_message
oqp_sgemm_i64 calls show_message
oqp_sgemv_i64 calls show_message
oqp_sger_i64 calls show_message
oqp_snrm2_i64 calls show_message
oqp_srot_i64 calls show_message
oqp_srotm_i64 calls show_message
oqp_ssbmv_i64 calls show_message
oqp_sscal_i64 calls show_message
oqp_sspmv_i64 calls show_message
oqp_sspr2_i64 calls show_message
oqp_sspr_i64 calls show_message
oqp_sswap_i64 calls show_message
oqp_ssymm_i64 calls show_message
oqp_ssymv_i64 calls show_message
oqp_ssyr2_i64 calls show_message
oqp_ssyr2k_i64 calls show_message
oqp_ssyr_i64 calls show_message
oqp_ssyrk_i64 calls show_message
oqp_stbmv_i64 calls show_message
oqp_stbsv_i64 calls show_message
oqp_stpmv_i64 calls show_message
oqp_stpsv_i64 calls show_message
oqp_strmm_i64 calls show_message
oqp_strmv_i64 calls show_message
oqp_strsm_i64 calls show_message
oqp_strsv_i64 calls show_message
oqp_tdhf_z_vector calls show_message, run, dft_initialize, oqp_dgemm_i64, oqp_dsyr2k_i64, orthogonal_transform, triangular_to_full, pack_matrix, unpack_matrix, set_screening, tddft_fxc, tddft_gxc, tdhf_unrelaxed_density
oqp_xerbla_i64 calls show_message
oqp_zaxpy_i64 calls show_message
oqp_zcopy_i64 calls show_message
oqp_zdotc_i64 calls show_message
oqp_zdotu_i64 calls show_message
oqp_zdrot_i64 calls show_message
oqp_zdscal_i64 calls show_message
oqp_zgbmv_i64 calls show_message
oqp_zgemm_i64 calls show_message
oqp_zgemv_i64 calls show_message
oqp_zgerc_i64 calls show_message
oqp_zgeru_i64 calls show_message
oqp_zhbmv_i64 calls show_message
oqp_zhemm_i64 calls show_message
oqp_zhemv_i64 calls show_message
oqp_zher2_i64 calls show_message
oqp_zher2k_i64 calls show_message
oqp_zher_i64 calls show_message
oqp_zherk_i64 calls show_message
oqp_zhpmv_i64 calls show_message
oqp_zhpr2_i64 calls show_message
oqp_zhpr_i64 calls show_message
oqp_zscal_i64 calls show_message
oqp_zswap_i64 calls show_message
oqp_zsymm_i64 calls show_message
oqp_zsyr2k_i64 calls show_message
oqp_zsyrk_i64 calls show_message
oqp_ztbmv_i64 calls show_message
oqp_ztbsv_i64 calls show_message
oqp_ztpmv_i64 calls show_message
oqp_ztpsv_i64 calls show_message
oqp_ztrmm_i64 calls show_message
oqp_ztrmv_i64 calls show_message
oqp_ztrsm_i64 calls show_message
oqp_ztrsv_i64 calls show_message
orthogonal_transform calls show_message, oqp_dgemm_i64
orthogonal_transform2 calls show_message, oqp_dgemm_i64
orthogonal_transform_sym calls show_message, oqp_dgemm_i64, oqp_dsymm_i64, oqp_dtpttr_i64, oqp_dtrttp_i64
pack_f90 calls show_message, oqp_dtrttp_i64
pcg_optimize calls show_message
run_population_analysis calls show_message, diag_symm_packed, oqp_dgemm_i64, unpack_matrix
scf_driver calls show_message, run, get_ab_initio_density, get_ab_initio_orbital, matrix_invsqrt, unpack_matrix, add_data, set_screening, form_rohf_fock, mo_to_ao, build_pfon_density, dftexcor
schmd calls show_message, oqp_dgeqrf_i64, oqp_dorgqr_i64
solve_linear_equations calls show_message, oqp_dsysv_i64
tdhf_1e_grad calls show_message, eijden, grad_ee_kinetic, grad_ee_overlap, grad_en_hellman_feynman, grad_en_pulay
tdhf_2e_grad calls show_message, grd2_driver
tdhf_energy calls show_message, run, dft_initialize, get_td_transition_dipole, orthogonal_transform, set_screening, mntoia, rpaeig, rpaexpndv, rparedms, tddft_fxc
tdhf_gradient calls show_message, dft_initialize, orthogonal_transform, tdhf_1e_grad, tdhf_2e_grad, unpack_matrix, tddft_xc_gradient
tdhf_mrsf_energy calls show_message, run, get_mrsf_transition_density, get_transition_density, get_transition_dipole, mrsfcbc, mrsfesum, mrsfmntoia, oqp_dgemm_i64, orthogonal_transform, orthogonal_transform_sym, unpack_matrix, set_screening, mntoia, rpaeig, rparedms, sfresvec, trfrmb
tdhf_sf_energy calls show_message, run, get_spin_square, get_transition_density, get_transition_dipole, oqp_dgemm_i64, orthogonal_transform_sym, unpack_matrix, set_screening, mntoia, rpaeig, rparedms, sfdmat, sfresvec, trfrmb
triangular_to_full calls show_message
unpack_f90 calls show_message, oqp_dtpttr_i64
pack_matrix calls pack_f90
unpack_matrix calls unpack_f90
compute calls calc_evfxc, calc_evxc, calc_xc
eijden calls orthogonal_transform_sym, unpack_matrix
fock_jk calls run, set_screening
form_rohf_fock calls orthogonal_transform2, orthogonal_transform_sym, triangular_to_full, pack_matrix, unpack_matrix
get_state_overlap_c calls get_states_overlap
guess_hcore_c calls guess_hcore
guess_huckel calls get_ab_initio_density, huckel_guess
guess_json calls get_ab_initio_density
hf_energy calls check_status, dft_initialize, scf_driver
mntoia calls oqp_dgemm_i64
mo_to_ao calls oqp_dgemm_i64, oqp_dsymm_i64, pack_matrix, unpack_matrix
mo_tran_gemm_ calls oqp_dgemm_i64
mo_tran_symm_ calls oqp_dsymm_i64
mrsfqrorhs calls oqp_dgemm_i64
orb_to_dens calls oqp_dsyr2k_i64, pack_matrix
resp_charges_c calls oqp_resp_charges
rpaeig calls diag_symm_packed, oqp_dgemm_i64, oqp_dtrttp_i64
rpaexpndv calls oqp_dgemm_i64
rparedms calls oqp_dgemm_i64
sfdmat calls oqp_dgemm_i64, orthogonal_transform, pack_matrix
sfresvec calls oqp_dgemm_i64
sfrorhs calls oqp_dgemm_i64
sfrowcal calls oqp_dgemm_i64
tddft_fxc calls triangular_to_full, run_xc
tddft_gxc calls triangular_to_full, run_xc
tdhf_energy_c calls tdhf_energy
tdhf_gradient_c calls tdhf_gradient
tdhf_mrsf_energy_c calls tdhf_mrsf_energy
tdhf_sf_energy_c calls tdhf_sf_energy
tdhf_unrelaxed_density calls oqp_dgemm_i64, orthogonal_transform, pack_matrix
tdhf_z_vector_c calls oqp_tdhf_z_vector
trfrmb calls oqp_dgemm_i64
utddft_fxc calls triangular_to_full, run_xc
build_pfon_density calls pack_matrix
grad_ee_kinetic calls unpack_matrix
grad_ee_overlap calls unpack_matrix
grad_en_hellman_feynman calls unpack_matrix
grad_en_pulay calls unpack_matrix
guess_huckel_c calls guess_huckel
guess_json_c calls guess_json
run_xc calls compxc
derexc_blk calls run_xc
dmatd_blk calls run_xc
tddft_xc_gradient calls run_xc
utddft_xc_gradient calls run_xc
dftexcor calls dmatd_blk