tagarray_get_data – OPENQP
tagarray_get_data Interface
5 statements
Source File
public interface tagarray_get_data
Called by
Module Procedures
private subroutine tagarray_get_data_int64_val(container, tag, ptr, status)
Arguments
Type Intent Optional Attributes Name
type(container_t), intent(inout) :: container
character(len=*), intent(in) :: tag
integer(kind=8), pointer :: ptr
integer(kind=c_int32_t), intent(out), optional :: status
private subroutine tagarray_get_data_int64_1d(container, tag, ptr, status)
Arguments
Type Intent Optional Attributes Name
type(container_t), intent(inout) :: container
character(len=*), intent(in) :: tag
integer(kind=8), pointer :: ptr(:)
integer(kind=c_int32_t), intent(out), optional :: status
private subroutine tagarray_get_data_int64_2d(container, tag, ptr, status)
Arguments
Type Intent Optional Attributes Name
type(container_t), intent(inout) :: container
character(len=*), intent(in) :: tag
integer(kind=8), pointer :: ptr(:,:)
integer(kind=c_int32_t), intent(out), optional :: status
private subroutine tagarray_get_data_int64_3d(container, tag, ptr, status)
Arguments
Type Intent Optional Attributes Name
type(container_t), intent(inout) :: container
character(len=*), intent(in) :: tag
integer(kind=8), pointer :: ptr(:,:,:)
integer(kind=c_int32_t), intent(out), optional :: status
private subroutine tagarray_get_data_real64_val(container, tag, ptr, status)
Arguments
Type Intent Optional Attributes Name
type(container_t), intent(inout) :: container
character(len=*), intent(in) :: tag
real(kind=8), pointer :: ptr
integer(kind=c_int32_t), intent(out), optional :: status
private subroutine tagarray_get_data_real64_1d(container, tag, ptr, status)
Arguments
Type Intent Optional Attributes Name
type(container_t), intent(inout) :: container
character(len=*), intent(in) :: tag
real(kind=8), pointer :: ptr(:)
integer(kind=c_int32_t), intent(out), optional :: status
private subroutine tagarray_get_data_real64_2d(container, tag, ptr, status)
Arguments
Type Intent Optional Attributes Name
type(container_t), intent(inout) :: container
character(len=*), intent(in) :: tag
real(kind=8), pointer :: ptr(:,:)
integer(kind=c_int32_t), intent(out), optional :: status
private subroutine tagarray_get_data_real64_3d(container, tag, ptr, status)
Arguments
Type Intent Optional Attributes Name
type(container_t), intent(inout) :: container
character(len=*), intent(in) :: tag
real(kind=8), pointer :: ptr(:,:,:)
integer(kind=c_int32_t), intent(out), optional :: status
private subroutine tagarray_get_data_char8_val(container, tag, ptr, status)
Arguments
Type Intent Optional Attributes Name
type(container_t), intent(inout) :: container
character(len=*), intent(in) :: tag
character(kind=c_char, len=*), pointer :: ptr
integer(kind=c_int32_t), intent(out), optional :: status
private subroutine tagarray_get_data_char8_1d(container, tag, ptr, status)
Arguments
Type Intent Optional Attributes Name
type(container_t), intent(inout) :: container
character(len=*), intent(in) :: tag
character(kind=c_char, len=*), pointer :: ptr(:)
integer(kind=c_int32_t), intent(out), optional :: status
Call graph
dftder calls tagarray_get_data
eijden calls tagarray_get_data
electric_moments calls tagarray_get_data
get_states_overlap calls tagarray_get_data
get_structures_ao_overlap calls tagarray_get_data
guess_hcore calls tagarray_get_data
guess_huckel calls tagarray_get_data
guess_json calls tagarray_get_data
hf_gradient calls tagarray_get_data, dftder, eijden
int1e calls tagarray_get_data
oqp_apply_basis calls tagarray_get_data
oqp_banner calls tagarray_get_data
oqp_resp_charges calls tagarray_get_data
oqp_tdhf_z_vector calls tagarray_get_data
print_eigvec_vals_labeled calls tagarray_get_data
run_population_analysis calls tagarray_get_data
scf_driver calls tagarray_get_data, print_mo_range
tdhf_1e_grad calls tagarray_get_data, eijden
tdhf_energy calls tagarray_get_data
tdhf_gradient calls tagarray_get_data, tdhf_1e_grad
tdhf_mrsf_energy calls tagarray_get_data
tdhf_sf_energy calls tagarray_get_data
apply_basis_c calls oqp_apply_basis
get_state_overlap_c calls get_states_overlap
get_structures_ao_overlap_c calls get_structures_ao_overlap
guess_hcore_c calls guess_hcore
guess_huckel_c calls guess_huckel
guess_json_c calls guess_json
hf_energy calls scf_driver
lowdin calls run_population_analysis
mulliken calls run_population_analysis
oqp_banner_c calls oqp_banner
print_mo_range calls print_eigvec_vals_labeled
resp_charges_c calls oqp_resp_charges
tdhf_energy_c calls tdhf_energy
tdhf_gradient_c calls tdhf_gradient
tdhf_mrsf_energy_c calls tdhf_mrsf_energy
tdhf_sf_energy_c calls tdhf_sf_energy
tdhf_z_vector_c calls oqp_tdhf_z_vector