unpack_matrix – OPENQP
unpack_matrix Interface
3 statements
Source File
public interface unpack_matrix
Calls
Called by
Module Procedures
public subroutine UNPACK_F90(AP, A, UPLO)
@brief Fortran-90 routine for unpacking 1D array to symmetric matrix
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: AP(*)
real(kind=dp), intent(out) :: A(:,:)
character(len=1), intent(in), optional :: UPLO
private subroutine UNPACK_F77(AP, A, N, UPLO) bind(C, name="MTX_UNPACK")
@brief Fortran-77 routine for unpacking 1D array to symmetric matrix
@details LAPACK returns only upper or lower filling of matrix
@date 6 October 2021 - Initial release - @author Igor S. Gerasimov
@param[in] AP - packed matrix @param[out] A - matrix for unpacking (N x N) @param[in] N - shape of matrix A @param[in] UPLO - format of packed matrix, U for upper and L for lower
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: AP(*)
real(kind=dp), intent(out) :: A(N,*)
integer, intent(in) :: N
character(len=1), intent(in) :: UPLO
Call graph
unpack_matrix calls unpack_f90
unpack_f90 calls show_message, oqp_dtpttr_i64
oqp_dtpttr_i64 calls show_message, dtpttr
dftder calls unpack_matrix
eijden calls unpack_matrix
form_rohf_fock calls unpack_matrix
get_ab_initio_orbital calls unpack_matrix
get_spin_square calls unpack_matrix
grad_ee_kinetic calls unpack_matrix
grad_ee_overlap calls unpack_matrix
grad_en_hellman_feynman calls unpack_matrix
grad_en_pulay calls unpack_matrix
huckel_guess calls unpack_matrix
mo_to_ao calls unpack_matrix
oqp_tdhf_z_vector calls unpack_matrix
run_population_analysis calls unpack_matrix
scf_driver calls unpack_matrix, add_data, form_rohf_fock, get_ab_initio_orbital, mo_to_ao
tdhf_gradient calls unpack_matrix, tdhf_1e_grad
tdhf_mrsf_energy calls unpack_matrix
tdhf_sf_energy calls unpack_matrix, get_spin_square
guess_hcore calls get_ab_initio_orbital
guess_huckel calls huckel_guess
hf_energy calls scf_driver
hf_gradient calls dftder, eijden, grad_ee_kinetic, grad_ee_overlap, grad_en_hellman_feynman, grad_en_pulay
lowdin calls run_population_analysis
mulliken calls run_population_analysis
tdhf_1e_grad calls eijden, grad_ee_kinetic, grad_ee_overlap, grad_en_hellman_feynman, grad_en_pulay
tdhf_gradient_c calls tdhf_gradient
tdhf_mrsf_energy_c calls tdhf_mrsf_energy
tdhf_sf_energy_c calls tdhf_sf_energy
tdhf_z_vector_c calls oqp_tdhf_z_vector
guess_hcore_c calls guess_hcore
guess_huckel_c calls guess_huckel