workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"'
      when: never
    - if: '$CI_COMMIT_BRANCH'

stages:
  - test

docs-build:
  stage: test
  image: python:3.11-bookworm
  tags:
    - small-linux
  script:
    - python -m pip install -r docs/requirements.txt
    - mkdocs build --strict
  artifacts:
    paths:
      - site/
    expire_in: 1 week
