! Spin-polarized semilocal XC chain rules for the MRSF-TDDFT Hessian.
!
! The state-dependent XC scalar is
!
!   q(g,p) = e_xc(g) + e_xc,g(g) . p,
!
! where g contains the alpha/beta LDA or GGA ground-density variables and p
! is their direction generated by the relaxed MRSF density.  This density-only
! representation is the open-shell analogue of Nakata's TDDFT Hessian chain
! rule and does not introduce a configuration-state expansion.
module mod_dft_gridint_mrsf_xc_hessian_point

  use precision, only: fp

  implicit none
  private

  public :: mrsf_xc_weighted_fixed_hessian
  public :: mrsf_xc_weighted_response_row
  public :: mrsf_xc_kernel_fock_coefficients

contains

!> Build the spin-resolved AO coefficients of K_xc[D](P) and their total
!> nuclear derivatives from the first three XC derivatives.
  pure subroutine mrsf_xc_kernel_fock_coefficients(first,second,third,probe, &
      dground,dprobe,is_gga,grad_ground,grad_probe,dgrad_ground,dgrad_probe, &
      v_r,coefficient,dv_r,dcoefficient,status)
    real(fp), intent(in) :: first(:),second(:,:),third(:,:,:),probe(:)
    real(fp), intent(in) :: dground(:,:),dprobe(:,:)
    logical, intent(in) :: is_gga
    real(fp), intent(in) :: grad_ground(3,2),grad_probe(3,2)
    real(fp), intent(in) :: dgrad_ground(:,:,:),dgrad_probe(:,:,:)
    real(fp), intent(out) :: v_r(2),coefficient(3,2),dv_r(:,:), &
      dcoefficient(:,:,:)
    integer, intent(out) :: status

    real(fp), allocatable :: kernel(:),dkernel(:,:),dfirst(:,:)
    integer :: coordinate,i,j,k,ncoord,nvar

    nvar=size(first)
    ncoord=size(dground,2)
    status=0
    v_r=0.0_fp
    coefficient=0.0_fp
    dv_r=0.0_fp
    dcoefficient=0.0_fp
    if((nvar/=2 .and. nvar/=5) .or. ncoord<=0 .or. &
       (is_gga .neqv. nvar==5) .or. size(probe)/=nvar .or. &
       any(shape(second)/=[nvar,nvar]) .or. &
       any(shape(third)/=[nvar,nvar,nvar]) .or. &
       any(shape(dground)/=[nvar,ncoord]) .or. &
       any(shape(dprobe)/=[nvar,ncoord]) .or. &
       any(shape(dgrad_ground)/=[3,2,ncoord]) .or. &
       any(shape(dgrad_probe)/=[3,2,ncoord]) .or. &
       any(shape(dv_r)/=[2,ncoord]) .or. &
       any(shape(dcoefficient)/=[3,2,ncoord])) then
      status=-1
      return
    end if
    allocate(kernel(nvar),dkernel(nvar,ncoord),dfirst(nvar,ncoord))
    kernel=matmul(second,probe)
    do coordinate=1,ncoord
      dfirst(:,coordinate)=matmul(second,dground(:,coordinate))
      dkernel(:,coordinate)=matmul(second,dprobe(:,coordinate))
      do i=1,nvar
        do j=1,nvar
          do k=1,nvar
            dkernel(i,coordinate)=dkernel(i,coordinate)+ &
              third(i,j,k)*dground(j,coordinate)*probe(k)
          end do
        end do
      end do
    end do
    v_r=kernel(1:2)
    dv_r=dkernel(1:2,:)
    if(.not.is_gga) then
      deallocate(kernel,dkernel,dfirst)
      return
    end if
    coefficient(:,1)=2.0_fp*kernel(3)*grad_ground(:,1)+ &
      kernel(5)*grad_ground(:,2)+2.0_fp*first(3)*grad_probe(:,1)+ &
      first(5)*grad_probe(:,2)
    coefficient(:,2)=2.0_fp*kernel(4)*grad_ground(:,2)+ &
      kernel(5)*grad_ground(:,1)+2.0_fp*first(4)*grad_probe(:,2)+ &
      first(5)*grad_probe(:,1)
    do coordinate=1,ncoord
      dcoefficient(:,1,coordinate)= &
        2.0_fp*dkernel(3,coordinate)*grad_ground(:,1)+ &
        2.0_fp*kernel(3)*dgrad_ground(:,1,coordinate)+ &
        dkernel(5,coordinate)*grad_ground(:,2)+ &
        kernel(5)*dgrad_ground(:,2,coordinate)+ &
        2.0_fp*dfirst(3,coordinate)*grad_probe(:,1)+ &
        2.0_fp*first(3)*dgrad_probe(:,1,coordinate)+ &
        dfirst(5,coordinate)*grad_probe(:,2)+ &
        first(5)*dgrad_probe(:,2,coordinate)
      dcoefficient(:,2,coordinate)= &
        2.0_fp*dkernel(4,coordinate)*grad_ground(:,2)+ &
        2.0_fp*kernel(4)*dgrad_ground(:,2,coordinate)+ &
        dkernel(5,coordinate)*grad_ground(:,1)+ &
        kernel(5)*dgrad_ground(:,1,coordinate)+ &
        2.0_fp*dfirst(4,coordinate)*grad_probe(:,2)+ &
        2.0_fp*first(4)*dgrad_probe(:,2,coordinate)+ &
        dfirst(5,coordinate)*grad_probe(:,1)+ &
        first(5)*dgrad_probe(:,1,coordinate)
    end do
    deallocate(kernel,dkernel,dfirst)
  end subroutine mrsf_xc_kernel_fock_coefficients

!-----------------------------------------------------------------------------

!> Add the fixed-density second nuclear derivative of q(g,p) at one point.
  pure subroutine mrsf_xc_weighted_fixed_hessian(exc,first,second,third, &
      probe,dground,dprobe,d2ground,d2probe,quadrature_scale,weight, &
      dweight,d2weight,hessian,status)
    real(fp), intent(in) :: exc,first(:),second(:,:),third(:,:,:),probe(:)
    real(fp), intent(in) :: dground(:,:,:),dprobe(:,:,:)
    real(fp), intent(in) :: d2ground(:,:,:,:,:),d2probe(:,:,:,:,:)
    real(fp), intent(in) :: quadrature_scale,weight,dweight(:,:), &
      d2weight(:,:,:,:)
    real(fp), intent(inout) :: hessian(:,:,:,:)
    integer, intent(out) :: status

    real(fp), allocatable :: first_total(:),second_total(:,:)
    real(fp) :: value,derivative_a,derivative_b,second_ab
    integer :: nvar,natom,atom_a,atom_b,cart_a,cart_b,k

    nvar=size(first)
    natom=size(dweight,2)
    status=0
    if(nvar<=0 .or. natom<=0 .or. size(probe)/=nvar .or. &
       any(shape(second)/=[nvar,nvar]) .or. &
       any(shape(third)/=[nvar,nvar,nvar]) .or. &
       any(shape(dground)/=[nvar,3,natom]) .or. &
       any(shape(dprobe)/=[nvar,3,natom]) .or. &
       any(shape(d2ground)/=[nvar,3,3,natom,natom]) .or. &
       any(shape(d2probe)/=[nvar,3,3,natom,natom]) .or. &
       any(shape(d2weight)/=[3,natom,3,natom]) .or. &
       any(shape(hessian)/=[3,3,natom,natom])) then
      status=-1
      return
    end if
    allocate(first_total(nvar),second_total(nvar,nvar))
    first_total=first+matmul(second,probe)
    second_total=second
    do k=1,nvar
      second_total=second_total+probe(k)*third(k,:,:)
    end do
    value=exc+dot_product(first,probe)
    do atom_a=1,natom
      do cart_a=1,3
        derivative_a=dot_product(first_total, &
          dground(:,cart_a,atom_a))+dot_product(first, &
          dprobe(:,cart_a,atom_a))
        do atom_b=1,natom
          do cart_b=1,3
            derivative_b=dot_product(first_total, &
              dground(:,cart_b,atom_b))+dot_product(first, &
              dprobe(:,cart_b,atom_b))
            second_ab=dot_product(first_total, &
              d2ground(:,cart_a,cart_b,atom_a,atom_b))+ &
              dot_product(first, &
              d2probe(:,cart_a,cart_b,atom_a,atom_b))+ &
              dot_product(dground(:,cart_a,atom_a),matmul(second_total, &
              dground(:,cart_b,atom_b)))+ &
              dot_product(dground(:,cart_a,atom_a),matmul(second, &
              dprobe(:,cart_b,atom_b)))+ &
              dot_product(dprobe(:,cart_a,atom_a),matmul(second, &
              dground(:,cart_b,atom_b)))
            hessian(cart_a,cart_b,atom_a,atom_b)= &
              hessian(cart_a,cart_b,atom_a,atom_b)+quadrature_scale*( &
              weight*second_ab+dweight(cart_a,atom_a)*derivative_b+ &
              dweight(cart_b,atom_b)*derivative_a+ &
              d2weight(cart_a,atom_a,cart_b,atom_b)*value)
          end do
        end do
      end do
    end do
    deallocate(first_total,second_total)
  end subroutine mrsf_xc_weighted_fixed_hessian

!> Add one density-response direction to the derivative of the XC gradient.
  pure subroutine mrsf_xc_weighted_response_row(first,second,third,probe, &
      dground,dprobe,response_ground,response_probe, &
      dresponse_ground,dresponse_probe,quadrature_scale,weight,dweight, &
      row,status)
    real(fp), intent(in) :: first(:),second(:,:),third(:,:,:),probe(:)
    real(fp), intent(in) :: dground(:,:,:),dprobe(:,:,:)
    real(fp), intent(in) :: response_ground(:),response_probe(:)
    real(fp), intent(in) :: dresponse_ground(:,:,:), &
      dresponse_probe(:,:,:)
    real(fp), intent(in) :: quadrature_scale,weight,dweight(:,:)
    real(fp), intent(inout) :: row(:,:)
    integer, intent(out) :: status

    real(fp), allocatable :: first_total(:),delta_first_total(:), &
      second_ground(:)
    real(fp) :: delta_value,delta_derivative
    integer :: nvar,natom,atom,cart,i,j,k

    nvar=size(first)
    natom=size(dweight,2)
    status=0
    if(nvar<=0 .or. natom<=0 .or. size(probe)/=nvar .or. &
       size(response_ground)/=nvar .or. size(response_probe)/=nvar .or. &
       any(shape(second)/=[nvar,nvar]) .or. &
       any(shape(third)/=[nvar,nvar,nvar]) .or. &
       any(shape(dground)/=[nvar,3,natom]) .or. &
       any(shape(dprobe)/=[nvar,3,natom]) .or. &
       any(shape(dresponse_ground)/=[nvar,3,natom]) .or. &
       any(shape(dresponse_probe)/=[nvar,3,natom]) .or. &
       any(shape(row)/=[3,natom])) then
      status=-1
      return
    end if
    allocate(first_total(nvar),delta_first_total(nvar), &
      second_ground(nvar))
    first_total=first+matmul(second,probe)
    second_ground=matmul(second,response_ground)
    delta_first_total=matmul(second,response_ground+response_probe)
    do i=1,nvar
      do j=1,nvar
        do k=1,nvar
          delta_first_total(i)=delta_first_total(i)+ &
            third(i,j,k)*response_ground(j)*probe(k)
        end do
      end do
    end do
    delta_value=dot_product(first_total,response_ground)+ &
      dot_product(first,response_probe)
    do atom=1,natom
      do cart=1,3
        delta_derivative=dot_product(delta_first_total, &
          dground(:,cart,atom))+dot_product(first_total, &
          dresponse_ground(:,cart,atom))+dot_product(second_ground, &
          dprobe(:,cart,atom))+dot_product(first, &
          dresponse_probe(:,cart,atom))
        row(cart,atom)=row(cart,atom)+quadrature_scale*( &
          dweight(cart,atom)*delta_value+weight*delta_derivative)
      end do
    end do
    deallocate(first_total,delta_first_total,second_ground)
  end subroutine mrsf_xc_weighted_response_row

end module mod_dft_gridint_mrsf_xc_hessian_point
